#!/bin/bash
# Date : (2012-05-18 16-10)
# Last revision : (2013-03-30 10-27)
# Wine version used : 1.4.1
# Distribution used to test : Ubuntu 12.04 LTS
# Author : Jan Nytra jannytra@seznam.cz
#    updated by Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="knights_and_merchants_the_peasants_rebellion"
PREFIX="KnightsAndMerchantsTPR_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Knights and Merchants: The Peasants Rebellion"
SHORTCUT_NAME="Knights and Merchants: The Peasants Rebellion"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1271
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Joymania Development / TopWare Interactive " "http://www.gog.com/gamecard/$GOGID" "Jan Nytra" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "6f7212f523a94aa606f39eaf2f3116b8"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "KM_TPR.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;StrategyGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Knights and Merchants TPR/manual.pdf"
# C:\Program Files\GOG.com\Knights and Merchants TPR/readme.pdf

POL_SetupWindow_Close

exit 0
