#!/bin/bash
# PlayOnLinux Function
# Date : (2010-11-14 21:00)
# Last revision : (2012-02-22 21:00)
# Author : GNU_Raziel
# Only For : http://www.playonlinux.com

FORCE_MODE=$1

cd "$POL_USER_ROOT/ressources"
mkdir -p mono210
# Downloading Mono 2.10
cd "$POL_USER_ROOT/ressources/mono210/"
if [ ! -e "mono-2.10.8-gtksharp-2.12.11-win32-1.exe" ]; then
POL_SetupWindow_download "$(eval_gettext 'Downloading Mono 2.10...')" "$TITLE" "http://download.mono-project.com/archive/2.10.8/windows-installer/1/mono-2.10.8-gtksharp-2.12.11-win32-1.exe"
fi

# Check if mono210 is already installed
CHECK_MONO210=`find $WINEPREFIX -name "mono-2.0.dll"`
if [ "$CHECK_MONO210" == "" ] || [ "$FORCE_MODE" == "--force" ]; then
	POL_Wine start /unix "mono-2.10.8-gtksharp-2.12.11-win32-1.exe" /silent
	POL_Wine_WaitExit "Mono 2.10"
fi