#!/usr/bin/env playonlinux-bash
# PlayOnLinux Function
# Date : ?
# Last revision : (2013-01-22 21-52)
# Author : NSLW based on Berillions's d3dx9 script

cd "$POL_USER_ROOT/ressources"
POL_Download_Resource "http://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe" "4cf007a355cb5f34a3c5c400113b33c3"

POL_Wine_WaitBefore "DirectX 9"

POL_SetupWindow_wait_next_signal "PlayOnLinux is installing DirectPlay" "DirectPlay"

mkdir "Directx"
cd Directx
cabextract "../directx_feb2010_redist.exe"

mkdir "dxnt"
cabextract -d "dxnt" dxnt.cab

cd "dxnt"

mv -f dplaysvr.exe "$WINEPREFIX/drive_c/windows/system32"
mv -f dplayx.dll "$WINEPREFIX/drive_c/windows/system32"
mv -f dpnet.dll "$WINEPREFIX/drive_c/windows/system32"
mv -f dpnhpast.dll "$WINEPREFIX/drive_c/windows/system32"
mv -f dpwsockx.dll "$WINEPREFIX/drive_c/windows/system32"

POL_Wine regsvr32 dplayx.dll
POL_Wine regsvr32 dpnet.dll
POL_Wine regsvr32 dpnhpast.dll

#Réglage directplay
POL_Wine_OverrideDLL native dplayx dpnet dpnhpast dpwsockx

cd "$POL_USER_ROOT/ressources"
rm -rf Directx

POL_SetupWindow_detect_exit