#!/bin/bash
# PlayOnLinux Function
# Date : (2010-09-07 19-00)
# Last revision : (2013-01-22 23-00)
# Author : GNU_Raziel
# Only For : http://www.playonlinux.com

if [ "$POL_LANG" = "fr" ]; then
	LNG_VC80_INSTALL="Installation MSvc80..."
else
	LNG_VC80_INSTALL="Installing MSvc80..."
fi

POL_Download_Resource "http://www.sweetpotatosoftware.com/files/microsoft.vc80.crt.zip" "53accbf0e1e7a67415ddcdd44f8e226e"

POL_SetupWindow_wait_next_signal "$LNG_VC80_INSTALL" "$TITLE"

cd "$WINEPREFIX/drive_c/windows/temp"
unzip "$POL_USER_ROOT/ressources/microsoft.vc80.crt.zip"
cp Microsoft.VC80.CRT/*.* ../system32/
rm -rf Microsoft.VC80.CRT

# Overriding dll
POL_Call POL_Function_OverrideDLL "native,builtin" "msvcr80"

POL_SetupWindow_detect_exit