#!/bin/bash

local GAME="$1"
# option: --altername 'basename' baseindex: get pieces starting from another index than 0
# options: --patch: patches | --bonus: bonus contents
# 2.. MD5: hash of the pieces
# Will download as many pieces as extra parameters
# Hashes are recommended for large downloads anyway
shift

local BASENAME="$GAME"
local INDEX=0
if [ "$1" = "--alternate" ]; then
	BASENAME="$2"
	INDEX="$3"
	shift 3
fi

# URL = ${BASEURL}/${GAME}/${INDEXPREFIX}${INDEX}
local BASEURL="https://secure.gog.com/downlink"
local INDEXPREFIX="en1installer"
if [ "$1" = "--patch" ]; then
        INDEXPREFIX="en1patch"
	shift
elif [ "$1" = "--bonus" ]; then
	BASEURL="https://secure.gog.com/downlink/file"
        INDEXPREFIX=""
	shift
fi

local PIECES="$#"

local GOG_REPO="$(POL_Config_Read GOG_REPO)"

if [ -z "$GOG_REPO" ]; then
	POL_SetupWindow_textbox "$(eval_gettext 'In what directory do you want to download GOG files?')" "$TITLE" "$POL_USER_ROOT/tmp/"
	GOG_REPO="$APP_ANSWER"
	POL_Config_Write GOG_REPO "$GOG_REPO"
fi


# Login / open session
local COOKIES="$POL_USER_ROOT/tmp/gog_cookies"
local COOKIES_2="$POL_USER_ROOT/tmp/gog_cookies2"
while true; do
	POL_SetupWindow_login "$(eval_gettext 'Please enter your gog.com login to download $BASENAME')" "$TITLE" "http://www.gog.com/"

	POL_SetupWindow_wait "$(eval_gettext 'Please wait...')" "$TITLE"

	rm "$COOKIES" 2> /dev/null
	rm "$COOKIES_2" 2> /dev/null
	gutm="$($POL_WGET http://www.gog.com/ -O- --user-agent="Mozilla/5.0 (Windows NT 6.1; U;WOW64; de;rv:11.0) Gecko Firefox/11.0" | sed -n 's/^.*id="gutm" value="\([^"]*\)".*$/\1/p')"
	gutm="$(POL_Website_urlencode "$gutm")"

	buk="$($POL_WGET "http://www.gog.com/user/ajax" -O- --post-data="a=get&c=gamecard&p1=false&p2=false&auth=&gutm=$gutm" --save-cookies=$COOKIES_2 --user-agent="Mozilla/5.0 (Windows NT 6.1; U;WOW64; de;rv:11.0) Gecko Firefox/11.0" |sed -n 's/^.*"buk":"\([^"]*\)".*/\1/p')"
	buk="$(POL_Website_urlencode "$buk")"

	$POL_WGET https://secure.gog.com/login --save-cookies=$COOKIES --load-cookies=$COOKIES_2 --post-data="log_email=$(POL_Website_urlencode "$POL_LOGIN")&log_password=$(POL_Website_urlencode "$POL_PASSWORD")&redirectOk=/&unlockSettings=0&btn_login=Log me in&buk=$buk" --no-check-certificate -O- --header="DNT: 1" --user-agent="Mozilla/5.0 (Windows NT 6.1; U;WOW64; de;rv:11.0) Gecko Firefox/11.0"

	unset POL_LOGIN POL_PASSWORD

	local AUTH_SESSION="$(awk '$6 == "guc_al" { print $7 }' $COOKIES)"
	[ "$AUTH_SESSION" != "0" ] && break
	unset AUTH_SESSION

	POL_SetupWindow_question "$(eval_gettext 'Gog.com login failed, try again?')" "$TITLE"
	if [ "$APP_ANSWER" = "FALSE" ]; then
		POL_SetupWindow_Close
		exit
	fi
done

# Download
[ -d "$GOG_REPO" ] || mkdir -p "$GOG_REPO"
cd "$GOG_REPO" || cd "$POL_USER_ROOT/tmp/"
POL_Debug_Message "Will download into $PWD"
local FAILURE=""

download_piece ()
{
	# 1: URL
	# 2: filename
	# 3: MD5 hash
	# 4: Title

	# Failed piece from previous download, maybe reference MD5 was corrected?
	local FAILEDPIECE="$2.failed"
	if [ -n "$3" -a ! -e "$2" -a -e "$FAILEDPIECE" ]; then
		POL_SetupWindow_wait "$(eval_gettext 'Checking piece integrity...')" "$4"
		if [ "$(POL_MD5_file $FAILEDPIECE)" = "$3" ]; then
			mv "$FAILEDPIECE" "$2"
		fi
	fi

	if [ ! -e "$2" ]; then
		local TMPPIECE="$2.part"
		POL_System_wget "$1" "$4" --no-check-certificate --load-cookies="$COOKIES" -O "$TMPPIECE"

		POL_SetupWindow_wait "$(eval_gettext 'Checking piece integrity...')" "$4"
		if [ ! -e "$TMPPIECE" ]; then
			POL_Debug_Error "Download seems to have failed"
			FAILURE=1
		elif [ -n "$3" ] && [ "$(POL_MD5_file $TMPPIECE)" != "$3" ]; then
			POL_Debug_Error "Download seems to be corrupted"
			FAILURE=1
			mv "$TMPPIECE" "$FAILEDPIECE"
		else
			mv "$TMPPIECE" "$2"
			[ -e "$FAILEDPIECE" ] && rm "$FAILEDPIECE"
		fi
	fi
}

download_piece "$BASEURL/$GAME/${INDEXPREFIX}$INDEX" "setup_$BASENAME.exe" "$1" "$BASENAME (1/$PIECES)"

if [ $PIECES -gt 1 ]; then
	local n=2
	while [ $n -le $PIECES ]; do
		download_piece "$BASEURL/$GAME/${INDEXPREFIX}$((INDEX+n-1))" "setup_$BASENAME-$((n-1)).bin" "${!n}" "$BASENAME ($n/$PIECES)"
		let n=$((n+1))
	done
fi

# Close session
rm -f "$COOKIES"

[ -n "$FAILURE" ] && POL_Debug_Fatal "One or more downloads failed"

POL_GoG_downloaded="True"
POL_GoG_location="$PWD/setup_$BASENAME.exe"
