#!/usr/bin/env playonlinux-bash
# Last revision : (2012-06-30 00:46)
# Creator: petch
#  based on POL_Install_d3dx9 by Berillions/GNU_Raziel
# Only For : http://www.playonlinux.com

# Downloading directx runtime
POL_Download_Resource "http://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe" "7c1fc2021cf57fed3c25c9b03cd0c31a"

# Extracting & Installing Dx9 dlls
POL_SetupWindow_wait_next_signal "$(eval_gettext 'Installing DirectX 9 dlls...')" "$TITLE"
cd "$POL_USER_ROOT/ressources"

install_dx_dlls () {
    local CABPATTERN="$1"
    local TARGET="$2"
    local PATTERN="$3"
    local TMPDLL="$POL_USER_ROOT/tmp/Install_d3dx9"

    mkdir "$TMPDLL"
    cabextract -d "$TMPDLL/" -L -F "$CABPATTERN" directx_Jun2010_redist.exe
    
    for x in "$TMPDLL/"*.cab; do
        cabextract -d "$TARGET/" -L -F "$PATTERN" "$x"
    done
    rm -rf "$TMPDLL"
}

if [ "$POL_ARCH" = "amd64" ]; then
	POL_Debug_Message "Extracting x86 and x64 dlls"
        install_dx_dlls '*d3dx9*x64.cab' "$WINEPREFIX/drive_c/windows/system32" '*.dll'
        install_dx_dlls '*d3dx9*x86.cab' "$WINEPREFIX/drive_c/windows/syswow64" '*.dll'
else
	POL_Debug_Message "Extracting only x86 dlls"
        install_dx_dlls '*d3dx9*x86.cab' "$WINEPREFIX/drive_c/windows/system32" '*.dll'
fi

# Overriding dlls
POL_Debug_Message "Overriding all d3dx9 dlls"
POL_Wine_OverrideDLL "native, builtin" "d3dx9_24" "d3dx9_25" "d3dx9_26" "d3dx9_27" "d3dx9_28" "d3dx9_29" "d3dx9_30" "d3dx9_31" "d3dx9_32" "d3dx9_33" "d3dx9_34" "d3dx9_35" "d3dx9_36" "d3dx9_37" "d3dx9_38" "d3dx9_39" "d3dx9_40" "d3dx9_42" "d3dx9_42" "d3dx9_43"
