#!/bin/bash

# 1 : Game to download
# 2 : Md5sum
# 3 : Number of pieces

if [ "$POL_SELECTED_FILE" ]; then
	POL_GoG_location="$POL_SELECTED_FILE"
else
	INSTALL_METHOD_BACK="$INSTALL_METHOD"
	DIRNAME_BACK="$PWD"

	if @ 2>/dev/null; then # PlayOnLinux can understand GoG_Download
		POL_SetupWindow_InstallMethod LOCAL,DOWNLOAD
	else
		INSTALL_METHOD="LOCAL"
	fi

	if [ "$INSTALL_METHOD" = "DOWNLOAD" ]; then
		cd "$POL_USER_ROOT/tmp/"
		@ POL_GoG_download "$1" "$3"
		POL_GoG_location="$POL_USER_ROOT/tmp/setup_$1.exe"
	fi
	
	if [ "$INSTALL_METHOD" = "LOCAL" ]; then
		POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" ""
		POL_GoG_location="$APP_ANSWER"
	fi

	if [ "$2" ]; then
		if [ ! "$(POL_MD5_file $POL_GoG_location)" = "$2" ]; then
			POL_Debug_Error "MD5 mismatch"
		fi
	fi
	INSTALL_METHOD="$INSTALL_METHOD_BACK"
	cd "$DIRNAME_BACK"
fi
cat << "-----END PGP SIGNATURE-----" > /dev/null
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.10 (GNU/Linux)

iEYEABECAAYFAk+B7HoACgkQ5TH6yaoTykeWqACfbzCy+7gK3B5w3ysV62fIH9Nw
Xc8AoJK6OvbA/NkBtF2tVzoA8uMA7p5j
=rYD3
-----END PGP SIGNATURE-----
