#!/bin/bash
# PlayOnLinux Function
# Date : (2010-11-14 21:00)
# Last revision : (2012-09-15 09:40)
# Author : GNU_Raziel
#   modified by petch
# Only For : http://www.playonlinux.com

FORCE_MODE=$1

mkdir "$POL_USER_ROOT/ressources/mono28"
POL_Download_Resource "http://download.mono-project.com/archive/2.8/windows-installer/9/mono-2.8-gtksharp-2.12.10-win32-9.exe" "c36436c1ba016b7cf25d8ec2480a2e03" "mono28"

# Check if mono28 is already installed
CHECK_MONO28=`find $WINEPREFIX -name "mono-2.0.dll"`
if [ "$CHECK_MONO28" = "" -o "$FORCE_MODE" = "--force" ]; then
	POL_Wine start /unix "$POL_USER_ROOT/ressources/mono28/mono-2.8-gtksharp-2.12.10-win32-9.exe" /silent
	POL_Wine_WaitExit "Mono 2.8"
fi
