#!/bin/bash

# 1 : Game to download
# 2.. : Md5sum(s) of piece(s)

if [ "$POL_SELECTED_FILE" ]; then
	POL_Debug_Message "Using selected file"
	POL_GoG_location="$POL_SELECTED_FILE"
else
	INSTALL_METHOD_BACK="$INSTALL_METHOD"

	if [ -n "$POL_WGET" ]; then # PlayOnLinux can understand GoG_Download
		POL_Debug_Message "PlayOnLinux can understand GoG_Download"
		POL_SetupWindow_InstallMethod LOCAL,DOWNLOAD
	else
		POL_Debug_Message "PlayOnLinux do not understand GoG_Download"
		INSTALL_METHOD="LOCAL"
	fi

	POL_Debug_Message "Install method $INSTALL_METHOD"

	if [ "$INSTALL_METHOD" = "DOWNLOAD" ]; then
		POL_Call POL_GoG_download "$@"
	fi

	if [ "$INSTALL_METHOD" = "LOCAL" ]; then
		POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" ""
		POL_GoG_location="$APP_ANSWER"
	fi
	INSTALL_METHOD="$INSTALL_METHOD_BACK"
fi
