#!/usr/bin/env playonlinux-bash
# PlayOnLinux Function
# Date : (2010-11-14 21:00)
# Last revision : (2013-01-22 22:29)
# Author : GNU_Raziel
# Only For : http://www.playonlinux.com

FORCE_MODE=$1

# Downloading Mono 2.10
POL_Download_Resource "http://download.mono-project.com/archive/2.10.8/windows-installer/1/mono-2.10.8-gtksharp-2.12.11-win32-1.exe" "b02fdfa076ea0cbed00195d2eec39624" "mono210"

# Check if mono210 is already installed
CHECK_MONO210=`find $WINEPREFIX -name "mono-2.0.dll"`
if [ "$CHECK_MONO210" = "" -o "$FORCE_MODE" = "--force" ]; then
	cd "$POL_USER_ROOT/ressources/mono210/"
	POL_Wine start /unix "mono-2.10.8-gtksharp-2.12.11-win32-1.exe" /silent
	POL_Wine_WaitExit "Mono 2.10"
fi