#!/bin/bash
# PlayOnLinux Function
# Date : (2009-11-19 21-50)
# Last revision : (2013-01-22 16:00)
# Author : Berillions, Tinou
# Updated by : GNU_Raziel
# Only For : http://www.playonlinux.com

# [Quentin PÂRIS] (2012-04-29 13:02)
#   Fixing bug #820
# [petch] (2013-01-22 16:00)
#   Fixing bug #1787

FORCE_MODE=$1

POL_Download_Resource "http://repository.playonlinux.com/divers/msxml3.msi" "7049c6531837341363fe69d068d001b0" "msxml3"

# Check if msxml3 is already installed
CHECK_MSXML3=`find $WINEPREFIX -name "msxml3r.dll"`
if [ "$CHECK_MSXML3" = "" -o "$FORCE_MODE" = "--force" ]; then
	# Installing msxml3
	if [ "$POL_ARCH" = "amd64" ]; then
		rm "$WINEPREFIX/drive_c/windows/syswow64/msxml3.dll"
		rm "$WINEPREFIX/drive_c/windows/system32/msxml3.dll"
	else
		rm "$WINEPREFIX/drive_c/windows/system32/msxml3.dll"
	fi
        cd "$POL_USER_ROOT/ressources/msxml3/"
	POL_Wine msiexec /i msxml3.msi /q
	POL_Wine_WaitExit "msxml3"

	# Overriding dll
	POL_Wine_OverrideDLL "native,builtin" "msxml3"
fi