#!/bin/bash
# PlayOnLinux Function
# Date : Unknown
# Last revision : (2012-05-17 21:00)
# Author : Berillions
# Updated by : GNU_Raziel
# Only For : http://www.playonlinux.com

FORCE_MODE=$1

# Downloading vcrun2005 sp1
mkdir -p "$POL_USER_ROOT/ressources/vcrun2005"
cd "$POL_USER_ROOT/ressources/vcrun2005"

# Installing x64 version
if [ "$POL_ARCH" == "amd64" ]; then
	if [ ! -e "vcredist_x64.exe" ]; then
		if [ "$POL_LANG" == "fr" ]; then
			POL_SetupWindow_download "$(eval_gettext 'Downloading vcrun2005 sp1 x64...')" "$TITLE" "http://download.microsoft.com/download/2/d/8/2d83625f-1af0-4807-9da0-5b994058d213/vcredist_x64.exe"
		else
			POL_SetupWindow_download "$(eval_gettext 'Downloading vcrun2005 sp1 x64...')" "$TITLE" "http://download.microsoft.com/download/d/4/1/d41aca8a-faa5-49a7-a5f2-ea0aa4587da0/vcredist_x64.exe"
		fi
	fi
fi

if [ ! -e "vcredist_x86.exe" ]; then
	if [ "$POL_LANG" == "fr" ]; then
		POL_SetupWindow_download "$(eval_gettext 'Downloading vcrun2005 sp1 x86...')" "$TITLE" "http://download.microsoft.com/download/a/3/7/a379292d-24f2-4bbb-841b-c2aeb1100471/vcredist_x86.exe"
	else
		POL_SetupWindow_download "$(eval_gettext 'Downloading vcrun2005 sp1 x86...')" "$TITLE" "http://download.microsoft.com/download/e/1/c/e1c773de-73ba-494a-a5ba-f24906ecf088/vcredist_x86.exe"
	fi
fi

# Check if vcrun2005 is already installed
CHECK_VC2K5=`find $WINEPREFIX -name "msdia80.dll"`
if [ "$CHECK_VC2K5" == "" ] || [ "$FORCE_MODE" == "--force" ]; then
	# Installing vcrun2005 sp1
	if [ "$POL_ARCH" == "amd64" ]; then
		rm "$WINEPREFIX/drive_c/windows/syswow64/msvcp80.dll"
		rm "$WINEPREFIX/drive_c/windows/system32/msvcp80.dll"
		POL_Wine start /unix "vcredist_x64.exe" /q
		POL_Wine_WaitExit "vcrun2005 sp1 x64"
		POL_Wine start /unix "vcredist_x86.exe" /q
		POL_Wine_WaitExit "vcrun2005 sp1 x86"
	else
		rm "$WINEPREFIX/drive_c/windows/system32/msvcp80.dll"
		POL_Wine start /unix "vcredist_x86.exe" /q
		POL_Wine_WaitExit "vcrun2005 sp1 x86"
	fi

	# Overriding dll
	POL_Wine_OverrideDLL "native,builtin" "msvcr80"
fi