#!/bin/bash
# Date : (2011-16-03 21-00)
# Last revision : (2013-01-22 23-05)
# Author : GNU_Raziel
# Only For : http://www.playonlinux.com

if [ "$POL_LANG" = "fr" ]; then
	LNG_VC90_INSTALL="Installation MSvc90..."
else
	LNG_VC90_INSTALL="Installing MSvc90..."
fi

POL_Download_Resource "http://files.playonlinux.com/Microsoft.vc90.crt.zip" "710598c9c1d03fc913146a9aa6681db8"

POL_SetupWindow_wait_next_signal "$LNG_VC90_INSTALL" "$TITLE"

cd "$WINEPREFIX/drive_c/windows/temp"
unzip "$POL_USER_ROOT/ressources/Microsoft.vc90.crt.zip"
cp Microsoft.vc90.crt/*.* ../system32/
rm -rf Microsoft.vc90.crt

# Overriding dll
POL_Call POL_Function_OverrideDLL "native,builtin" "msvcr90"

POL_SetupWindow_detect_exit