#!/usr/bin/env playonlinux-bash
# PlayOnLinux Function
 
# Date : (2009-11-21)
# Last revision : (2013-01-22 23:09)
# Author : Berillions
# Licence : 
# Depend : none

#downloading msxml4
POL_Download_Resource "http://download.microsoft.com/download/A/2/D/A2D8587D-0027-4217-9DAD-38AFDB0A177E/msxml.msi" "14e34a6cbd8f060a9c965e39b745657a"

POL_SetupWindow_wait_next_signal "PlayOnLinux is installing msxml4" "$TITLE"

cd "$REPERTOIRE/ressources"
POL_Wine msiexec /i msxml.msi /q

POL_SetupWindow_detect_exit