#!/usr/bin/env playonlinux-bash
# PlayOnLinux Function
# Date : (2010-02-12 21-00)
# Last revision : (2013-01-22 20:08)
# Author : GNU_Raziel
# Only For : http://www.playonlinux.com
# RealName: Steam

if [ "$POL_LANG" == "fr" ]; then
    STEAM_EXEC="SteamInstall_French.msi"
elif [ "$POL_LANG" == "de" ]; then
    STEAM_EXEC="SteamInstall_German.msi"
elif [ "$POL_LANG" == "es" ]; then
    STEAM_EXEC="SteamInstall_Spanish.msi"
else
    STEAM_EXEC="SteamInstall.msi"
fi

# Setting default path for installers
POL_LoadVar_PROGRAMFILES

# Downloading latest Steam
# Since we cannot validate the file with a hash (changes too often), do not put it into resources
# Otherwise in case of corrupted download, the only solution for the user is to clean his cache
# Download is not that large anyway (~8MB)
cd "$POL_USER_ROOT/tmp/"
POL_SetupWindow_download "$(eval_gettext 'Please wait while Steam is downloaded...')" "$TITLE" "http://cdn.steampowered.com/download/$STEAM_EXEC"

# Installing mandatory dependencies 
POL_Wine_InstallFonts
POL_Call POL_Function_FontsSmoothRGB

# Installing Steam
cd "$POL_USER_ROOT/tmp/"
POL_Wine msiexec /i "$STEAM_EXEC" /q
POL_Wine_WaitExit "Steam"

# Fix for Steam (cause wine crash for many games if enabled) - Empty value = disabled
POL_Wine_OverrideDLL "" "gameoverlayrenderer"

# Bug #31374 http://bugs.winehq.org/show_bug.cgi?id=31374
POL_Wine_OverrideDLL "" "dwrite"
