#!/usr/bin/env playonlinux-bash
# PlayOnLinux Function
# Date : (2011-14-05 21-00)
# Last revision : (2013-01-23 00-06)
# Author : GNU_Raziel
# Only For : http://www.playonlinux.com

if [ "$POL_LANG" == "fr" ]; then
	LNG_FILE_INSTALL="Installation XMLlite..."
else
	LNG_FILE_INSTALL="Installing XMLlite..."
fi

POL_Download_Resource "http://winezeug.googlecode.com/svn/trunk/winetricks_files/winetest.cat" "012c2f2e9a415688736e6e3f98db26f4" "xmllite"

POL_SetupWindow_wait_next_signal "$LNG_FILE_INSTALL" "$TITLE"
mkdir -p "$WINEPREFIX/drive_c/windows/system32/catroot/{f750e6c3-38ee-11d1-85e5-00c04fc295ee}"
cp -f "$POL_USER_ROOT/ressources/xmllite/winetest.cat" "$WINEPREFIX/drive_c/windows/system32/catroot/{f750e6c3-38ee-11d1-85e5-00c04fc295ee}/oem0.cat"


cd "$WINEPREFIX/drive_c/windows/system32/"
POL_Call POL_SP2_Extract xmllite.dll
#Overriding dll
POL_Call POL_Function_OverrideDLL "native" "xmllite"

POL_SetupWindow_detect_exit