#!/bin/bash

# 1 : Game to download
# 2.. : Md5sum(s) of piece(s)

if [ "$POL_SELECTED_FILE" ]; then
	POL_GoG_location="$POL_SELECTED_FILE"
else
	INSTALL_METHOD_BACK="$INSTALL_METHOD"
	DIRNAME_BACK="$PWD"

	if @ 2>/dev/null; then # PlayOnLinux can understand GoG_Download
		POL_SetupWindow_InstallMethod LOCAL,DOWNLOAD
	else
		INSTALL_METHOD="LOCAL"
	fi

	if [ "$INSTALL_METHOD" = "DOWNLOAD" ]; then
		cd "$POL_USER_ROOT/tmp/"
		@ POL_GoG_download "$@"
		POL_GoG_location="$POL_USER_ROOT/tmp/setup_$1.exe"
	fi
	
	if [ "$INSTALL_METHOD" = "LOCAL" ]; then
		POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" ""
		POL_GoG_location="$APP_ANSWER"
	fi
	INSTALL_METHOD="$INSTALL_METHOD_BACK"
	cd "$DIRNAME_BACK"
fi
