#!/bin/bash
# Date : (2013-03-21 21-40)
# Last revision : (2013-12-23 12-06)
# Wine version used : 1.4.1, 1.6.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="a_new_beginning"
PREFIX="ANewBeginning_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - A New Beginning: Final Cut"
SHORTCUT_NAME="A New Beginning"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1632
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Daedalic Entertainment" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" --alternate "setup_$GOGID" 3 "b9633cac4f7d6acfc950a45a86c78483" "e886c99679507122c613023ee76e387f" "afebbdb9ae9bed618f79e7b7ab8b2397" "97ae1edf303d06275da33dd034f44ab8"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install /nogui


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Only used by configuration tool
POL_Call POL_Install_dotnet40

# Doesn't hurt ;)
POL_Wine_rebootHi

POL_Shortcut "ANB.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;AdventureGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/A New Beginning - Final Cut/A New Beginning - Manual.pdf"

# Fix missing sound issue in cutscenes.
# See: http://wiki.winehq.org/Sound ("SDL applications").
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'unset SDL_AUDIODIVER'

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

cd "$GOGROOT/A New Beginning - Final Cut/" || exit 1
TITLE="$TITLE"

POL_Wine VisionaireConfigurationTool.exe
exit 0
_EOF_

exit 0
