#!/bin/bash
# Date : (2011-12-28 22-21)
# Last revision : (2012-10-29 01-40)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="advent_rising"
PREFIX="AdventRising_gog"
WORKING_WINE_VERSION="1.3.36"

TITLE="GOG.com - Advent Rising"
SHORTCUT_NAME="Advent Rising"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1027
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "GlyphX Games / Majesco" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "28869aa14b25d9705f65ed916458a9aa" "16038e27a471a710b06bf8d737fc3679" "3f98999aa162600b4b8cb0fe036cbe21" "e210f8aace0110d0ab20b46a1d10ee92"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_X11Drv "GrabFullScreen" "Y"
# Read on WineHQ AppDB test, not sure it's necessary
POL_Wine_Direct3D "OffscreenRenderingMode" "backbuffer"

Set_OS winxp

POL_SetupWindow_VMS "128"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "advent.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Advent Rising/manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Advent Rising/Help/ReadMe.int.txt

POL_SetupWindow_Close

exit 0
