#!/bin/bash
# Date : (2011-12-28 22-21)
# Last revision : (2012-01-22 00-49)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_advent_rising.exe 2343577 "28869aa14b25d9705f65ed916458a9aa"
# setup_advent_rising-1.bin 2097656064 "16038e27a471a710b06bf8d737fc3679"
# setup_advent_rising-2.bin 2100000000 "3f98999aa162600b4b8cb0fe036cbe21"
# setup_advent_rising-3.bin 137857989 "e210f8aace0110d0ab20b46a1d10ee92"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="AdventRising_gog"
WORKING_WINE_VERSION="1.3.36"

TITLE="$(eval_gettext 'Advent Rising (GoG release)')"
SHORTCUT_NAME="Advent Rising"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "GlyphX Games / Majesco" "http://www.gog.com/en/gamecard/advent_rising" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "setup_advent_rising.exe"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

POL_Wine_X11Drv "GrabFullScreen" "Y"
# Read on WineHQ AppDB test, not sure it's necessary
POL_Wine_Direct3D "OffscreenRenderingMode" "backbuffer"

Set_OS winxp

POL_SetupWindow_VMS "128"

# Doesn't hurt ;)
POL_Wine_reboot

cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Advent Rising/gfw_high.ico" "$REPERTOIRE/icones/32/$SHORTCUT_NAME"
POL_Shortcut "advent.exe" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Advent Rising/manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Advent Rising/Help/ReadMe.int.txt

# One last word about "Advent Revising"
POL_SetupWindow_message "$(eval_gettext 'Think about installing one of the unofficial patches "Advent Revising"\nto fix lots of known issues:\nhttp://www.miketyndall.com/setz/Advent%20Revising/\n\nNo matter what version you choose, use a Windows archiver to\nuncompress the patch inside the your prefix case-insensitively.')" "$TITLE"

POL_SetupWindow_Close

exit
