#!/bin/bash
# Date : (2012-09-16 11-43)
# Last revision : (2012-09-16 17-19)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="age_of_wonders_2_the_wizards_throne"
PREFIX="AgeOfWonders2_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="Age of Wonders 2 - The Wizard's Throne (GoG release)"
SHORTCUT_NAME="Age of Wonders 2: The Wizard's Throne"
SHORTCUT_EDITOR="$SHORTCUT_NAME - $(eval_gettext 'Editor')"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Triumph Studios" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "495087ff83958e74e80748b5737532e1"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Launcher.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "AoW2Compat"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Age of Wonders II/QuickStart.pdf"
# C:\Program Files\GOG.com\Age of Wonders II\Readme.html

POL_Shortcut "AoW2Ed.exe" "$SHORTCUT_EDITOR" "$SHORTCUT_NAME.png" ""

POL_SetupWindow_Close

exit
