#!/bin/bash
# Date : (2012-09-09 15-50)
# Last revision : (2012-09-16 17-20)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="age_of_wonders"
PREFIX="AgeOfWonders_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="Age of Wonders (GoG release)"
SHORTCUT_NAME="Age of Wonders"
SHORTCUT_EDITOR="$SHORTCUT_NAME - $(eval_gettext 'Editor')"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Triumph Studios" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "e85217d7b4cee5169be995fe2710260d"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

POL_Call POL_Install_iv50

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Launcher.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "AoWCompat"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Age of Wonders/QuickStart.pdf"
# C:\Program Files\GOG.com\Age of Wonders\Readme.txt
# C:\Program Files\GOG.com\Age of Wonders\AoWEd.exe

#POL_Shortcut "AoWEd.exe" "$SHORTCUT_EDITOR" "$SHORTCUT_NAME - Editor" ""

POL_SetupWindow_Close

exit
