#!/bin/bash
# Date : (2012-08-18 23-59)
# Last revision : (2013-05-05 18-02)
# Wine version used : 1.4-dos_support_0.6
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="alien_breed_tower_assault"
PREFIX="AlienBreed_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.6"

TITLE="GOG.com - Alien Breed and Tower Assault"
SHORTCUT_NAME1="Alien Breed"
SHORTCUT_NAME2="Alien Breed: Tower Assault"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1368
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Team17 Software" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "91d1470411fff4f6760631498bb389ea"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# Problem with shortizing subdirectories side-by-side :(
TOWERASSAULT="Tower Assault"
mv "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Alien Breed Pack/Alien Breed Tower Assault" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Alien Breed Pack/$TOWERASSAULT"

cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
sdl_fulldouble=true
dosbox_machine=vesa_oldvbe
cpu_core=auto
cpu_cputype=486_slow
cpu_cycles=5000
sblaster_type=sb16
sblaster_base=220
sblaster_irq=7
sblaster_dma=1
sblaster_hdma=5
sblaster_mixer=true
sblaster_oplmode=auto
sblaster_oplrate=22050
ipx_enable=1
ipx_connection=1
ipx_ipx=true
_EOFCFG_

POL_Shortcut "ALIEN.EXE" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" "" "Game;ArcadeGame;"
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Alien Breed Pack/Alien Breed/manual.pdf"
# C:\Program Files\GOG.com\Alien Breed Pack\Alien Breed\keybindings.txt

POL_Shortcut "TA.EXE" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" "" "Game;ArcadeGame;"
POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Alien Breed Pack/$TOWERASSAULT/manual.pdf"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME1"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Alien Breed Pack/Alien Breed/" || exit 1

TITLE="$TITLE"

POL_Debug_Init
POL_Wine CONFIG.EXE
POL_SetupWindow_Close
exit 0
_EOF_

exit 0
