#!/bin/bash
# Date : (2013-03-21 21-40)
# Last revision : (2013-03-23 09-54)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="a_new_beginning"
PREFIX="ANewBeginning_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - A New Beginning: Final Cut"
SHORTCUT_NAME="A New Beginning"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1632
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Daedalic Entertainment" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "f03d80877a015ddbc77cb1c237208d8d" "f1da21026277da854081c2950b6488ae" "a0483e61ed0df41914863e5a077cab62"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Only used by configuration tool
POL_Call POL_Install_dotnet40

# Doesn't hurt ;)
POL_Wine_rebootHi

POL_Shortcut "ANB.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/A New Beginning/Manual.pdf"

# Fix missing sound issue in cutscenes.
# See: http://wiki.winehq.org/Sound ("SDL applications").
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'unset SDL_AUDIODIVER'

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/GOG Games/A New Beginning/" || exit 1
TITLE="$TITLE"

POL_Debug_Init
POL_Wine VisionaireConfigurationTool.exe
exit 0
_EOF_

exit 0
