#!/bin/bash
# Date : (2012-05-17 16-12)
# Last revision : (2013-04-23 22-05)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="another_world_15th_anniversary_edition"
PREFIX="AnotherWorld_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Another World: 15th Anniversary Edition"
SHORTCUT_NAME="Another World"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1230
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Eric Chahi / Digital Lounge" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

# Game no longer available for download, replaced by 20th anniversary version
if [ "$POL_SELECTED_FILE" ]; then
	POL_Debug_Message "Using selected file"
	POL_GoG_location="$POL_SELECTED_FILE"
else
	cd "$HOME"
	POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "" "Windows Executables (*.exe)|*.exe;*.EXE"
	POL_GoG_location="$APP_ANSWER"
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

POL_Wine_DirectInput "MouseWarpOverride" "disable"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Another World.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
case "$POL_LANG" in
  uk|sp|fr|it|de)
        MANUAL="Manual_${POL_LANG}.pdf"
        ;;
    *)
        MANUAL="Manual_uk.pdf"
        ;;
esac

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Another World/$MANUAL"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Another World/" || exit 1

TITLE="$TITLE"

POL_Debug_Init

POL_Wine Config.exe

exit 0
_EOF_

exit 0
