#!/bin/bash
# Date : (2012-07-02 19-30)
# Last revision : (2013-02-07 11-49)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="arcanum_of_steamworks_and_magick_obscura"
PREFIX="Arcanum_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Arcanum"
SHORTCUT_NAME="Arcanum"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1298
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Troika Games / Activision" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "e76e2915bdac8fb1cf7d0634a83803a5"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Arcanum.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "-No3d -doublebuffer" # -fullscreen
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Arcanum/Manual.pdf"
# C:\GOG Games\Arcanum\readme.txt

POL_SetupWindow_Close

exit
