#!/bin/bash
# Date : (2012-01-09 22-00)
# Last revision : (2012-09-23 18-31)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_arma_cold_war_assault.exe 444364681 "299f5cb319d023b502937a10fc21fc83"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="arma_cold_war_assault"
PREFIX="ColdWarAssault_gog"
WORKING_WINE_VERSION="1.3.36"

TITLE="Arma: Cold War Assault (GoG release)"
SHORTCUT_NAME="Arma: Cold War Assault"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1040
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bohemia Interactive Studio" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "299f5cb319d023b502937a10fc21fc83"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "ColdWarAssault.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Arma Cold War Assault/manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Arma Cold War Assault/readme.txt

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Arma Cold War Assault/" || exit 1

POL_Wine ColdWarAssaultPreferences.exe

exit
_EOF_

exit
