#!/bin/bash
# Date : (2012-06-13 19-32)
# Last revision : (2013-04-21 20-31)
# Wine version used : 1.5.0
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Problem with Wine 1.5.1+
# http://bugs.winehq.org/show_bug.cgi?id=30328

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="arx_fatalis"
PREFIX="ArxFatalis_gog"
WORKING_WINE_VERSION="1.5.0"

TITLE="GOG.com - Arx Fatalis"
SHORTCUT_NAME="Arx Fatalis"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1256
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Arkane Studios" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "0dd8ec13c10146db1a741258b624040a"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

POL_Wine_DirectInput "MouseWarpOverride" "force"

# Disable forcegdi, remove keyboard settings to revert to defaults
cat <<'_EOFCFG_' | perl -pe 's/\n/\r\n/' > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Arx Fatalis/cfg_default.ini"
[VIDEO]
resolution=800x600
full_screen=1
bump=1
_EOFCFG_

cat <<_EOFFUNC_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Arx Fatalis/arx_funcs"

read_arx_settings () {
  [ -z "\$WINEPREFIX" ] && POL_Debug_Fatal 'read_arx_settings: \$WINEPREFIX must be set'
  perl -ne 'print "RESOLUTION=\$1\n" if /^resolution=(\d+x\d+)/' "\$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Arx Fatalis/cfg_default.ini"
}

write_arx_settings () {
  [ -z "\$WINEPREFIX" ] && POL_Debug_Fatal 'read_arx_settings: \$WINEPREFIX must be set'
  perl -i.bak -pe 's/^resolution=\d+x\d+/resolution='"\$RESOLUTION"'/' "\$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Arx Fatalis/cfg_default.ini"
}

_EOFFUNC_

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "ARX.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Arx Fatalis/manual.pdf"
# C:\Program Files\GOG.com\Arx Fatalis\readme.txt
# C:\Program Files\GOG.com\Arx Fatalis\map.pdf

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Arx Fatalis/" || exit 1

TITLE="$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

source arx_funcs
eval \$(read_arx_settings)

# drop 320x200, 400x300 and 512x384
POL_SetupWindow_menu_list "\$(eval_gettext 'Select game resolution:')" "\$TITLE" "640x480~800x600~1024x768~1152x864~1280x1024" "~" "\$RESOLUTION"
[ "\$APP_ANSWER" != "\$RESOLUTION" ] && RESOLUTION="\$APP_ANSWER" write_arx_settings

POL_SetupWindow_Close
exit 0
_EOF_

exit 0
