#!/bin/bash
# Date : (2012-09-08 18-30)
# Last revision : (2012-10-29 01-49)
# Wine version used : 1.5.12
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="back_to_the_future_the_game"
PREFIX="BackToTheFutureTG_gog"
WORKING_WINE_VERSION="1.5.12"

TITLE="GOG.com - Back To The Future The Game"
SHORTCUT_NAME1="Back To The Future E1: It's About Time!"
SHORTCUT_NAME2="Back To The Future E2: Get Tannen!"
SHORTCUT_NAME3="Back To The Future E3: Citizen Brown"
SHORTCUT_NAME4="Back To The Future E4: Double Visions"
SHORTCUT_NAME5="Back To The Future E5: OUTATIME"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1392
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Telltale Games" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "71def52be8380f71f38407d1e27f811f"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_Install_d3dx9_36

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "BackToTheFuture101.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME1"
POL_Shortcut "BackToTheFuture102.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME2"
POL_Shortcut "BackToTheFuture103.exe" "$SHORTCUT_NAME3" "$SHORTCUT_NAME3.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME3"
POL_Shortcut "BackToTheFuture104.exe" "$SHORTCUT_NAME4" "$SHORTCUT_NAME4.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME4"
POL_Shortcut "BackToTheFuture105.exe" "$SHORTCUT_NAME5" "$SHORTCUT_NAME5.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME5"

POL_SetupWindow_Close

exit
