#!/bin/bash
# Date : (2012-05-12 14-11)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="baldurs_gate_2_complete"
PREFIX="BaldursGate2_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Baldur's Gate II Complete"
SHORTCUT_NAME="Baldur's Gate II"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/BG2/top.jpg" "http://files.playonlinux.com/resources/setups/BG2/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1182
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bioware / Hasbro Inc." "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "7129c3caa365931bd2a18552f16c806a" "d174cf1c13625ecda8a4024a2ef023e3" "c199d5f671a4585ece29bc3cb5018e34"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "BGMain.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Baldur's Gate 2/manual.pdf"
# C:\GOG Games\Baldur's Gate 2\Readme.txt
# C:\GOG Games\Baldur's Gate 2\Readme_addon.txt

#POL_Shortcut "CharView.exe" "$SHORTCUT_NAME - Character Viewer" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/GOG Games/Baldur's Gate 2/" || exit 1

TITLE="$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_Wine BGConfig.exe
POL_Call POL_Configurator_runparts

POL_SetupWindow_Close
exit 0
_EOF_

exit 0
