#!/bin/bash
# Date : (2012-05-10 17-58)
# Last revision : (2013-07-10 13-27)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="baldurs_gate_the_original_saga"
PREFIX="BaldursGate1_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Baldur's Gate: The Original Saga"
SHORTCUT_NAME="Baldur's Gate"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/BG1/top.jpg" "http://files.playonlinux.com/resources/setups/BG1/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1179
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bioware / Hasbro Inc." "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "4a2ed1b8c06525b8940eb068ad9a890c"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

POL_Wine_X11Drv "GrabFullScreen" "Y"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Baldur.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Baldur's Gate/MANUAL.PDF"
# C:\GOG Games\Baldur's Gate\Readme.txt
# C:\GOG Games\Baldur's Gate\MAP.pdf
# C:\GOG Games\Baldur's Gate\MANUAL_addon.PDF
# C:\GOG Games\Baldur's Gate\Readme_totsc.txt

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/GOG Games/Baldur's Gate/" || exit 1

TITLE="$TITLE"

POL_SetupWindow_Init

POL_Wine Config.exe
POL_Call POL_Configurator_runparts

POL_SetupWindow_Close
exit 0
_EOF_

exit 0
