#!/bin/bash
# Date : (2012-06-30 13-10)
# Last revision : (2013-03-24 15-47)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="blackwell_bundle"
PREFIX="BlackwellBundle_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Blackwell Bundle"
SHORTCUT_NAME1="Blackwell 1: The Blackwell Legacy"
SHORTCUT_NAME2="Blackwell 2: Blackwell Unbound"
SHORTCUT_NAME3="Blackwell 3: Blackwell Convergence"
SHORTCUT_NAME4="Blackwell 4: Blackwell Deception"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left2.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1288
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Wadjet Eye Games" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "ef717235021813125b4e1230ec35487f"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "blackwell1.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" "" "Game"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME1"
POL_Shortcut "Unbound.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" "" "Game"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME2"
POL_Shortcut "Convergence.exe" "$SHORTCUT_NAME3" "$SHORTCUT_NAME3.png" "" "Game"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME3"
POL_Shortcut "Deception.exe" "$SHORTCUT_NAME4" "$SHORTCUT_NAME4.png" "" "Game"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME4"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME1"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/GOG Games/Blackwell Bundle/Episode 1 - The Blackwell Legacy/" || exit 1
TITLE="$TITLE"

POL_Debug_Init
POL_Wine winsetup.exe
exit 0
_EOF_

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME2"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/GOG Games/Blackwell Bundle/Episode 2 - Blackwell Unbound/" || exit 1
TITLE="$TITLE"

POL_Debug_Init
POL_Wine winsetup.exe
exit 0
_EOF_

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME3"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/GOG Games/Blackwell Bundle/Episode 3 - Blackwell Convergence/" || exit 1
TITLE="$TITLE"

POL_Debug_Init
POL_Wine winsetup.exe
exit 0
_EOF_

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME4"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/GOG Games/Blackwell Bundle/Episode 4 - Blackwell Deception/" || exit 1
TITLE="$TITLE"

POL_Debug_Init
POL_Wine winsetup.exe
exit 0
_EOF_

exit 0
