#!/bin/bash
# Date : (2013-08-15 14-11)
# Last revision : (2013-08-18 03-37)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="blade_of_darkness"
PREFIX="BladeOfDarkness_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Blade of Darkness"
SHORTCUT_NAME="Blade of Darkness"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
#POL_SetupWindow_SetID ScriptIDNumber
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Studio / Publisher" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "7faa6812f14e6c3f8ceb63244f322fdb"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

#POL_Wine_OverrideDLL "" winegstreamer
POL_Call POL_Install_devenum
POL_Call POL_Install_quartz
#POL_Call POL_Install_amstream
POL_Call POL_Install_wmp9
#POL_Call POL_Install_ffdshow

cat << _EOFREG_ >> "$POL_USER_ROOT/tmp/ffdshow.reg"
[HKEY_CURRENT_USER\Software\GNU\ffdshow]
"mpg1"=dword:00000001
"mpg2"=dword:00000001

[HKEY_CURRENT_USER\Software\GNU\ffdshow_audio]
"trayIcon"=dword:00000000
_EOFREG_
POL_Wine regedit "$POL_USER_ROOT/tmp/ffdshow.reg"
rm "$POL_USER_ROOT/tmp/ffdshow.reg"

# cd "$GOGROOT/Blade of Darkness/Data/video/EnglishUS"
# mkdir -p Mpeg
# mv main.mpg Mpeg
# ffmpeg -i Mpeg/main.mpg -c:v mpeg4 -b:v 2000k main.mpg

POL_Wine_Direct3D "DirectDrawRenderer" "gdi"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Blade.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/Blade of Darkness/Blade of Darkness - Manual.pdf"
# C:\GOG Games\Blade of Darkness\Docs\Readme.txt

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

cd "$GOGROOT/Blade of Darkness/Bin/" || exit 1
TITLE="$TITLE"

POL_Wine nglide_config.exe
exit 0
_EOF_

exit 0
