#!/bin/bash
# Date : (2012-01-29 18-29)
# Last revision : (2012-04-11 23-50)
# Wine version used : 1.4-rc2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="broken_sword_2__the_smoking_mirror"
PREFIX="BrokenSword2DC_gog"
WORKING_WINE_VERSION="1.4-rc2"

TITLE="Broken Sword II: The Smoking Mirror (DC) (GoG release)"
SHORTCUT_NAME="Broken Sword 2: The Smoking Mirror"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Revolution Software" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_setup "$GOGID" "4cfe3858334e36c85cb6954362afc4a5"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "128"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "BrokenSword2.exe" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Broken Sword II - The Smoking Mirror Directors Cut/manual.pdf"
# C:\Program Files\GOG.com\Broken Sword II - The Smoking Mirror Directors Cut\Readme.txt

POL_SetupWindow_Close

exit
