#!/bin/bash
# Date : (2012-01-29 17-31)
# Last revision : (2012-04-07 20-47)
# Wine version used : 1.4-rc2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
#    author of original script Ulukyn
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_broken_sword_directors_cut.exe 1217398155 "27b2f01bfd65ea1a20054c73aee8d4db"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="BrokenSword1DC_gog"
WORKING_WINE_VERSION="1.4-rc2"
INSTALLBIN="setup_broken_sword_directors_cut.exe"

TITLE="Broken Sword: Shadow of the Templars (DC) (GoG release)"
URL="http://www.gog.com/en/gamecard/broken_sword_directors_cut"
SHORTCUT_NAME="Broken Sword 1: Shadow of the Templars"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/min.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Revolution Software" "$URL" "Pierre Etchemaite" "$PREFIX"

if [ -z "$POL_SELECTED_FILE" ]; then
    POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
    [ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

if [ -n "$POL_SELECTED_FILE" ]; then
    ARCHIVE="$POL_SELECTED_FILE"
else
    cd $HOME
    POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" ""
    ARCHIVE="$APP_ANSWER"
fi

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "bs1dc.exe" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Broken Sword - Director's Cut/manual.pdf"

POL_SetupWindow_Close

exit
