#!/bin/bash
# Date : (2012-02-03 21-27)
# Last revision : (2012-04-19 00-44)
# Wine version used : 1.4-rc2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="broken_sword_3__the_sleeping_dragon"
PREFIX="BrokenSword3_gog"
WORKING_WINE_VERSION="1.4-rc2"

TITLE="Broken Sword III: The Sleeping Dragon (GoG release)"
SHORTCUT_NAME="Broken Sword3: The Sleeping Dragon"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Revolution Software" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "09b2c88aab14000ae56461d84bef3407"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

# http://www.gog.com/en/forum/broken_sword_the_smoking_mirror/broken_sword_the_sleeping_dragon_freezes_on_startup
#cat <<'_EOFINI_' > "$POL_USER_ROOT/tmp/refresh60hz.reg"
#REGEDIT4
#
#[HKEY_LOCAL_MACHINE\Software\Microsoft\DirectDraw]
#"ForceRefreshRate"=dword:0000003c
#_EOFINI_
#POL_Wine regedit "$POL_USER_ROOT/tmp/refresh60hz.reg"
#rm "$POL_USER_ROOT/tmp/refresh60hz.reg"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "BSTSD.exe" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Broken Sword - The Sleeping Dragon/Readme.html"

POL_SetupWindow_Close

exit
