#!/bin/bash
# Date : (2012-01-29 17-31)
# Last revision : (2012-09-23 18-35)
# Wine version used : 1.4-rc2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
#    author of original script Ulukyn
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="broken_sword_directors_cut"
PREFIX="BrokenSword1DC_gog"
WORKING_WINE_VERSION="1.4-rc2"

TITLE="Broken Sword: Shadow of the Templars (DC) (GoG release)"
SHORTCUT_NAME="Broken Sword 1: Shadow of the Templars"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/min.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 970
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Revolution Software" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "27b2f01bfd65ea1a20054c73aee8d4db"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "bs1dc.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Broken Sword - Director's Cut/manual.pdf"

POL_SetupWindow_Close

exit
