#!/bin/bash
# Date : (2013-09-07)
# Last Revision : (2013-09-08 00:01)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable repositories)
# Author : VisitntX visitntx@gmail.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :
 
[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
GOGID="the_chaos_engine"
PREFIX="ChaosEngineRemastered_gog"
WORKING_WINE_VERSION="1.4.1"
 
TITLE="GOG.com - The Chaos Engine Remastered"
SHORTCUT_NAME="The Chaos Engine Remastered"
 
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
 
POL_SetupWindow_Init
POL_Debug_Init
 
POL_SetupWindow_presentation "$TITLE" "Abstraction Games and The Bitmap Brothers / Mastertronic" "http://www.gog.com/en/gamecard/$GOGID" "VisitntX" "$PREFIX"
 
POL_Call POL_GoG_setup "$GOGID" "6fa6da89af9d2a458e1a4589d948b1f1"
 
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
 
POL_Call POL_GoG_install
 
# Setting Windows Version 
Set_OS winxp
 
# Cleaning Wine by rebooting 
POL_Wine_reboot
 
POL_Shortcut "The Chaos Engine - Remastered.exe" "$SHORTCUT_NAME" "" "" "Game;ActionGame;" # "$SHORTCUT_NAME.png"
 
POL_SetupWindow_Close
 
exit