#!/bin/bash
# Date : (2012-07-19 20-00)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.5.9-raw3
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_chronicles_of_riddick_assault_on_dark_athena"
PREFIX="ChroniclesOfRiddickAODA_gog"
WORKING_WINE_VERSION="1.5.9-raw3"

TITLE="GOG.com - Chronicles of Riddick: Assault on Dark Athena"
SHORTCUT_NAME="The Chronicles of Riddick: Assault on Dark Athena"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1323
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Starbreeze Studios & Tigon Studios / Atari" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "2aa011a2f73cbcc1427a62173be7cb60" "f25f5e5b36d019c995a080c5cb6435ac" "bdd4b203fde34f68418fa7ef9e8ef8a0" "7db0c50a23083fcebea63b7c470ef035" "ed06a88a199493a02c3e46b87516b34a"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Default interface leaks winprocs and crashes under Wine
POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Pixel aspect: auto => normal
# (auto picks wrong aspect for me, but maybe it's just me)
sed -i.bak -e 's/^VID_PIXELASPECT=-1\.000000/VID_PIXELASPECT=1.000000/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Chronicles of Riddick - Assault on Dark Athena/Environment.cfg"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "DarkAthena.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"

MANUAL="RIDDICK_PC_MANUAL_GB.pdf"
[ "$POL_LANG" = "fr" ] && MANUAL="RIDDICK_PC_MANUAL_FR.pdf"
[ "$POL_LANG" = "es" ] && MANUAL="RIDDICK_PC_MANUAL_ES.pdf"
[ "$POL_LANG" = "de" ] && MANUAL="RIDDICK_PC_MANUAL_DE.pdf"
[ "$POL_LANG" = "it" ] && MANUAL="RIDDICK_PC_MANUAL_IT.pdf"

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/The Chronicles of Riddick - Assault on Dark Athena/$MANUAL"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/GOG Games/The Chronicles of Riddick - Assault on Dark Athena/" || exit 1
TITLE="$TITLE"
POL_Debug_Init
POL_Wine DarkAthena_Launcher.exe
exit 0
_EOF_

exit 0
