#!/bin/bash
# Date : (2012-07-19 20-00)
# Last revision : (2012-09-23 18-36)
# Wine version used : 1.5.0-raw3
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_chronicles_of_riddick_assault_on_dark_athena"
PREFIX="ChroniclesOfRiddickAODA_gog"
WORKING_WINE_VERSION="1.5.0-raw3"

TITLE="The Chronicles of Riddick - Assault on Dark Athena (GoG release)"
SHORTCUT_NAME="The Chronicles of Riddick: Assault on Dark Athena"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1323
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Starbreeze Studios & Tigon Studios / Atari" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "6454dee0072163f6a48f8c8036f729a5" "f3af5eb04e6c0ba0975933dc9df9a156" "228beec336145e4e03910b8bb510386a" "a5573b82e24d9ff79f11645d63d2bdb3" "abc9e0cd2e11acea7c55f5ce487bb43f"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Pixel aspect: auto => normal
# (auto picks wrong aspect for me, but maybe it's just me)
sed -i.bak -e 's/^VID_PIXELASPECT=-1\.000000/VID_PIXELASPECT=1.000000/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Chronicles of Riddick - Assault on Dark Athena/Environment.cfg"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "DarkAthena.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""

MANUAL="RIDDICK_PC_MANUAL_GB.pdf"
[ "$POL_LANG" = "fr" ] && MANUAL="RIDDICK_PC_MANUAL_FR.pdf"
[ "$POL_LANG" = "es" ] && MANUAL="RIDDICK_PC_MANUAL_ES.pdf"
[ "$POL_LANG" = "de" ] && MANUAL="RIDDICK_PC_MANUAL_DE.pdf"
[ "$POL_LANG" = "it" ] && MANUAL="RIDDICK_PC_MANUAL_IT.pdf"

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Chronicles of Riddick - Assault on Dark Athena/$MANUAL"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/The Chronicles of Riddick - Assault on Dark Athena/" || exit 1
TITLE="$TITLE"
POL_Debug_Init
POL_Wine DarkAthena_Launcher.exe
exit
_EOF_

exit
