#!/bin/bash
# Date : (2013-02-25 21-49)
# Last revision : (2013-03-24 15-47)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="commandos_ammo_pack"
PREFIX="CommandosAP_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Commandos Ammo Pack"
SHORTCUT_NAME1="Commandos: Behind Enemy Lines"
SHORTCUT_NAME2="Commandos: Beyond The Call Of Duty"
SHORTCUT_NAMEDS="Commandos: Dedicated Server"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1594
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Pyro Studios / Digital Game Factory" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

which ffmpeg || POL_Debug_Fatal "$(eval_gettext 'This install script requires ffmpeg')"

POL_Call POL_GoG_setup "$GOGID" "25d859e83b0b7e6115da5e36eb469dd7"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_Call POL_Install_devenum
POL_Call POL_Install_quartz
POL_Call POL_Install_amstream
POL_Call POL_Install_wmp9
POL_Call POL_Install_ffdshow

# Hide ffdshow systray icon
cat << _EOFREG_ >> "$POL_USER_ROOT/tmp/hideffdshow.reg"
[HKEY_CURRENT_USER\Software\GNU\ffdshow_audio]
"trayIcon"=dword:00000000
_EOFREG_
POL_Wine regedit "$POL_USER_ROOT/tmp/hideffdshow.reg"
rm "$POL_USER_ROOT/tmp/hideffdshow.reg"

convert_videos () {
    local DIR="$1"
    shift

    cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Commandos Ammo Pack/$DIR" || POL_Debug_Fatal "Could not find game directory"
    [ -d Cinepak ] || mkdir Cinepak
    mv *.avi Cinepak/

    for i in "$@"; do
        POL_SetupWindow_set_text "$i"
        ffmpeg -i "Cinepak/$i" -c:v wmv2 -b:v 2000k "$i"
        let FILES++
        POL_SetupWindow_pulse $((100 * FILES / TOTAL))
    done
}

POL_SetupWindow_pulsebar "$(eval_gettext 'Converting videos...')" "$TITLE"
FILES=0
TOTAL=18

convert_videos VIDEO/  H_Afri.avi H_Intro.avi H_Norm.avi H_Noru.avi H_Rhin.avi H_Vict.avi Tut_1.avi Tut_2.avi Tut_3.avi Tut_4.avi Tut_5.avi Tut_6.avi Tut_7.avi
convert_videos coman_mp/VIDEO/ 1_v.avi 2_v.avi 3_v.avi 4_v.avi h_intro.avi

# "3D DirectX7"?
POL_SetupWindow_VMS "4"

# Mouse to borders to scroll around
POL_Wine_X11Drv "GrabFullScreen" "Y"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "comandos.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Commandos Ammo Pack/Manual.pdf"

POL_Shortcut "coman_mp.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME1.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Commandos Ammo Pack/coman_mp/Manual.pdf"

# C:\Program Files\GOG.com\Commandos Ammo Pack\coman_mp\mpserver.exe

POL_SetupWindow_Close

exit 0
