#!/bin/bash
# Date : (2012-06-16 17-38)
# Last revision : (2013-03-31 16-25)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="commandos_2_3"
PREFIX="Commandos_2_3_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Commandos 2 and 3"
SHORTCUT_NAME1="Commandos 2: Men of Courage"
SHORTCUT_NAME2="Commandos 3: Destination Berlin"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1258
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Pyro Studios / Digital Game Factory" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "9499377e9b329067218f8164ab5b455e" "cfd007eb9a27eea5aad3dbb72909aea9" "360d4b8dcc7b08874d7e92dc6596a496"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "comm2.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" "" "Game;StrategyGame;"
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Commandos 2 and 3/Commandos 2 - Men of Courage/Manual.PDF"
# C:\Program Files\GOG.com\Commandos 2 and 3\Commandos 2 - Men of Courage\Readme.rtf

POL_Shortcut "Commandos3.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" "" "Game;StrategyGame;"
POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Commandos 2 and 3/Commandos 3 - Destination Berlin/manual.pdf"
# C:\Program Files\GOG.com\Commandos 2 and 3\Commandos 3 - Destination Berlin\Readme.rtf

POL_SetupWindow_Close

exit 0
