#!/bin/bash
# Date : (2013-09-06)
# Last Revision : (2013-09-07 08:59)
# Wine version used : 1.4.1
# Distribution used to test : Debian Jessie (Testing repositories)
# Author : VisitntX visitntx@gmail.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :
 
[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
GOGID="daikatana"
PREFIX="Daikatana_gog"
WORKING_WINE_VERSION="1.4.1"
 
TITLE="GOG.com - Daikatana"
SHORTCUT_NAME="Daikatana"
 
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
 
POL_SetupWindow_Init
POL_SetupWindow_SetID 1817
POL_Debug_Init
 
POL_SetupWindow_presentation "$TITLE" "Ion Storm Inc. / Square Enix" "http://www.gog.com/en/gamecard/$GOGID" "VisitntX" "$PREFIX"
 
POL_Call POL_GoG_setup "$GOGID" "af495c91f8e334cee3c7e853e1a29d13"
 
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
 
POL_Call POL_GoG_install
 
# Setting the Windows Version
Set_OS winxp
 
# Cleaning Wine by rebooting
POL_Wine_reboot
 
POL_Shortcut "daikatana.exe" "$SHORTCUT_NAME" "" "" "Game;Action;" # "$SHORTCUT_NAME.png"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/Daikatana/Daikatana_-_Manual_-_PC.pdf"
 
POL_SetupWindow_Close
 
exit
