#!/bin/bash
# Date : (2013-01-26 12-16)
# Last revision : (2013-01-26 20-05)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="dark_reign_expansion"
PREFIX="DarkReign_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Dark Reign and Expansion"
SHORTCUT_NAME1="Dark Reign - The Future of War"
SHORTCUT_NAME2="Dark Reign - The Rise of the Shadowhand"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1553
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Auran / Activision" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "3774c5347b189351164783c29813e095"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

# Yeah
POL_SetupWindow_VMS "1"

# "Please GOG, Wine's explorer.exe is a troublefree as XP Home's, don't kill it"
POL_Wine_UpdateRegistryPair 'HKEY_LOCAL_MACHINE\Software\GOG.com\GOGDARKREIGN' 'WINDOWSXPHOME' 'True'

# Scroll devilishly fast for me otherwise
cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Dark Reign/" || POL_Debug_Fatal "Could not find game directory"
cp TACTICS.CFG TACTICS.CFG.orig
sed -e 's/^ScrollSpeed=[0-9]\+/ScrollSpeed=5/' TACTICS.CFG.orig > TACTICS.CFG
# If you think I should also drop GameSpeed, or any other tweak, just tell me

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Dark Reign - Original Game.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Dark Reign/Manual.pdf"
# C:\Program Files\GOG.com\Dark Reign\readme.txt
# C:\Program Files\GOG.com\Dark Reign\Customer_support.htm

POL_Shortcut "Dark Reign - Expansion.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""

POL_SetupWindow_Close

exit
