#!/bin/bash
# Date : (2012-11-18 16-24)
# Last revision : (2013-05-19 13-56)
# Wine version used : 1.4.1
# Distribution used to test : Ubuntu 12.10 64-bit
# Author : Kweepeer (Based on Broken Sword DC script by Pierre Etchemaite)
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Known issues:
# - The game freezes sometimes during gameplay. After a few seconds, the game continues.

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="deponia"
PREFIX="Deponia_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Deponia"
SHORTCUT_NAME="Deponia"

POL_GetSetupImages "" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1467
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Daedalic Entertainment" "http://www.gog.com/gamecard/$GOGID" "Kweepeer" "$PREFIX"
POL_Call POL_GoG_setup "$GOGID" \
  "a77f5db9ce214b5435a5dbca9a574464" \
  "88573504e0cab842cb63a57e52423cf1" \
  "332343a8c3016cec9b0535b3498bee49"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Deponia.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;AdventureGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Deponia/Manual.pdf"

# Fix missing sound issue in cutscenes.
# See: http://wiki.winehq.org/Sound ("SDL applications").
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'unset SDL_AUDIODIVER'

# Fix savegame issue.
# http://bugs.winehq.org/show_bug.cgi?id=31251
mkdir "$WINEPREFIX/drive_c/tmp"

POL_SetupWindow_Close

# Note on configurator:
# VisionaireConfigurationTool.exe doesn't seem to work in GOG version of the game.
# You can set advanced options by editing $WINEPREFIX/drive_c/GOG Games/Deponia/config.ini.
