#!/bin/bash
# Date : (2012-05-14 00-51)
# Last revision : (2012-10-29 02-01)
# Wine version used : 1.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="deus_ex"
PREFIX="DeusEx_gog"
WORKING_WINE_VERSION="1.4"

TITLE="GOG.com - Deus Ex GOTY Edition"
SHORTCUT_NAME="Deus Ex"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1190
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ion Storm Inc. / Square Enix" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "8c6cfa5089c41ca80545e27b99aa3730"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cd "$POL_USER_ROOT/tmp"
# Direct3D driver update
POL_Download "http://files.playonlinux.com/D3DDrv.dll" "8211caf827881d3969e1812fc6341146"
cp D3DDrv.dll "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Deus Ex/System/D3DDrv.dll"

# Default OpenGL renderer crashes on exit, pick a better one
# Source http://www.cwdohnal.com/utglr/
POL_Download "http://files.playonlinux.com/dxglr21.zip" "e25ec9940eff8aa1e3a74e94ffdba706"
POL_System_ExtractSingleFile "dxglr21.zip" "OpenGLDrv.dll" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Deus Ex/System/OpenGlDrv.dll"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "DeusEx.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Deus Ex/manual.pdf"
# Game has issues with uncapped FPS (dialogs cut before the end...) => enable vblank
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "export __GL_SYNC_TO_VBLANK=1" # nvidia?
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "export vblank_mode=1"         # others?
# C:\Program Files\GOG\Deus Ex\Help\ReadMe.htm
# C:\Program Files\GOG\Deus Ex\Help\MPAdmin.htm
# C:\Program Files\GOG\Deus Ex\Help\ReadMeMultiplayer.htm
# C:\Program Files\GOG\Deus Ex\Help\MPMap.htm
# C:\Program Files\GOG\Deus Ex\Help\ReadMeMPStrategy.htm
# C:\Program Files\GOG\Deus Ex\Help\ReadMePatch1.htm
# C:\Program Files\GOG\Deus Ex\Help\PatchFix.htm

# OpenGL tip
POL_SetupWindow_message "$(eval_gettext 'On first run the game will autodetect available renderers.\nIt is likely that you will get better performance out of the OpenGL renderer;\nYou can select it after clicking on "Show all devices".')" "$TITLE"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Deus Ex/" || exit 1

TITLE="$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_question "$(eval_gettext 'Run $TITLE in safe mode?')" "\$TITLE"
[ "\$APP_ANSWER" = "TRUE" ] && POL_Wine System/DeusEx.exe -safe

POL_Call POL_Configurator_runparts

POL_SetupWindow_Close
exit
_EOF_

exit
