#!/bin/bash
# Date : (2012-05-14 00-51)
# Last revision : (2012-05-14 12-53)
# Wine version used : 1.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="deus_ex"
PREFIX="DeusEx_gog"
WORKING_WINE_VERSION="1.4"

TITLE="Deus Ex GOTY Edition (GoG release)"
SHORTCUT_NAME="Deus Ex"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ion Storm Inc. / Square Enix" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "8c6cfa5089c41ca80545e27b99aa3730"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

cd "$POL_USER_ROOT/tmp"
# Direct3D driver update
POL_Download "http://files.playonlinux.com/D3DDrv.dll" "8211caf827881d3969e1812fc6341146"
cp D3DDrv.dll "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Deus Ex/System/D3DDrv.dll"

# Default OpenGL renderer crashes on exit, pick a better one
# Source http://www.cwdohnal.com/utglr/
POL_Download "http://files.playonlinux.com/dxglr21.zip" "e25ec9940eff8aa1e3a74e94ffdba706"
POL_System_ExtractSingleFile "dxglr21.zip" "OpenGLDrv.dll" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Deus Ex/System/OpenGlDrv.dll"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "DeusEx.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Deus Ex/manual.pdf"
# Game has issues with uncapped FPS (dialogs cut before the end...) => enable vblank
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "export __GL_SYNC_TO_VBLANK=1" # nvidia?
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "export vblank_mode=1"         # others?
# C:\Program Files\GOG\Deus Ex\Help\ReadMe.htm
# C:\Program Files\GOG\Deus Ex\Help\MPAdmin.htm
# C:\Program Files\GOG\Deus Ex\Help\ReadMeMultiplayer.htm
# C:\Program Files\GOG\Deus Ex\Help\MPMap.htm
# C:\Program Files\GOG\Deus Ex\Help\ReadMeMPStrategy.htm
# C:\Program Files\GOG\Deus Ex\Help\ReadMePatch1.htm
# C:\Program Files\GOG\Deus Ex\Help\PatchFix.htm

POL_Shortcut "DeusEx.exe" "$SHORTCUT_NAME [safe mode]" "$SHORTCUT_NAME.png" "-safe"

POL_SetupWindow_Close

exit
