#!/bin/bash
# Date : (2011-12-23 23-13)
# Last revision : (2012-04-19 00-46)
# Wine version used : 1.3.35
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="divine_divinity"
PREFIX="DivineDivinity_gog"
WORKING_WINE_VERSION="1.3.35"

TITLE="Divine Divinity (GoG release)"
SHORTCUT_NAME="Divine Divinity"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Larian Studios" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "560aff548d3df0d619958b443017b111"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

# Default is Direct3D which creates display problems (trails)
# Switch to DirectDraw
cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Divine Divinity" || POL_Debug_Fatal "$(eval_gettext 'Could not find program directory!')"
cp slashed.cfg slashed.cfg.orig
perl -e 'print "\x02\x00\x00\x00"' > slashed.cfg

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "div.exe" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Divine Divinity/Manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Divine Divinity/ReadMe.txt

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Divine Divinity/" || exit 1

POL_Wine configtool.exe

exit
_EOF_

exit
