#!/bin/bash
# Date : (2012-03-18 22-56)
# Last revision : (2012-04-11 00-00)
# Wine version used : 1.5.0
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="dungeons_dragons_dragonshard"
PREFIX="Dragonshard_gog"
WORKING_WINE_VERSION="1.5.0"

TITLE="Dungeons&Dragons: Dragonshard (GoG release)"
SHORTCUT_NAME="Dungeons&Dragons: Dragonshard"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Liquid Entertainment / Atari" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_setup "$GOGID" "e5ca9cdb4edb72881b1c214f0f5fcd4f"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Dragonshard.exe" "$SHORTCUT_NAME"
# C:\Program Files\GOG.com\Dragonshard\DNDEditor.exe
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Dragonshard/manual.pdf"
# C:\Program Files\GOG.com\Dragonshard\Readme.txt

POL_SetupWindow_Close

exit
