#!/bin/bash
# Date : (2012-03-18 22-56)
# Last revision : (2012-03-25 18-46)
# Wine version used : 1.5.0
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_dungeons_and_dragons_dragonshard.exe 833610549 "e5ca9cdb4edb72881b1c214f0f5fcd4f"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="Dragonshard_gog"
WORKING_WINE_VERSION="1.5.0"
INSTALLBIN="setup_dungeons_and_dragons_dragonshard.exe"

TITLE="Dungeons&Dragons: Dragonshard (GoG release)"
URL="http://www.gog.com/en/gamecard/dungeons_dragons_dragonshard"
SHORTCUT_NAME="Dungeons&Dragons: Dragonshard"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Liquid Entertainment / Atari" "$URL" "Pierre Etchemaite" "$PREFIX"

if [ -z "$POL_SELECTED_FILE" ]; then
    POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
    [ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

if [ -n "$POL_SELECTED_FILE" ]; then
    ARCHIVE="$POL_SELECTED_FILE"
else
    cd $HOME
    POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "$INSTALLBIN"
    ARCHIVE="$APP_ANSWER"
fi

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Dragonshard.exe" "$SHORTCUT_NAME"
# C:\Program Files\GOG.com\Dragonshard\DNDEditor.exe
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Dragonshard/manual.pdf"
# C:\Program Files\GOG.com\Dragonshard\Readme.txt

POL_SetupWindow_Close

exit
