#!/bin/bash
# Date : (2012-08-06 19-20)
# Last revision : (2012-09-23 18-40)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="dreamfall_the_longest_journey"
PREFIX="Dreamfall_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="Dreamfall - The Longest Journey (GoG release)"
SHORTCUT_NAME="Dreamfall: The longest journey"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1348
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Funcom" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "1091dd106f114d2d20a91d76aa1655ed" "76b01bcf0928a586a20437b2d3bda7a5" "d8a0841f377d027e1a098b73f085250b" "85337cd0b34a273dcb073b7e8e1b203c"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "128"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "dreamfall.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Dreamfall/manual.pdf"

POL_SetupWindow_Close

exit
