#!/bin/bash
# Date : (2011-12-18 01-01)
# Last revision : (2012-04-19 00-35)
# Wine version used : 1.5.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="dungeon_keeper_2"
PREFIX="DungeonKeeper2_gog"
WORKING_WINE_VERSION="1.5.1"

TITLE="Dungeon Keeper II (GoG release)"
SHORTCUT_NAME="Dungeon Keeper II"
SHORTCUT_SAFE="$SHORTCUT_NAME - $(eval_gettext 'Safe mode')"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bullfrog Productions / Electronic Arts" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "44ddedeca494543b528ea022aa971a61"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "DKII.EXE" "$SHORTCUT_NAME"
POL_Shortcut "DKII_SOFT.EXE" "$SHORTCUT_SAFE"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOGcom/Dungeon Keeper 2/manual.pdf"
# C:/$PROGRAMFILES/GOGcom/Dungeon Keeper 2/reference_card.pdf
# C:/$PROGRAMFILES/GOGcom/Dungeon Keeper 2/ReadMe.txt

POL_SetupWindow_message "$(eval_gettext 'GOG release defaults to 800x600 software rendering to work around\nstability issues, specially under Windows XP/Seven.\nYou can re-enable hardware acceleration in the configurator.')" "$TITLE"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

cd "\$POL_USER_ROOT/tmp/" || exit 1

TITLE="$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

# Based on http://www.pcgamingbuzz.com/2011/how-to-fix-dungeon-keeper-2-from-gog/

POL_SetupWindow_menu "$(eval_gettext 'Rendering')" "\$TITLE" "$(eval_gettext 'Unchanged'
)~$(eval_gettext '800x600 software rendering (GOG defaults)')~$(eval_gettext 'Hardware 3D')" "~" "
$(eval_gettext 'Unchanged')"

case "\$APP_ANSWER" in
    "$(eval_gettext 'Unchanged')")
        ;;

    "$(eval_gettext '800x600 software rendering (GOG defaults)')")
        cat <<-'_INIEOF_' > "\$POL_USER_ROOT/tmp/software3d.reg"
	REGEDIT4
	
	[HKEY_CURRENT_USER\Software\Bullfrog Productions Ltd\Dungeon Keeper II\Configuration\Video]
	"Engine Id"=dword:00000004
	"EnvironmentMapping"=dword:00000000
	"Res 1024*768 Enabled"=dword:00000000
	"Res 1280*1024 Enable"=dword:00000000
	"Res 1600*1200 Enable"=dword:00000000
	"Screen Hardware3D"=dword:00000000
	"Screen Height"=dword:00000258
	"Screen Width"=dword:00000320
	"Translucent Water"=dword:00000000
	_INIEOF_
        POL_Wine regedit "\$POL_USER_ROOT/tmp/software3d.reg"
        rm "\$POL_USER_ROOT/tmp/software3d.reg"
        ;;

    "$(eval_gettext 'Hardware 3D')")
        cat <<-'_INIEOF_' > "\$POL_USER_ROOT/tmp/hardware3d.reg"
	REGEDIT4
	
	[HKEY_CURRENT_USER\Software\Bullfrog Productions Ltd\Dungeon Keeper II\Configuration\Video]
	"Engine Id"=dword:00000002
	"EnvironmentMapping"=dword:00000001
	"Res 1024*768 Enabled"=dword:00000001
	"Res 1280*1024 Enable"=dword:00000001
	"Res 1600*1200 Enable"=dword:00000001
	"Screen Hardware3D"=dword:00000001
	"Screen Height"=dword:00000500
	"Screen Width"=dword:00000400
	"Translucent Water"=dword:00000001
	_INIEOF_
        POL_Wine regedit "\$POL_USER_ROOT/tmp/hardware3d.reg"
        rm "\$POL_USER_ROOT/tmp/hardware3d.reg"
        POL_SetupWindow_message "$(eval_gettext 'You can now change the resolution inside game options.\nThe game can become unstable at high resolutions, so you may have\nto experiment a bit.')" "$TITLE"
        ;;
esac

POL_SetupWindow_Close
exit
_EOF_

exit
