#!/bin/bash
# Date : (2011-12-18 01-01)
# Last revision : (2012-01-02 21-27)
# Wine version used : 1.3.35
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archive:
# setup_dungeon_keeper_2.exe 436819889 "44ddedeca494543b528ea022aa971a61"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="DungeonKeeper2_gog"
WORKING_WINE_VERSION="1.3.35"

TITLE="$(eval_gettext 'Dungeon Keeper II (GoG release)')"
SHORTCUT_NAME="Dungeon Keeper II"
SHORTCUT_SAFE="$SHORTCUT_NAME - $(eval_gettext 'Safe mode')"
SHORTCUT_DOC="$SHORTCUT_NAME - $(eval_gettext 'User manual')"
SHORTCUT_REFCARD="$SHORTCUT_NAME - $(eval_gettext 'Reference Card')"
SHORTCUT_README="$SHORTCUT_NAME - $(eval_gettext 'Readme')"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bullfrog Productions / Electronic Arts" "http://www.gog.com/en/gamecard/dungeon_keeper_2" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "setup_dungeon_keeper_2.exe"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

POL_Call POL_Function_SetNativeExtension "pdf"
POL_Call POL_Function_SetNativeExtension "txt"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "DKII.EXE" "$SHORTCUT_NAME"
POL_Shortcut "DKII_SOFT.EXE" "$SHORTCUT_SAFE"
POL_Shortcut "start.exe" "$SHORTCUT_DOC" "" "'C:/$PROGRAMFILES/GOGcom/Dungeon Keeper 2/manual.pdf'"
POL_Shortcut "start.exe" "$SHORTCUT_REFCARD" "" "'C:/$PROGRAMFILES/GOGcom/Dungeon Keeper 2/reference_card.pdf'"
POL_Shortcut "start.exe" "$SHORTCUT_README" "" "'C:/$PROGRAMFILES/GOGcom/Dungeon Keeper 2/ReadMe.txt'"

POL_SetupWindow_Close

exit
