#!/bin/bash
# Date : (2013-05-22 22-00)
# Last revision : (2013-05-22 22-00)
# Wine version used : 1.4-dos_support_0.6
# Distribution used to test : Xubuntu 13.04
# Author : Pascal Reinhard dev@ovocean.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="dungeon_keeper"
PREFIX="DungeonKeeper_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.6"

TITLE="GOG.com - Dungeon Keeper"
SHORTCUT_NAME="Dungeon Keeper"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.png" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1712
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bullfrog Productions / Electronic Arts" "http://www.gog.com/gamecard/$GOGID" "Xodetaetl" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "e8f77a31da061460cd93bfb275270b45"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install

# The game expects itself at the root directory of C:
mv "$WINEPREFIX/drive_c/GOG Games/Dungeon Keeper" "$WINEPREFIX/drive_c/DKeeper"

# Dosbox config
cat <<_EOFCFG_ > "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
sdl_output=overlay
render_aspect=true
dosbox_memsize=30
mixer_prebuffer=100
_EOFCFG_

mv "$WINEPREFIX/drive_c/DKeeper/GAME.INST" "$WINEPREFIX/drive_c/DKeeper/game.cue"

cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/DungeonKeeper.bat"
@echo off
c:
cd DKeeper
imgmount d game.cue -t iso -fs iso
keeper.exe
exit
_EOFBAT_

POL_Shortcut "DungeonKeeper.bat" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;StrategyGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/DKeeper/manual.pdf"

POL_SetupWindow_Close

exit 0
