#!/bin/bash
# Date : (2013-05-22 22-00)
# Last revision : (2013-05-29 22-20)
# Wine version used : 1.4-dos_support_0.6
# Distribution used to test : Xubuntu 13.04
# Authors : Pascal Reinhard <dev@ovocean.com>, TonyFlow <tonyflow@rhcp.net>
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="dungeon_keeper"
PREFIX="DungeonKeeper_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.6"

TITLE="GOG.com - Dungeon Keeper"
SHORTCUT_NAME="Dungeon Keeper"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.png" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1712
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bullfrog Productions / Electronic Arts" "http://www.gog.com/gamecard/$GOGID" "Xodetaetl" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "e8f77a31da061460cd93bfb275270b45"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install

GOGPATH="$GOGROOT/Dungeon Keeper"
  
# Enable the high-resolution mode by default
if type -t POL_unbase64 > /dev/null; then
	POL_unbase64 <<-_EOF_ > "$GOGPATH/SAVE/SETTINGS.DAT"
	AAQDAAEBf1oBAAANAAAAyADQAMsAzQAdACoA0wDRAMcAzwAUACYAJgEZARQEFAEjABEAHwAUAiIAMAAjASIBMAEhAB4AKgBSAA4AGQAyAAEABg==
	_EOF_
	POL_SetupWindow_message "$(eval_gettext 'Tip: The high-resolution mode has been activated, if it is too slow, you can disable it by pressing Alt+R while in game.)')" "$TITLE"
else
	POL_SetupWindow_message "$(eval_gettext 'Tip: You can enable a higher-resolution mode by pressing Alt+R during the game.')" "$TITLE"
fi

# Dosbox config
cat <<_EOFCFG_ > "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
sdl_output=overlay
render_aspect=true
dosbox_memsize=30
mixer_prebuffer=100
cpu_cycles=130000
cpu_cycleup=5000
cpu_cycledown=5000
_EOFCFG_

# Batch launcher with image disk mount
cat <<_EOFBAT_ > "$GOGPATH/DK.bat"
@echo off
cd C:\GOGGAM~1\DUNGEO~1
imgmount D GAME~1.INS -t iso -fs iso
KEEPER.EXE
exit
_EOFBAT_

POL_Shortcut "DK.bat" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;StrategyGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGPATH/manual.pdf"

POL_SetupWindow_Close
exit 0
