#!/bin/bash
# Date : (2012-02-19 21:00)
# Last revision : (2013-01-07 15:12)
# Wine version used : 1.4
# Distribution used to test : Mint 12 x64
# Author : GNU_Raziel
# Licence : Retail
# Only For : http://www.playonlinux.com

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

TITLE="EA's origin"
PREFIX="Origin"
EDITOR="Electronic Arts"
GAME_URL="http://store.origin.com"
AUTHOR="GNU_Raziel"
WORKING_WINE_VERSION="1.4"
GAME_VMS="256"

# Starting the script
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/top.jpg" "http://files.playonlinux.com/resources/setups/left.jpg" "$TITLE"
POL_SetupWindow_Init

# Starting debugging API
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"

# Setting prefix path
POL_Wine_SelectPrefix "$PREFIX"

# Downloading wine if necessary and creating prefix
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Downloading latest Origin
cd "$POL_USER_ROOT/tmp/"
POL_SetupWindow_download "$(eval_gettext 'Downloading $TITLE, please wait...')" "$TITLE" "https://download.dm.origin.com/origin/live/OriginSetup.exe"

# Installing mandatory dependencies
POL_Wine_InstallFonts
POL_Function_FontsSmoothRGB
POL_Call POL_Install_wininet # Fix EA Connexion's issue 1
POL_Call POL_Install_vcrun2010

# Installing Origin
cd "$POL_USER_ROOT/tmp/"
POL_Wine "OriginSetup.exe"
POL_Wine_WaitExit "$TITLE"

# Asking about memory size of graphic card
POL_SetupWindow_VMS $GAME_VMS

# Set Graphic Card information keys for wine
POL_Wine_SetVideoDriver

## Fix for this software
# Fix EA connexion's issue 2
mkdir -p "$POL_USER_ROOT/wineprefix/$PREFIX/drive_c/system32/drivers/etc/"
touch "$POL_USER_ROOT/wineprefix/$PREFIX/drive_c/system32/drivers/etc/hosts"

# Sound problem fix - pulseaudio related
[ "$POL_OS" = "Linux" ] && Set_SoundDriver "alsa"
[ "$POL_OS" = "Linux" ] && Set_SoundEmulDriver "Y"
## End Fix

# Making shortcut
POL_Shortcut "Origin.exe" "$TITLE" "" ""

POL_SetupWindow_Close
exit 0