#!/bin/bash
# Date : (2012-01-02 23-22)
# Last revision : (2013-12-26 15-18)
# Wine version used : 1.3.36, 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="fallout"
PREFIX="Fallout_gog"
WORKING_WINE_VERSION="1.4.1"
[ "$POL_OS" = "Mac" ] && WORKING_WINE_VERSION="1.3.7"

TITLE="GOG.com - Fallout"
SHORTCUT_NAME="Fallout"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1032
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Black Isle Studios / Interplay" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "0fc0cd177c2084fc4b09bb82ed481478"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install /nogui


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "falloutw.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
# sometimes exits with an exitcode of 1 for what it seems no good reason
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Fallout/MANUAL.PDF"
# C:\GOG Games\Fallout\ReadMe.txt

POL_SetupWindow_Close

exit 0
