#!/bin/bash
# Date : (2012-04-22 14-16)
# Last revision : (2012-11-05 22-29)
# Wine version used : 1.5.16
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="fallout_tactics"
PREFIX="FalloutTactics_gog"
WORKING_WINE_VERSION="1.5.16"

TITLE="GOG.com - Fallout Tactics"
SHORTCUT_NAME="Fallout Tactics"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1139
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Micro Forté / Interplay" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "280a1f49f8ef375bdeccec83a559e51e" "3bd6d8f6b10403e0ad09fa849e29685b"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# The need for this is not totally proven
POL_Wine_Direct3D "DirectDrawRenderer" "gdi"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "BOS.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Fallout Tactics/MANUAL.PDF"
# C:\Program Files\GOG.com\Fallout Tactics\readme.txt

POL_SetupWindow_Close

exit
