#!/bin/bash
# Date : (2012-08-29 21-13)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.5.23
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="far_cry_2_fortunes_edition"
PREFIX="FarCry2_gog"
WORKING_WINE_VERSION="1.5.23"

TITLE="GOG.com - Far Cry 2"
SHORTCUT_NAME="Far Cry 2: Fortune's Edition"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1382
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ubisoft Montréal / Ubisoft" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "96f0cf6e0b8501099934d0ddd4555611" "74e68eac583c285dfe3de21401e66be5" "84fbc08e8a3910156e57cccdee6e0a52"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_Install_d3dx9_36

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "farcry2.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Far Cry 2 Fortune's Edition/manual.pdf"
# C:\GOG Games\Far Cry 2 Fortune's Edition\ReadMe.txt
# C:\GOG Games\Far Cry 2 Fortune's Edition\bin\FC2Editor.exe
# C:\GOG Games\Far Cry 2 Fortune's Edition\bin\FC2BenchmarkTool.exe
# C:\GOG Games\Far Cry 2 Fortune's Edition\bin\FC2ServerLauncher.exe

POL_SetupWindow_Close

# Run Failsafe as configurator
cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/GOG Games/Far Cry 2 Fortune's Edition/bin" || exit 1
TITLE="$TITLE"
POL_Debug_Init
POL_Wine farcry2.exe -RenderProfile_ResolutionX 640 -RenderProfile_ResolutionY 480 -RenderProfile_RefreshRate 0
exit 0
_EOF_

exit 0
