#!/bin/bash
# Date : (2012-08-29 21-13)
# Last revision : (2012-08-29 21-54)
# Wine version used : 1.5.11
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="far_cry_2_fortunes_edition"
PREFIX="FarCry2_gog"
WORKING_WINE_VERSION="1.5.11"

TITLE="Far Cry 2 - Fortune's Edition (GoG release)"
SHORTCUT_NAME="Far Cry 2: Fortune's Edition"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ubisoft Montréal / Ubisoft" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "2e4e11dcae8a9f9ab5c0b782e12bf33e" "e77f62e1835c92de348ed6db68a44b46" "6bc7cc8b721e846b1388ef99f4581fd3"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_Install_d3dx9_36

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "farcry2.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Far Cry 2/manual.pdf"
# C:\Program Files\GOG.com\Far Cry 2\bin\FC2Editor.exe
# C:\Program Files\GOG.com\Far Cry 2\bin\FC2BenchmarkTool.exe
# C:\Program Files\GOG.com\Far Cry 2\bin\FC2ServerLauncher.exe

POL_SetupWindow_Close

# Run Failsafe as configurator
cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Far Cry 2/bin" || exit 1
TITLE="$TITLE"
POL_Debug_Init
POL_Wine farcry2.exe -RenderProfile_ResolutionX 640 -RenderProfile_ResolutionY 480 -RenderProfile_RefreshRate 0
exit
_EOF_

exit
