#!/bin/bash
# Date : (2012-08-31 20-03)
# Last revision : (2012-10-29 02-10)
# Wine version used : 1.5.11
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="freedom_force_vs_the_3rd_reich"
PREFIX="FFvt3R_gog"
WORKING_WINE_VERSION="1.5.11"

TITLE="GOG.com - Freedom Force vs. the 3rd Reich"
SHORTCUT_NAME="Freedom Force vs. the 3rd Reich"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1384
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Irrational Games / Focus Home Interactive" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "8c6e4af36a8766a7b2df8c9790e894e1"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "ffvt3r.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/FFvTTR/Manual.pdf"
# C:\Program Files\GOG.com\FFvTTR\Readme.txt

POL_SetupWindow_Close

exit
