#!/bin/bash
# Date : (2012-03-26 20-43)
# Last revision : (2012-11-10 20-13)
# Wine version used : 1.5.0, 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="freespace_2"
PREFIX="Freespace2_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Freespace 2"
SHORTCUT_NAME="Freespace 2"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1107
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Volition / Interplay" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "06341f1ccd8f70a1e02cc236712e7726"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "FS2.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "POL_Wine_AutoSetVersionEnv"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "wineserver -k"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "nice -19 wineserver"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Freespace 2/MANUAL.PDF"
# C:\GOG Games\Freespace 2\ReadMe.txt
# C:\GOG Games\Freespace 2\refcard.pdf
# C:\GOG Games\Freespace 2\FRED2.exe

POL_SetupWindow_Close

exit
