#!/bin/bash
# Date : (2012-03-26 20-43)
# Last revision : (2013-08-11 01-16)
# Wine version used : 1.3.27
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# 1.3.32, 1.3.37, 1.4.1, 1.5.0: slow
# 1.3.29: slow?
# 1.3.28: no sound (complains about DirectSound)
# 1.3.27: fast

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="freespace_2"
PREFIX="Freespace2_gog"
WORKING_WINE_VERSION="1.3.27"

TITLE="GOG.com - Freespace 2"
SHORTCUT_NAME="Freespace 2"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1107
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Volition / Interplay" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "06341f1ccd8f70a1e02cc236712e7726"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# fake sdbinst.exe
POL_Call POL_Install_nop "$WINEPREFIX/drive_c/windows/system32/sdbinst.exe" 

POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "FS2.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/Freespace 2/MANUAL.PDF"
# C:\Program Files\GOG.com\Freespace 2\readme.txt
# C:\Program Files\GOG.com\Freespace 2\refcard.pdf

POL_SetupWindow_Close

exit 0
