#!/bin/bash
# Date : (2012-03-26 20-43)
# Last revision : (2012-03-26 21-09)
# Wine version used : 1.5.0
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_freespace_2.exe 1645549696 "06341f1ccd8f70a1e02cc236712e7726"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="Freespace2_gog"
WORKING_WINE_VERSION="1.5.0"
INSTALLBIN="setup_freespace_2.exe"

TITLE="Freespace 2 (GoG release)"
URL="http://www.gog.com/en/gamecard/freespace_2"
SHORTCUT_NAME="Freespace 2"

POL_SetupWindow_Init
POL_Debug_Init

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg"

POL_SetupWindow_presentation "$TITLE" "Volition / Interplay" "$URL" "Pierre Etchemaite" "$PREFIX"

if [ -z "$POL_SELECTED_FILE" ]; then
    POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
    [ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

if [ -n "$POL_SELECTED_FILE" ]; then
    ARCHIVE="$POL_SELECTED_FILE"
else
    cd $HOME
    POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "$INSTALLBIN"
    ARCHIVE="$APP_ANSWER"
fi

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "FS2.exe" "$SHORTCUT_NAME"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "trap 'exit 0' EXIT"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Freespace 2/MANUAL.PDF"
# C:\Program Files\GOG.com\Freespace 2\readme.txt
# C:\Program Files\GOG.com\Freespace 2\refcard.pdf

POL_SetupWindow_Close

exit
