#!/bin/bash
# Date : (2012-05-22 19-15)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="gabriel_knight_3_blood_of_the_sacred_blood_of_the_damned"
PREFIX="GabrielKnight3_gog"
WORKING_WINE_VERSION="1.4"

TITLE="GOG.com - Gabriel Knight 3: Blood of the Sacred, of the Damned"
SHORTCUT_NAME="Gabriel Knight 3: Blood of the Sacred, Blood of the Damned"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1220
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Sierra / Activision" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "cb050eca9a1bb075eef84be60ac01316"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# So that it doesn't ask for "CDROM 1"
ln -sf / "$WINEPREFIX/dosdevices/p:"
cat <<_EOFINI_ > "$POL_USER_ROOT/tmp/cdrom.reg"
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Wine\Drives]
"P:"="cdrom"
_EOFINI_
POL_Wine regedit.exe "$POL_USER_ROOT/tmp/cdrom.reg"
rm "$POL_USER_ROOT/tmp/cdrom.reg"

# There's lot of issues with GK3's Direct3D, http://bugs.winehq.org/show_bug.cgi?id=26566
# Force DirectDraw + software rendering
POL_Wine_Direct3D "DirectDrawRenderer" "gdi"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "GK3.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;AdventureGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Gabriel Knight 3/Manual.pdf"
# C:\Program Files\GOG.com\Gabriel Knight 3\Readme.txt
# C:\Program Files\GOG.com\Gabriel Knight 3\Customer_support.htm

POL_SetupWindow_Close

exit 0
