#!/bin/bash
# Date : (2012-05-20 12-32)
# Last revision : (2012-09-23 18-46)
# Wine version used : 1.4-dos_support_0.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="gabriel_knight_2_the_beast_within"
PREFIX="GabrielKnight2_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.5"

TITLE="Gabriel Knight - The Beast Within (GoG release)"
SHORTCUT_NAME="Gabriel Knight 2: The Beast Within"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1215
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Sierra / Activision" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "2d83cb2af5ca7faad6565b73fcf1deec" "f2a6c96731716ce10257dd8f14f8d416" "2b3b64b886486ddb25417d51d3b366dd"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cat <<'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
cpu_core=normal
cpu_cycles=10000
_EOFCFG_
[ "$POL_OS" = "Linux" ] && echo "render_scaler=hq2x" >> "$WINEPREFIX/playonlinux_dos.cfg"

POL_Shortcut "SIERRA.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "resource.cfg"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Gabriel Knight 2/Manual.pdf"
# C:\Program Files\GOG.com\Gabriel Knight 2\README.txt

POL_SetupWindow_Close

exit
