#!/bin/bash
# Date : (2012-04-26 23-18)
# Last revision : (2014-09-12 21-11)
# Wine version used : 1.4-dos_support_0.6, 1.6.2-dos_support_0.6
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="gabriel_knight_sins_of_the_fathers"
PREFIX="GabrielKnight1_gog"
WORKING_WINE_VERSION="1.6.2-dos_support_0.6"

TITLE="GOG.com - Gabriel Knight 1: Sins of the Fathers"
SHORTCUT_NAME="Gabriel Knight 1: Sins of the Fathers"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1147
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Sierra / Activision" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "124ea26af47fd399d4ee5d47ed7a687b"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


cat <<'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
dosbox_memsize=8
cpu_core=normal
cpu_cycles=10000
mixer_prebuffer=40
_EOFCFG_
[ "$POL_OS" = "Linux" ] && echo "render_scaler=hq2x" >> "$WINEPREFIX/playonlinux_dos.cfg"

# SB Pro music by default
cp "$GOGROOT/Gabriel Knight - Sins of the Fathers/RESOURCE.CFG" "$GOGROOT/Gabriel Knight - Sins of the Fathers/RESOURCE.BAK"
sed -e 's/soundDrv  = .*\.DRV/soundDrv  = SBPRO.DRV/' "$GOGROOT/Gabriel Knight - Sins of the Fathers/RESOURCE.BAK" > "$GOGROOT/Gabriel Knight - Sins of the Fathers/RESOURCE.CFG"

cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
imgmount D "$WINEPREFIX/drive_c/GOG Games/Gabriel Knight - Sins of the Fathers/GK1.GOG" -t iso
_EOFAE_

POL_Shortcut "SIERRA.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;AdventureGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Gabriel Knight - Sins of the Fathers/Manual.pdf"
# C:\GOG Games\Gabriel Knight - Sins of the Fathers\readme.txt

POL_SetupWindow_Close

exit 0
