#!/bin/bash
# Date : (2012-05-01 21-26)
# Last revision : (2012-10-29 02-13)
# Wine version used : 1.5.2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="tom_clancys_ghost_recon"
PREFIX="GhostRecon_gog"
WORKING_WINE_VERSION="1.5.2"

TITLE="GOG.com - Tom Clancy's Ghost Recon"
SHORTCUT_NAME="Tom Clancy's Ghost Recon"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1158
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Red Storm Entertainment / Ubisoft" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "bddd199ea8827323e0630b2c0d6078e5"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "GhostRecon.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Tom Clancy’s Ghost Recon/GR manual.pdf"
# ...\GR ReadMe.txt

POL_SetupWindow_Close

exit
