#!/bin/bash
# Date : (2012-01-04 21-13)
# Last revision : (2012-04-19 00-37)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="giants_citizen_kabuto"
PREFIX="CitizenKabuto_gog"
WORKING_WINE_VERSION="1.3.36"

TITLE="Giants: Citizen Kabuto (GoG release)"
SHORTCUT_NAME="Giants: Citizen Kabuto"
SHORTCUT_SERVER="$SHORTCUT_NAME - $(eval_gettext 'Dedicated Server Editor')"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Planet Moon Studios / Interplay" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "9f894a9268a7150c2959673fe91cacaa"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

# Doesn't hurt ;)
POL_Wine_reboot

LNG_DS="$(eval_gettext 'The dedicated server')"
POL_SetupWindow_checkbox_list "$(eval_gettext 'What extra shortcuts should be created?')" "$TITLE" "${LNG_DS}" "~"
SHORTCUTS="$APP_ANSWER"

POL_Shortcut "Giants.exe" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Giants - Citizen Kabuto/Manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Giants - Citizen Kabuto/readme.TXT

if echo "$SHORTCUTS" | grep -q "$LNG_DS"; then
    POL_Shortcut "dedicated.exe" "$SHORTCUT_SERVER"
    POL_Shortcut_Document "$SHORTCUT_SERVER" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Giants - Citizen Kabuto/readme_dedicated.txt"
fi

POL_SetupWindow_Close

exit
