#!/bin/bash
# Date : (2012-01-04 21-13)
# Last revision : (2013-05-20 12-48)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="giants_citizen_kabuto"
PREFIX="CitizenKabuto_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Giants: Citizen Kabuto"
SHORTCUT_NAME="Giants: Citizen Kabuto"
SHORTCUT_SERVER="$SHORTCUT_NAME - $(eval_gettext 'Dedicated Server Editor')"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1061
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Planet Moon Studios / Interplay" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "3b45e431472dc7a91d9cc1ab8b149246" "b34907a93089d396d6ccfe55037cba3d"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Giants.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Giants - Citizen Kabuto/MANUAL.PDF"
# C:\GOG Games\Giants - Citizen Kabuto\ReadMe.txt
# C:\GOG Games\Giants - Citizen Kabuto\dedicated.exe
# C:\GOG Games\Giants - Citizen Kabuto\readme_dedicated.txt

POL_SetupWindow_Close

exit 0
