#!/bin/bash
# Date : (2012-06-30 21-24)
# Last revision : (2013-05-12 14-50)
# Wine version used : 1.5.15
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="gothic_3"
PREFIX="Gothic3_gog"
WORKING_WINE_VERSION="1.5.15"

TITLE="GOG.com - Gothic 3"
SHORTCUT_NAME="Gothic 3"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1291
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Piranha Bytes / Nordic Games" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "e3c7cb3d39149e20fceae29cdb647954" "6bb23fa49cc030149a175d36c89d8509" "8e07902445344006466bc18d059e5db3"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# Shaders compilation doesn't seem to work under Wine, use precompiled cache from
# Community patch 1.75.14
MYDOCS_PATH="$(winepath -u "$(POL_Wine regedit /E - 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders' | sed -n 's/"Personal"="\(.*\)".*/\1/p')")"
mkdir -p "$MYDOCS_PATH/Gothic3"
cd "$MYDOCS_PATH/Gothic3" || POL_Debug_Fatal "Could not find shaders cache directory"
POL_Download "http://files.playonlinux.com/Shader.Cache.bz2" "7d256885053747b6610a77d8f3782838"
bunzip2 "Shader.Cache.bz2"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "128"

POL_Call POL_Install_d3dx9_36
POL_Call POL_Install_d3dx9_40

# Workaround for black sky
POL_Wine_Direct3D "AlwaysOffscreen" "enabled"

# Performance tweak http://appdb.winehq.org/objectManager.php?sClass=version&iId=6012&iTestingId=71819
perl -i.bak -pe 'print "Timer.ThreadSafe=false\r\n" if /^Timer\.bIsSmooth=/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Gothic 3/Ini/ge3.ini"

POL_Wine_X11Drv "GrabFullScreen" "Y"
POL_Wine_X11Drv "DXGrab" "Y"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Gothic3.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Gothic 3/Manual.pdf"
# C:\Program Files\GOG.com\Gothic 3\readme.txt

POL_SetupWindow_Close

exit 0
