#!/bin/bash
# Date : (2012-05-31 20-09)
# Last revision : (2012-06-02 15-03)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="gothic_2_gold_edition"
PREFIX="Gothic2_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="Gothic 2 Gold (GoG release)"
SHORTCUT_NAME="Gothic 2 Gold"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Piranha Bytes / Nordic Games" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "62ca675dafe649497c03fe52de41433f"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

POL_Call POL_Install_directmusic

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "gogwrap.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "GOGGOTHIC2GOLD"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Gothic 2 Gold/manual.pdf"
# C:\Program Files\GOG.com\Gothic 2 Gold\Readme.txt
# C:\Program Files\GOG.com\Gothic 2 Gold\manual_addon.pdf

POL_SetupWindow_Close

exit
