#!/bin/bash
# Date : (2011-12-03 20-32)
# Last revision : (2012-01-02 20-41)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archive:
# setup_ground_control_2.exe 641603732 "dd1ae6e7ae1420bc52dc5327e974ea9e"

# Supposed to be "Gold" on WineHQ with 1.3.23, but I crash it with middle-click + drag
# Same for 1.3.27-rawinput2,
# very easily with 1.3.33
# couldn't crash it with 1.3.34-rawinput2
# 1.3.34 ok

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="GrndCtrl2_gog"
WORKING_WINE_VERSION="1.3.36"

TITLE="$(eval_gettext 'Ground Control 2 (GoG release)')"
SHORTCUT_NAME="Ground Control 2"
SHORTCUT_DOC="$SHORTCUT_NAME - $(eval_gettext 'User manual')"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Massive Entertainment / Rebellion" "http://www.gog.com/en/gamecard/ground_control_2_operation_exodus" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "setup_ground_control_2.exe"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_InstallFonts

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Helps at least when windowed
POL_Wine_X11Drv "GrabFullScreen" "Y"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "gcii.exe" "$SHORTCUT_NAME"
POL_Shortcut "start.exe" "$SHORTCUT_DOC" "" "'C:/$PROGRAMFILES/GOG.com/Ground Control II/Manual.pdf'"

POL_SetupWindow_Close
exit
