#!/bin/bash
# Date : (2012-04-29 21-51)
# Last revision : (2013-07-10 13-33)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="guilty_gear_x2_reload"
PREFIX="GuiltyGearX2_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Guilty Gear X2 Reload"
SHORTCUT_NAME="Guilty Gear X2 #Reload"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1153
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Arc System Works Co. / Funbox Media" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "3ba91b3b7b0fe033d4ba597410d5d982"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

POL_Call POL_Install_devenum
POL_Call POL_Install_quartz
# If I don't do that videos are black (?)
POL_Wine regsvr32 quartz.dll

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "launcher.exe" "$SHORTCUT_NAME" "Guilty Gear X2 Reload.png" "" "Game;ActionGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Guilty Gear X2 Reload/manual.pdf"
# C:\Program Files\GOG.com\Guilty Gear X2 Reload/README.TXT

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Guilty Gear X2 Reload/" || exit 1

TITLE="$TITLE"

POL_Wine --ignore-errors config.exe

exit 0
_EOF_

SETTINGS="$WINEPREFIX/drive_c/users/$USER/Application Data/ZOO Digital Publishing/GuiltyGearX2/setting.cfg"
while [ ! -e "$SETTINGS" ]; do
  bash "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
  # Disable Pixel Shaders
  [ -e "$SETTINGS" ] && dd if=/dev/zero of="$SETTINGS" bs=1 seek=247 count=1 conv=notrunc
done

exit 0
