#!/bin/bash
# Date : (2012-12-23 16-55)
# Last revision : (2013-01-26 17-37)
# Wine version used : 1.3.19
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Wine 1.3.19 choice:
# http://appdb.winehq.org/objectManager.php?sClass=version&iId=24425&iTestingId=67710

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="heroes_of_might_and_magic_3_complete_edition"
PREFIX="HoMM3_gog"
WORKING_WINE_VERSION="1.3.19"

TITLE="GOG.com - Heroes of Might and Magic 3 Complete"
SHORTCUT_NAME="Heroes of Might and Magic 3 Complete"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1518
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "New World Computing Inc. / Ubisoft" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "7a39cfc99b1d41a45ea18474033ea0cb"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Heroes3.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Heroes of Might and Magic 3 Complete/Heroes3_Manual.pdf"
# C:\Program Files\GOG.com\Heroes of Might and Magic 3\Heroes3_AB_Manual.pdf
# C:\Program Files\GOG.com\Heroes of Might and Magic 3\Heroes3_SoD_Manual.pdf
# C:\Program Files\GOG.com\Heroes of Might and Magic 3\Heroes3_Tutorial.pdf
# C:\Program Files\GOG.com\Heroes of Might and Magic 3\README.TXT
# C:\Program Files\GOG.com\Heroes of Might and Magic 3\h3ccmped.exe
# C:\Program Files\GOG.com\Heroes of Might and Magic 3\h3maped.exe

POL_SetupWindow_Close

exit
