#!/bin/bash
# Date : (2012-12-08 09-28)
# Last revision : (2013-07-10 13-33)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="hitman"
PREFIX="HitmanCN47_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Hitman: Codename 47"
SHORTCUT_NAME="Hitman: Codename 47"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1506
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "IO Interactive / Square Enix" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "00583288b643718f2b98bbe50012fc02"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Select OpenGL renderer by default
cat <<'_EOFCFG_' > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Hitman Codename 47/Hitman.ini"
Include Setup\Locale.zip
//DrawDll Render3DFX.dll
DrawDll renderopengl.dll
//DrawDll RenderOpenGL.dll
SoundDll Sound.dll
ScriptDll GSC.dll
LocaleDLL Locale.dll
Resolution 800x600
ColorDepth 0
_EOFCFG_

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "hitman.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Hitman Codename 47/manual.pdf"
# C:\Program Files\GOG.com\Hitman Codename 47\keybindings_Numpad.pdf
# C:\Program Files\GOG.com\Hitman Codename 47\keybindings_WASD.pdf

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Hitman Codename 47/" || exit 1
TITLE="$TITLE"

POL_Wine Setup.exe
exit 0
_EOF_

exit 0
