#!/bin/bash
# Date : (2012-05-13 17-24)
# Last revision : (2012-05-24 19-40)
# Wine version used : 1.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="icewind_dale_complete"
PREFIX="IcewindDale_gog"
WORKING_WINE_VERSION="1.4"

TITLE="Icewind Dale Complete (GoG release)"
SHORTCUT_NAME="Icewind Dale"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Black Isle Studios / Hasbro Inc." "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "add3f33f3651ea39277806c9a77360c3"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Prevent a lot of fixme:dplay:DP_IF_Receive in logs during game
POL_Call POL_Install_directplay

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "IDMain.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Icewind Dale Complete/Manual.PDF"
# C:\Program Files\GOG.com\Icewind Dale Complete\readme.txt
# C:\Program Files\GOG.com\Icewind Dale Complete\readme_addon.TXT
# C:\Program Files\GOG.com\Icewind Dale Complete\readme_addon2.txt

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Icewind Dale Complete/" || exit 1

TITLE="$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_Wine Config.exe

POL_Call POL_Configurator_runparts

POL_SetupWindow_Close
exit
_EOF_

exit
