#!/bin/bash
# Date : (2012-02-28 21-20)
# Last revision : (2013-03-24 15-47)
# Wine version used : 1.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="incoming_incoming_forces"
PREFIX="IncomingForces_gog"
WORKING_WINE_VERSION="1.4"

TITLE="GOG.com - Incoming and Incoming Forces"
SHORTCUT_NAME1="Incoming"
SHORTCUT_NAME2="Incoming Forces"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1080
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Rage Software / Kalypso Media Digital" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "6bdfc2bc17028db1789d04333f329818"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Needed for Incoming only
POL_Call POL_Install_vcrun2008

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "incoming.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Incoming and Incoming Forces/Incoming/Manual.pdf"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME1"

POL_Shortcut "forces.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Incoming and Incoming Forces/Incoming Forces/Manual.pdf"

POL_SetupWindow_Close

exit 0
