#!/bin/bash
# Date : (2012-02-28 21-20)
# Last revision : (2012-02-28 21-29)
# Wine version used : 1.4-rc5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_incoming_and_incoming_forces.exe 441032824 "6bdfc2bc17028db1789d04333f329818"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="IncomingForces_gog"
WORKING_WINE_VERSION="1.4-rc5"
INSTALLBIN="setup_incoming_and_incoming_forces.exe"

TITLE="Incoming Forces (GoG release)"
URL="http://www.gog.com/en/gamecard/incoming_incoming_forces"
SHORTCUT_NAME="Incoming Forces"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Rage Software / Kalypso Media Digital" "$URL" "Pierre Etchemaite" "$PREFIX"

POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
[ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "$INSTALLBIN"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_message "$(eval_gettext 'Note: I did not manage to get Incoming to work correctly, this installer\nwill just take care of Incoming Forces. You can deselect Incoming\nfrom GOG installer to save some disk space.')" "$TITLE"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "forces.exe" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Incoming and Incoming Forces/Incoming Forces/Manual.pdf"

POL_SetupWindow_Close

exit
