#!/bin/bash
# Date : (2012-02-28 21-20)
# Last revision : (2012-04-05 22-48)
# Wine version used : 1.4-rc5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_incoming_and_incoming_forces.exe 441032824 "6bdfc2bc17028db1789d04333f329818"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="IncomingForces_gog"
WORKING_WINE_VERSION="1.4-rc5"
INSTALLBIN="setup_incoming_and_incoming_forces.exe"

TITLE="Incoming & Incoming Forces (GoG release)"
URL="http://www.gog.com/en/gamecard/incoming_incoming_forces"
SHORTCUT_NAME1="Incoming"
SHORTCUT_NAME2="Incoming Forces"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Rage Software / Kalypso Media Digital" "$URL" "Pierre Etchemaite" "$PREFIX"

if [ -z "$POL_SELECTED_FILE" ]; then
    POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
    [ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

if [ -n "$POL_SELECTED_FILE" ]; then
    ARCHIVE="$POL_SELECTED_FILE"
else
    cd $HOME
    POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "$INSTALLBIN"
    ARCHIVE="$APP_ANSWER"
fi

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Needed for Incoming only
POL_Call POL_Install_vcrun2008

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "incoming.exe" "$SHORTCUT_NAME1"
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Incoming and Incoming Forces/Incoming/Manual.pdf"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME1"
POL_ExtractIcon "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Incoming and Incoming Forces/Incoming/gfw_high.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT_NAME1"
POL_ExtractBiggestIcon "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Incoming and Incoming Forces/Incoming/gfw_high.ico" "$POL_USER_ROOT/icones/full_size/$SHORTCUT_NAME1"

POL_Shortcut "forces.exe" "$SHORTCUT_NAME2"
POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Incoming and Incoming Forces/Incoming Forces/Manual.pdf"
POL_ExtractIcon "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Incoming and Incoming Forces/Incoming Forces/gfw_high.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT_NAME2"
POL_ExtractBiggestIcon "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Incoming and Incoming Forces/Incoming Forces/gfw_high.ico" "$POL_USER_ROOT/icones/full_size/$SHORTCUT_NAME2"

POL_SetupWindow_Close

exit
