#!/bin/bash
# Date : (2012-01-08 20-49)
# Last revision : (2012-04-19 00-52)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="iron_storm"
PREFIX="IronStorm_gog"
WORKING_WINE_VERSION="1.3.36"

TITLE="Iron Storm (GoG release)"
SHORTCUT_NAME="Iron Storm"
SHORTCUT_DS="$SHORTCUT_NAME - $(eval_gettext 'Dedicated Server')"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "4X Studio / Anuman Interactive" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "ce666bf38c8c722f1d675b394c44c1f7"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "IronStorm.exe" "$SHORTCUT_NAME"
POL_Shortcut "IronStorm_DS.exe" "$SHORTCUT_DS"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Iron Storm/Manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Iron Storm/readme.txt

POL_SetupWindow_Close

exit
