#!/bin/bash
# Date : (2012-01-23 01-07)
# Last revision : (2013-04-20 20-59)
# Wine version used : 1.3.37, 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="jack_orlando_a_cinematic_adventure_dc"
PREFIX="JackOrlandoDC_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Jack Orlando: A Cinematic Adventure"
SHORTCUT_NAME="Jack Orlando DC"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1062
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Toontraxx / Topware Interactive" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "ea8815ca57005b75368163897b51e1f2"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "JackOrlando.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;AdventureGame;"
# sometimes exits with an exitcode != 0 for what it seems no good reason
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Jack Orlando Director's Cut/Manual.pdf"

POL_SetupWindow_Close

exit 0
