#!/bin/bash
# Date : (2012-06-03 00-19)
# Last revision : (2012-10-29 02-24)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="kingpin_life_of_crime"
PREFIX="KingpinLOC_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="GOG.com - Kingpin: Life of Crime"
SHORTCUT_NAME="Kingpin: Life of Crime"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1241
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Xatrix Entertainment / Interplay" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "a2153a264fdaf6b0b241188bbf830f6d"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "kingpin.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
# Report a shorter version string http://www.linuxpoweruser.com/?cat=6
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'export __GL_ExtensionStringVersion=17700'
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Kingpin/MANUAL.PDF"
# C:\Program Files\GOG.com\Kingpin\readme.txt
# C:\Program Files\GOG.com\Kingpin\kprad\radiant.exe (QERadiant Editor)

POL_SetupWindow_Close

exit
