#!/bin/bash
# Date : (2012-11-30 23-44)
# Last revision : (2012-12-01 01-00)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="lands_of_lore_3"
PREFIX="LandsOfLore_3_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Lands of Lore 3"
SHORTCUT_NAME="Lands of Lore 3"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
#POL_SetupWindow_SetID ScriptIDNumber
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Westwood Studios / Electronic Arts" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "6d283a252fd05c23eafc8bb57b1d3beb" "fc97f3f2aa662f1255d9365926821375" "c69cf62442cadf1c9e88bec801702853"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# fake sdbinst.exe
POL_Call POL_Install_nop "$WINEPREFIX/drive_c/windows/system32/sdbinst.exe" 

POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "LOL3.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "-CD. -16MB -NO_ASSERTS"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Lands of Lore 3/Manual.pdf"
# C:\GOG Games\Lands of Lore 3\Keycard.pdf

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/GOG Games/Lands of Lore 3/" || exit 1
TITLE="$TITLE"

POL_Debug_Init
POL_Wine nglide_config.exe
exit
_EOF_

exit
