#!/bin/bash
# Date : (2012-05-14 21-36)
# Last revision : (2012-05-14 22-11)
# Wine version used : 1.5.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="legend_of_grimrock"
PREFIX="LegendOfGrimrock_gog"
WORKING_WINE_VERSION="1.5.4"

TITLE="Legend of Grimrock (GoG release)"
SHORTCUT_NAME="Legend of Grimrock"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Almost Human" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "900f5d84a47118961a8d86ff156cea51"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# FIXME
POL_SetupWindow_message "$(eval_gettext 'When asked to install DirectX 9.0c, accept.')" "$TITLE"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

POL_Call POL_Install_d3dx9
POL_Call POL_Install_xact
POL_Wine_OverrideDLL builtin d3dx9_43

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "grimrock.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Legend of Grimrock/legend_of_grimrock_manual.pdf"
# C:\Program Files\GOG.com\Legend of Grimrock/legend_of_grimrock_map.pdf

POL_SetupWindow_Close

exit
