#!/bin/bash
# Date : (2012-08-02 15-20)
# Last revision : (2012-10-29 02-27)
# Wine version used : 1.4-dos_support_0.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="little_big_adventure_2"
PREFIX="LittleBigAdventure2_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.5"

TITLE="GOG.com - Little Big Adventure 2"
SHORTCUT_NAME="Little Big Adventure 2: Twinsen's Odyssey"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1342
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Adeline Software International / Didier Chanfray SARL" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "cb7cd7056cbb8bf7164548185795667f"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
dosbox_memsize=30
cpu_core=auto
cpu_cputype=auto
cpu_cycles=max
mixer_prebuffer=240
_EOFCFG_

cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
imgmount D "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Little Big Adventure 2/LBA2.DAT" -t iso
_EOFAE_

# LBA2.EXE is detected as Windows executable
cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Little Big Adventure 2/LBA2.BAT"
@ECHO OFF
LBA2.EXE
EXIT
_EOFBAT_

POL_Shortcut "LBA2.BAT" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Little Big Adventure 2/manual.pdf"
# C:\Program Files\GOG.com\Little Big Adventure 2\README.TXT

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Little Big Adventure 2/" || exit 1
TITLE="$TITLE"
POL_Debug_Init
POL_Wine Language.exe
exit 0
_EOF_

exit 0
