#!/bin/bash
# Date : (2012-03-11 19-24)
# Last revision : (2012-09-23 18-54)
# Wine version used : 1.4-scummvm_support
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="lure_of_the_temptress"
PREFIX="LureOfTheTemptress_gog"
WORKING_WINE_VERSION="1.4-scummvm_support"

TITLE="Lure of the Temptress (GoG release)"
SHORTCUT_NAME="Lure of the Temptress"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1096

POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Revolution Software" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "dcc8c74c53670f308a37dbead4181965"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# "SVGA videocard" (?)
POL_SetupWindow_VMS "2"

cat <<_EOFCFG_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Lure of the Temptress/lure.polcfg"
[lure]
description=Lure of the Temptress (VGA/DOS/English)
platform=pc
gameid=lure
language=en
extra=VGA
multi_midi=true
enable_gs=true
native_mt32=true
_EOFCFG_

POL_Shortcut "lure.polcfg" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Lure of the Temptress/Manual.pdf"
# C:\Program Files\GOG.com\Lure of the Temptress\solution.txt

POL_SetupWindow_Close

exit
