#!/bin/bash
# Date : (2012-03-11 19-24)
# Last revision : (2013-03-24 15-47)
# Wine version used : 1.4-scummvm_support
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="lure_of_the_temptress"
PREFIX="LureOfTheTemptress_gog"
WORKING_WINE_VERSION="1.4-scummvm_support"

TITLE="GOG.com - Lure of the Temptress"
SHORTCUT_NAME="Lure of the Temptress"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1096

POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Revolution Software" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "4650bfa2cbcef03980ba1e0a57f49a7f"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# "SVGA videocard" (?)
POL_SetupWindow_VMS "2"

cat <<_EOFCFG_ > "$WINEPREFIX/drive_c/GOG Games/Lure of the Temptress/lure.polcfg"
[lure]
description=Lure of the Temptress (VGA/DOS/English)
platform=pc
gameid=lure
language=en
extra=VGA
multi_midi=true
enable_gs=true
native_mt32=true
_EOFCFG_

POL_Shortcut "lure.polcfg" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Lure of the Temptress/Manual.pdf"
# C:\GOG Games\Lure of the Temptress\solution.txt

POL_SetupWindow_Close

exit 0
