#!/bin/bash
# Date : (2012-10-23 19-42)
# Last revision : (2012-10-27 01-05)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="might_and_magic_7_for_blood_and_honor"
PREFIX="MightAndMagic7_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="Might and Magic 7 - For Blood and Honor (GoG release)"
SHORTCUT_NAME="Might and Magic 7 - For Blood and Honor"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1448
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "New World Computing / Ubisoft" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "089ede3d8084de1160cf9ccd73aa75ad"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader, Foxit or SumatraPDF in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "MM7.exe" "$SHORTCUT_NAME" "" "" # "$SHORTCUT_NAME.png"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Might and Magic VII/MANUAL.PDF"
# C:\Program Files\GOG.com\Might and Magic VII\Readme.txt
# C:\Program Files\GOG.com\Might and Magic VII\MAP.PDF
# C:\Program Files\GOG.com\Might and Magic VII\Reference_card.PDF

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Might and Magic VII/" || exit 1
TITLE="$TITLE"
POL_Debug_Init
POL_Wine MM7Setup.exe

exit
_EOF_

exit
