#!/bin/bash
# Date : (2013-08-20 22-37)
# Last revision : (2013-08-20 22-44)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="moonbase_commander"
PREFIX="MoonbaseCommander_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Moonbase Commander"
SHORTCUT_NAME="Moonbase Commander"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
#POL_SetupWindow_SetID ScriptIDNumber
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Humongous Entertainment / Rebellion" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "3e5a0b82d6532832d901fa7152013788"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


POL_Call POL_Install_directplay

# GoG work!
Set_OS winxp

# 640x480x16bpp?
POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "moonbase.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/Moonbase Commander/Manual.pdf"
# C:\GOG Games\Moonbase Commander\Readme.txt

POL_SetupWindow_Close

exit 0
