#!/bin/bash
# Date : (2012-03-17 10-47)
# Last revision : (2012-09-14 23-42)
# Wine version used : 1.3.27
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Logo screen does not show up starting from Wine 1.3.28:
# http://bugs.winehq.org/show_bug.cgi?id=28869
# Tested up to Wine 1.5.0

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="neverwinter_nights_diamond_edition"
PREFIX="NeverwinterNights_gog"
WORKING_WINE_VERSION="1.3.27"

TITLE="Neverwinter Nights Diamond Edition (GoG release)"
SHORTCUT_NAME="Neverwinter Nights Diamond Edition"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bioware / Atari" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "5e07fe97815bf329eacd1f0a474128cc" "9e5aec8eb2a8bea2626a51d36e72d12e" "ba9ed46b94eb84870e9e41eeab653859"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "nwn.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Neverwinter Nights Diamond Edition/NWN_OnlineManual.pdf"
# C:\Program Files\GOG.com\Neverwinter Nights Diamond Edition\NWNHordes_Manual.pdf
# C:\Program Files\GOG.com\Neverwinter Nights Diamond Edition\NWN_SoU_OnlineManual.pdf
# C:\Program Files\GOG.com\Neverwinter Nights Diamond Edition\readme.txt
# C:\Program Files\GOG.com\Neverwinter Nights Diamond Edition\HotUreadme.txt
# C:\Program Files\GOG.com\Neverwinter Nights Diamond Edition\SoUreadme.txt

POL_SetupWindow_Close

exit
