#!/bin/bash
# Date : (2012-03-17 10-47)
# Last revision : (2013-07-10 13-36)
# Wine version used : 1.3.27
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Logo screen does not show up starting from Wine 1.3.28:
# http://bugs.winehq.org/show_bug.cgi?id=28869
# Tested up to Wine 1.5.0

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="neverwinter_nights_diamond_edition"
PREFIX="NeverwinterNights_gog"
WORKING_WINE_VERSION="1.3.27"

TITLE="GOG.com - Neverwinter Nights Diamond Edition"
SHORTCUT_NAME="Neverwinter Nights Diamond Edition"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1099
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bioware / Atari" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "f951e13536f8ad0e424f719ba88bd39c" "7e434f93b72fe3e75f58db9c725d5478" "0036284492df9f3430b1b00a17757718"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "nwmain.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Neverwinter Nights Diamond Edition/NWN_OnlineManual.pdf"
# C:\GOG Games\Neverwinter Nights Diamond Edition\readme.txt
# C:\GOG Games\Neverwinter Nights Diamond Edition\NWNHordes_Manual.pdf
# C:\GOG Games\Neverwinter Nights Diamond Edition\NWN_SoU_OnlineManual.pdf

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/GOG Games/Neverwinter Nights Diamond Edition/" || exit 1
TITLE="$TITLE"

POL_Wine nwconfig.exe
exit 0
_EOF_

exit 0
