#!/usr/bin/env playonlinux-bash
# Date : (2011-12-17 15-39)
# Last revision : (2013-05-19 20-05)
# Wine version used : 1.3.36, 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Works with 1.1.34, but much slower!

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="nox"
PREFIX="Nox_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Nox"
SHORTCUT_NAME="Nox"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top2.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left2.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1022
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Westwood Studios / Electronic Arts" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "c1cc844fb0f17bd8e7406354eef1616e"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "NOX.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Nox/manual.pdf"
# C:/GOG Games/Nox/Readme.txt

POL_SetupWindow_Close

exit 0
