#!/bin/bash
# Date : (2012-06-21 21-14)
# Last revision : (2012-09-23 18-58)
# Wine version used : 1.4-dos_support_0.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="one_unit_whole_blood"
PREFIX="OneUnitWholeBlood_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.5"

TITLE="One Unit Whole Blood (GoG release)"
SHORTCUT_NAME1="Blood: One Unit Whole Blood"
SHORTCUT_NAME2="Blood: Cryptic Passage"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1269
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Monolith Productions / Atari" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "a72a31def93390c794fc80a906328536"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
dosbox_memsize=64
cpu_core=auto
cpu_cycles=max
mixer_blocksize=2048
mixer_prebuffer=240
sblaster_sbtype=sb16
sblaster_sbbase=220
sblaster_irq=5
sblaster_dma=1
sblaster_hdma=5
sblaster_mixer=true
sblaster_oplmode=auto
sblaster_oplrate=22050
ipx_enable=1
ipx_connection=1
ipx_ipx=true
_EOFCFG_

cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
imgmount D "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/One Unit Whole Blood/game.inst" -t iso
_EOFAE_

POL_Shortcut "BLOOD.EXE" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/One Unit Whole Blood/Manual.pdf"
# C:\Program Files\GOG.com\One Unit Whole Blood\README.TXT

POL_Shortcut "CRYPTIC.EXE" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME1"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/One Unit Whole Blood/" || exit 1

TITLE="$TITLE"

POL_Debug_Init

POL_Wine SETUP.EXE

exit
_EOF_

exit
