#!/bin/bash
# Date : (2013-01-07 23-32)
# Last revision : (2013-01-08 19-11)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="original_war"
PREFIX="OriginalWar_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Original War"
SHORTCUT_NAME="Original War"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1531
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Altar Interactive / Bohemia Interactive Studio" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "d110b305c36e4f5fd2db7465c06d1303"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

# Screen can be scrolled by moving the mouse to the borders
POL_Wine_X11Drv "GrabFullScreen" "Y"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Owar.exe" "$SHORTCUT_NAME" "" "" # "$SHORTCUT_NAME.png"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Original War/Manual.pdf"
# C:\Program Files\GOG.com\Original War\readme.txt
# C:\Program Files\GOG.com\Original War\Help\English\Index.htm
# C:\Program Files\GOG.com\Original War\OwarDedicated.exe
# C:\Program Files\GOG.com\Original War\GM_Editor.exe
# C:\Program Files\GOG.com\Original War\gm_view.exe
# C:\Program Files\GOG.com\Original War\grndsec.exe
# C:\Program Files\GOG.com\Original War\PRCiX.exe
# C:\Program Files\GOG.com\Original War\PakView.exe
# C:\Program Files\GOG.com\Original War\OWP_Validator.exe
# C:\Program Files\GOG.com\Original War\XichtEd.exe
# C:\Program Files\GOG.com\Original War\ow_editor.exe
# C:\Program Files\GOG.com\Original War\Utils\TitleCreator\Titulky.exe
# C:\Program Files\GOG.com\Original War\ModLauncher.exe
# C:\Program Files\GOG.com\Original War\Utils\MMSC\Meaaov_ModSetupCompiler.exe

POL_SetupWindow_Close

exit 0
