#!/bin/bash
# Date : (2011-11-28 22-00)
# Last revision : (2012-01-29 01-10)
# Wine version used : 1.3.27-rawinput2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Freeware
# Depend : unzip

# Tested with install archive:
# OUTCASTP_V3.zip 102462783 "d1c6783339150684c659d5fb56f130dc"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

# Must match outcast-gog script values
PREFIX="Outcast_gog"
SHORTCUT_NAME="Outcast"

TITLE="$(eval_gettext 'Zenger s Outcast HI-RES patch v3')"
SHORTCUT_NAME="$(eval_gettext 'Zenger Hi-Res patch v3')"

POL_SetupWindow_Init
POL_Debug_Init
# URL shortener? :p
POL_SetupWindow_presentation "$TITLE" "Zenger" "http://www.gog.com/en/forum/outcast/...\nexperimental_outcast_hi_res_patch...\n_up_to_1280x768_cyana_lighthouse_problem_fixed/" "Pierre Etchemaite" "$PREFIX"

check_one "unzip" "unzip"
POL_SetupWindow_missing

if [ "$(POL_Wine_PrefixExists $PREFIX)" != "True" ]; then
    POL_Debug_Fatal "$(eval_gettext 'Oops, you must install Outcast (GoG release) first!')"
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_LoadVar_PROGRAMFILES

POL_SetupWindow_message "$(eval_gettext 'You can download the archive file from:')\nhttp://www.megaupload.com/?d=H6CIR27L" "$TITLE"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "OUTCASTP_V3.zip"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

unzip -n "$ARCHIVE" -d "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Outcast/" || POL_Debug_Fatal "$(eval_gettext 'Error why unzipping the archive')"

POL_SetupWindow_message "$(eval_gettext 'The patch can now be activated and configured from\nPlayOnLinux s setup wizard for Outcast.\nAnd dont forget to leave a message to Zenger on GoG forums!')" "$TITLE"

POL_SetupWindow_Close

cat <<_EOF_ > $POL_USER_ROOT/configurations/configurators/"$SHORTCUT_NAME".zenger-hires

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Outcast/" || return
[ -e APPLYMEGAPATCH.exe ] || return

POL_SetupWindow_question "$(eval_gettext 'Run \$TITLE?')" "\$TITLE"
if [ "\$APP_ANSWER" = "TRUE" ]; then

    POL_SetupWindow_wait "\$TITLE" "\$TITLE"

    POL_Wine APPLYMEGAPATCH.exe

    SCREEN_WIDTH=\$(grep '^ScreenWidth=' OUTCAST.ini |cut -d= -f2)
    SCREEN_HEIGHT=\$(grep '^ScreenHeight=' OUTCAST.ini |cut -d= -f2)
    Set_Desktop "On" "\$SCREEN_WIDTH" "\$SCREEN_HEIGHT"

    POL_SetupWindow_message "$(eval_gettext 'Check that the resolution has been changed\n(eventually set to \"HI-RES\") in the loader.')" "\$TITLE"

fi
_EOF_
