#!/bin/bash
# Date : (2012-01-07 21-26)
# Last revision : (2013-03-24 18-19)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="painkiller"
PREFIX="PainkillerBlack_gog"
WORKING_WINE_VERSION="1.3.36"

TITLE="GOG.com - Painkiller: Black Edition"
SHORTCUT_NAME="Painkiller Black Edition"
SHORTCUT_EDITOR="$SHORTCUT_NAME - $(eval_gettext 'Editor')"
SHORTCUT_DS="$SHORTCUT_NAME - $(eval_gettext 'Dedicated Server')"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1035
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "People Can Fly / Nordic Games" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "04779d4d56e828daff8f82ba239d96a3" "7db45f6fb84caa50f4b4679a63f30418" "23f6f6b2078b5b909eaacff0a8238586"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


Set_OS winxp

POL_SetupWindow_VMS "64"

# Doesn't hurt ;)
POL_Wine_reboot

LNG_EDITOR="$(eval_gettext 'Editor')"
LNG_DS="$(eval_gettext 'Dedicated server')"
POL_SetupWindow_checkbox_list "$(eval_gettext 'What extra shortcuts should be created?')" "$TITLE" "${LNG_EDITOR}~${LNG_DS}" "~"
SHORTCUTS="$APP_ANSWER"

POL_Shortcut "Painkiller.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Painkiller Black/Docs/Manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Painkiller Black/Docs/ReadMe.txt

if echo "$SHORTCUTS" | grep -q "$LNG_EDITOR"; then
    POL_Shortcut "PainEditor.exe" "$SHORTCUT_EDITOR" "$SHORTCUT_NAME.png" "" "Game"
    POL_Shortcut_Document "$SHORTCUT_EDITOR" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Painkiller Black/Docs/Pain Engine.pdf"
fi

if echo "$SHORTCUTS" | grep -q "$LNG_DS"; then
    POL_Shortcut "Painkiller.exe" "$SHORTCUT_DS" "$SHORTCUT_NAME.png" "-dedicated" "Game"
fi

POL_SetupWindow_Close

exit 0
