#!/bin/bash
# Date : (2012-10-19 18-04)
# Last revision : (2012-10-29 02-36)
# Wine version used : 1.4-dos_support_0.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="pirates_gold_plus"
PREFIX="PiratesPack_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.5"

TITLE="GOG.com - Pirates Pack"
SHORTCUT_NAME1='Pirates!'
SHORTCUT_NAME2='Pirates! Gold'

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1441
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "MicroProse / Atari" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "fd11a9b1da6393da7d1ca12b2b24e4f8"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader, Foxit or SumatraPDF in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# Pirate! Gold expects itself in C:\, at least some parts
mv "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Pirates Pack/Pirates GOLD"/* "$WINEPREFIX/drive_c/"


cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
dosbox_memsize=30
cpu_core=normal
cpu_cycles=5000
sblaster_sbtype=sb16
sblaster_sbbase=220
sblaster_irq=7
sblaster_dma=1
sblaster_hdma=5
sblaster_mixer=true
sblaster_oplmode=auto
sblaster_oplrate=22050
render_aspect=true
_EOFCFG_
# I prefer advmame2x over hq2x for Pirates! game - more "round" letters maybe
[ "$POL_OS" = "Linux" ] && echo "render_scaler=advmame2x" >> "$WINEPREFIX/playonlinux_dos.cfg"

cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Pirates Pack/Pirates!/P1.BAT"
@ECHO OFF
LOADFIX
PIR.EXE
EXIT
_EOFBAT_

cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/P2.BAT"
@ECHO OFF
imgmount D "$WINEPREFIX/drive_c/DATA.DAT" -t iso
D:
CALL PIRATESG.BAT
EXIT
_EOFBAT_

POL_Shortcut "P1.BAT" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Pirates Pack/Pirates!/codes.pdf"
#POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Pirates Pack/Pirates!/manual.pdf"

POL_Shortcut "P2.BAT" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/flags.pdf"
#POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/manual.pdf"

POL_SetupWindow_Close

exit
