#!/bin/bash
# Date : (2012-06-10 20-41)
# Last revision : (2012-12-06 21-08)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="planescape_torment"
PREFIX="PlanescapeTorment_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Planescape: Torment"
SHORTCUT_NAME="Planescape: Torment"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1253
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Black Isle Studios / Hasbro Inc." "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "98474820330a1487694c61820c85fa45"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

# "Fixed" version gives mouse cursor trails under Wine
cd "$WINEPREFIX/drive_c/GOG Games/Planescape Torment" || POL_Debug_Fatal "Game not installed in standard path?"
POL_Wine setup-ddrawfix.exe --uninstall
rm -r setup-ddrawfix.exe ddrawfix

POL_Shortcut "Torment.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Planescape Torment/manual.pdf"
# C:\GOG Games\Planescape Torment\Readme.txt

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/GOG Games/Planescape Torment/" || exit 1

TITLE="$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_Call POL_Configurator_runparts

POL_SetupWindow_Close
exit
_EOF_

exit
