#!/bin/bash
# Date : (2012-07-08 18-17)
# Last revision : (2012-10-29 02-38)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="postal_2_complete"
PREFIX="Postal2Complete_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="GOG.com - Postal 2 Complete"
SHORTCUT_NAME1="Postal 2 Share the Pain"
SHORTCUT_NAME2="Postal 2 Apocalypse Weekend"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1305
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Running With Scissors" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "16882025e2654e0e4aa141b10c8fe91d"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

POL_Wine_DirectInput "MouseWarpOverride" "force"

# Doesn't hurt ;)
POL_Wine_reboot

# Oh joy, the game and the extension binaries share the same name!
POL_Shortcut "$PROGRAMFILES/GOG.com/Postal 2 Share The Pain/System/Postal2.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Postal 2 Share The Pain/Manual.pdf"
# C:\Program Files\GOG.com\Postal 2 Share The Pain/Help.htm
# C:\Program Files\GOG.com\Postal 2 Share The Pain/System/UnrealEd.exe -safe

POL_Shortcut "$PROGRAMFILES/GOG.com/Postal 2 Share The Pain/ApocalypseWeekend/System/postal2.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Postal 2 Share The Pain/Apocalypse Weekend Manual.pdf"
# C:\Program Files\GOG.com\Postal 2 Share The Pain/ApocalypseWeekend/System/UnrealEd.exe

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME1"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Postal 2 Share The Pain/System" || exit 1
TITLE="$TITLE"
POL_Debug_Init
POL_Wine Postal2.exe -safe
exit
_EOF_

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME2"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Postal 2 Share The Pain/ApocalypseWeekend/System" || exit 1
TITLE="$TITLE"
POL_Debug_Init
POL_Wine postal2.exe -safe
exit
_EOF_

exit
