#!/bin/bash
# Date : (2012-04-09 13-47)
# Last revision : (2012-04-10 23-03)
# Wine version used : 1.5.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="prince_of_persia_the_sands_of_time"
PREFIX="SandsOfTime_gog"
WORKING_WINE_VERSION="1.5.1"

TITLE="Prince of Persia: The Sands of Time (GoG release)"
SHORTCUT_NAME="Prince of Persia: The Sands of Time"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ubisoft" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_setup "$GOGID" "f0a210a07427c92b938ae532073a1664"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "PrinceOfPersia.EXE" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Prince of Persia The Sands of Time/manual.pdf"
# C:\Program Files\GOG.com\Prince of Persia The Sands of Time\readme.txt

# Disable fog option by default
if type -t POL_unbase64 > /dev/null; then
	POL_unbase64 <<-_EOF_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Prince of Persia The Sands of Time/Profiles/DefaultProfile.DAT"
	UE9QNEQAZQBmAGEAdQBsAHQAAAAhOFn3sPoCAAAAUgAAAFSwDt0AASADAABYAgAAIAAAAAEAAAAA
	AAAAAgAAAAIAAAACAAAAAgAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAAAAAAAA
	AAABAAAABAAAABoAAABSzYhDAAEAAIA/AACAPwAAgD8BAAAAAAAAAAAAAAA=
	_EOF_
else
	POL_SetupWindow_message "$(eval_gettext 'If you can barely distinguish a landscape behind main menu,\ndisable FOG in graphic options.')" "$TITLE"
fi

POL_SetupWindow_Close

exit
