#!/bin/bash
# Date : (2013-02-24 12-50)
# Last revision : (2013-03-24 15-47)
# Wine version used : 1.4-dos_support_0.6
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="pro_pinball_timeshock"
PREFIX="ProPinballTS_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.6"

TITLE="GOG.com - Pro Pinball Timeshock"
SHORTCUT_NAME="Pro Pinball Timeshock"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1589
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Cunning Developments / Strategy First" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "24c7fb588dc60edc8df168af45ac6e17"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

# "SVGA"?
POL_SetupWindow_VMS "2"

cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
dosbox_memsize=64
cpu_core=auto
cpu_cycles=max
mixer_rate=22050
mixer_prebuffer=10
sblaster_sbtype=sb16
sblaster_sbbase=220
sblaster_irq=5
sblaster_dma=1
sblaster_hdma=5
sblaster_mixer=true
sblaster_oplmode=auto
sblaster_oplrate=22050
gus_gus=false
_EOFCFG_

cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/autoexec.bat"
@ECHO OFF
imgmount D "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Pro Pinball - Timeshock/pptime.inst" -t iso
_EOFBAT_

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "SHOCK.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Pro Pinball - Timeshock/manual.pdf"
# C:\Program Files\GOG.com\Pro Pinball - Timeshock\README.TXT
# C:\Program Files\GOG.com\Pro Pinball - Timeshock\tech_manual.PDF

POL_SetupWindow_Close

exit 0
