#!/bin/bash
# Date : (2012-08-01 03-19)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="psychonauts"
PREFIX="Psychonauts_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="GOG.com - Psychonauts"
SHORTCUT_NAME="Psychonauts"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1340
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Double Fine Productions" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "6ba666fb42890dc271811243173b2c59" "562c61cfef74b76efba77e797e0ce920" "3ab364b4bc3a183da51b06db92c2a875"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Psychonauts.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Psychonauts/manual.pdf"
# C:\Program Files\GOG.com\Psychonauts\ReadMe.txt

POL_SetupWindow_Close

exit 0
