#!/bin/bash

# CHANGELOG
# [SuperPlumus] (2013-06-27 11-38)
#   Clean code
# [petch] (2013-07-13 08-00)
#   Update hash

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

TITLE="Publish or Perish"
PREFIX="PublishOrPerish"
WORKING_WINE_VERSION="1.2.3"

EDITEUR="Harzing.com"
EDITEUR_URL="http://www.harzing.com/"
POP_URL="http://www.harzing.com/download/PoPSetup.exe"
FILE="PoPSetup.exe"
EXECUTABLE="PoP.exe"
AUTEUR="Tinou"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "$EDITEUR" "$EDITEUR_URL" "$AUTEUR" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_System_TmpCreate "$PREFIX"

POL_Wine_InstallFonts
POL_Call POL_Install_LunaTheme

cd "$POL_System_TmpDir"

if [ "$POL_SELECTED_FILE" ]; then
    SetupFile="$POL_SELECTED_FILE"
else
    POL_SetupWindow_InstallMethod "LOCAL,DOWNLOAD"
    if [ "$INSTALL_METHOD" = "DOWNLOAD" ]; then
        POL_Download "$POP_URL" "1dee7016c3fe6260e8df5f5e638ed0ed"
        SetupFile="$POL_System_TmpDir/PoPSetup.exe"
    elif [ "$INSTALL_METHOD" = "LOCAL" ]; then
        POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run')" "$TITLE"
        SetupFile="$APP_ANSWER"
    fi
fi

POL_Wine_WaitBefore "$TITLE"
POL_Wine "$SetupFile"

POL_System_TmpDelete

POL_Shortcut "$EXECUTABLE" "$TITLE"

POL_SetupWindow_Close
exit 0
