#!/bin/bash
# Date : (2012-05-17 13-41)
# Last revision : (2013-12-27 23-59)
# Wine version used : 1.4-dos_support_0.6
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="realms_of_arkania_3"
PREFIX="RealmsOfArkania3_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.6"

TITLE="GOG.com - Realms of Arkania 3"
SHORTCUT_NAME="Realms of Arkania 3: Shadows Over Riva"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1206
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Attic Entertainment / Fantasy Productions" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "450277e2519da7baf8c3333de9af072c"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# "VGA"?
POL_SetupWindow_VMS "1"

# I am tempted to add render_aspect=true here, as some gfx (faces...) obviously
# have a wrong aspect; But fonts get less readable when enabled
cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
cpu_core=auto
cpu_cputype=auto
cpu_cycles='fixed 35000'
render_frameskip=1
mixer_rate=44100
mixer_blocksize=2048
mixer_prebuffer=80
sblaster_sbtype=sb16
sblaster_sbbase=220
sblaster_irq=7
sblaster_dma=1
sblaster_hdma=5
sblaster_mixer=true
sblaster_oplmode=auto
sblaster_oplrate=44100
_EOFCFG_
[ "$POL_OS" = "Linux" ] && echo "render_scaler=hq2x" >> "$WINEPREFIX/playonlinux_dos.cfg"

# Don't know why the cd is necessary, but it sucks
cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
@ECHO OFF
C:                                                                          
cd \GOGGAM~1\REALMS~1                                                       
imgmount D "$GOGROOT/Realms of Arkania 3/game.inst" -t iso -fs iso
_EOFAE_

POL_Shortcut "RIVA.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/Realms of Arkania 3/Manual.pdf"

POL_SetupWindow_Close

exit 0
