#!/bin/bash
# Date : (2012-10-27 22-51)
# Last revision : (2012-11-04 16-15)
# Wine version used : 1.4-dos_support_0.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="realms_of_arkania_1_2"
PREFIX="RealmsOfArkania1_2_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.5"

TITLE="GOG.com - Realms of Arkania 1 and 2"
SHORTCUT_NAME1="Realms of Arkania 1: Blade of Destiny"
SHORTCUT_NAME2="Realms of Arkania 2: Star Trail"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1455
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Attic Entertainment / Fantasy Productions" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "56021238f76fe4e2dd7014fa8adc40c5"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader, Foxit or SumatraPDF in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Realms of Arkania Pack" || POL_Debug_Fatal "Game not installed in standard path?"

# Problem with shortizing "Realms of Arkania 1" and "Realms of Arkania 2" subdirectories side-by-side :(
ROA1="ROA1"
ROA2="ROA2"
mv "Realms of Arkania 1" "$ROA1"
mv "Realms of Arkania 2" "$ROA2"

cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
dosbox_memsize=16
cpu_core=auto
cpu_cycles=max
sblaster_sbtype=sb16
sblaster_sbbase=220
sblaster_irq=5
sblaster_dma=1
sblaster_hdma=5
sblaster_mixer=true
sblaster_oplmode=auto
sblaster_oplrate=22050
_EOFCFG_
if [ "$POL_OS" = "Linux" ]; then
	# use pmidi -l or aconnect -o list to check your (emulated) midi device
	# 128:0 is just default software emulation port (usually Timidity)
	cat <<-'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
	render_scaler=hq2x
	midi_mididevice=alsa
	midi_midiconfig=128:0
	_EOFCFG_
fi
if [ "$POL_OS" = "Mac" ]; then
	cat <<-'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
	midi_mididevice=coreaudio
	_EOFCFG_
fi

cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Realms of Arkania Pack/$ROA1/ROA1.BAT"
@ECHO OFF
cls
intro
bladem
exit
_EOFBAT_

cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Realms of Arkania Pack/$ROA2/ROA2.BAT"
@ECHO OFF
cls
star
exit
_EOFBAT_

POL_Shortcut "ROA1.BAT" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Realms of Arkania Pack/$ROA1/passwords.pdf"
# C:\Program Files\GOG.com\Realms of Arkania Pack\$ROA1\MANUAL.PDF
# C:\Program Files\GOG.com\Realms of Arkania Pack\$ROA1\Cluebook.pdf

POL_Shortcut "ROA2.BAT" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Realms of Arkania Pack/$ROA2/passwords.pdf"
# C:\Program Files\GOG.com\Realms of Arkania Pack\$ROA2\Manual.pdf
# C:\Program Files\GOG.com\Realms of Arkania Pack\$ROA2\Cluebook.pdf

POL_SetupWindow_Close

exit
