#!/bin/bash
# Date : (2012-02-25 23-27)
# Last revision : (2012-05-24 19-41)
# Wine version used : 1.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="riven_the_sequel_to_myst"
PREFIX="Riven_gog"
WORKING_WINE_VERSION="1.4"

TITLE="Riven: The sequel to Myst (GoG release)"
SHORTCUT_NAME="Riven: The sequel to Myst"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Cyan Worlds / Cyan Inc" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "e261a0e2ffceddc04ff6917c94a64e57"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2" # "640x480 16bit"

# Doesn't hurt ;)
POL_Wine_reboot

# Icon from http://www.iconarchive.com/show/mega-games-pack-30-icons-by-3xhumed/Myst-Riven-1-icon.html
POL_Shortcut "Riven.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Riven/manual.pdf"

POL_SetupWindow_Close

exit
