#!/bin/bash
# Date : (2012-05-01 00-01)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="runaway_a_road_adventure"
PREFIX="Runaway_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Runaway: A Road Adventure"
SHORTCUT_NAME="Runaway: A Road Adventure"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1435
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Pendulo Studio / Focus Home Interactive" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "174444af2422d4375d8ea4f2f8d54cbd"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

# Expect an dialog box about missing WMP 5.2 at the very end of installation
POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# GoG work!
Set_OS winxp

# "1024x768 16bits color"
POL_SetupWindow_VMS "2"

# Without this, some sounds (car trunk slam for example) are missing
POL_Call POL_Install_dsound

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Runaway.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;AdventureGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Runaway - A Road Adventure/manual.pdf"
# C:\Program Files\GOG.com\Runaway - A Road Adventure\README.TXT

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Runaway - A Road Adventure/" || exit 1

TITLE="$TITLE"

POL_Debug_Init
POL_Wine "Video Card Setup.exe"

exit 0
_EOF_

# If the configurator was never launched, the game will call it... then crash
# Second time around will be ok, but better call it ourselves :p
bash "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"

exit 0
