#!/bin/bash
# Date : (2013-02-19 21-20)
# Last revision : (2013-02-23 19-29)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="runaway_3_a_twist_of_fate"
PREFIX="Runaway3_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Runaway 3: A Twist of Fate"
SHORTCUT_NAME="Runaway 3: A Twist of Fate"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1586
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Pendulo Studios / Focus Home Interactive" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "b26ead02ea1fe6a9fc46b4df949724c6" "c04025ca91431288949757bf0ddbe38a" "744566b0ea14fb4118d7308591fa78bf" "37b22d868c324886cba929bc0a4fe3e3"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "128"

POL_Call POL_Install_d3dx9_36

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "RATOF.exe" "$SHORTCUT_NAME" "" "" # "$SHORTCUT_NAME.png"
#echo "xrandr -s 0" >> "$POL_USER_ROOT/shortcuts/$SHORTCUT_NAME"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Runaway - A Twist Of Fate/manual.pdf"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Runaway - A Twist Of Fate/" || exit 1
TITLE="$TITLE"

POL_Debug_Init
POL_Wine "RATOF-Config.exe"
exit
_EOF_

exit
