#!/bin/bash
# Date : (2013-02-01 21-35)
# Last revision : (2013-02-03 04-31)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="silent_storm_gold"
PREFIX="SilentStorm_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - S2: Silent Storm Gold Edition"
SHORTCUT_NAME1="Silent Storm"
SHORTCUT_NAME2="Silent Storm Sentinels"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
#POL_SetupWindow_SetID ScriptIDNumber
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Nival Interactive" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "2801282a9356ae86cef9620abb95cd7c"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "game.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Silent Storm GOLD/Silent Storm/Manual.pdf"

POL_Shortcut "Sentinels.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Silent Storm GOLD/Silent Storm Sentinels/UserManual/index.html"

exit
