#!/bin/bash
# Date : (2012-05-10 12-39)
# Last revision : (2012-10-29 02-41)
# Wine version used : 1.5.3
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="sacred_gold"
PREFIX="Sacred_gog"
WORKING_WINE_VERSION="1.5.3"

TITLE="GOG.com - Sacred Gold"
SHORTCUT_NAME="Sacred Gold"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1177
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "ASCARON Entertainment / Strategy First" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "f8392a03dd78739ede7169ca77ddfd8d"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# Required for videos http://bugs.winehq.org/show_bug.cgi?id=16250
POL_Call POL_Install_devenum
POL_Call POL_Install_quartz
POL_Call POL_Install_amstream

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Sacred.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Sacred Gold/Manual.pdf"
# C:\Program Files\GOG.com\Sacred Gold\Readme.html
# C:\Program Files\GOG.com\Sacred Gold\Map.pdf
# C:\Program Files\GOG.com\Sacred Gold\Quickstart.pdf

# C:\Program Files\GOG.com\Sacred Gold\GameServer.exe

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Sacred Gold/" || exit 1

TITLE="$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_Wine --ignore-errors Config.exe

POL_SetupWindow_Close
exit
_EOF_

exit
