#!/bin/bash
# Date : (2012-12-29 22-49)
# Last revision : (2012-12-30 15-04)
# Wine version used : 1.5.15
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="sam_max_beyond_time_and_space"
PREFIX="SamAndMaxS2_gog"
WORKING_WINE_VERSION="1.5.15"

TITLE="GOG.com - GOG.com - Sam and Max: Beyond Time and Space"
SHORTCUT_NAME1="Sam and Max S2E1: Ice Station Santa"
SHORTCUT_NAME2="Sam and Max S2E2: Moai Better Blues"
SHORTCUT_NAME3="Sam and Max S2E3: Night of the Raving Dead"
SHORTCUT_NAME4="Sam and Max S2E4: Chariots of the Dogs"
SHORTCUT_NAME5="Sam and Max S2E5: What's New, Beelzebub"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1523
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Telltale Games" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "4ab26ab5f5450d361a238f89f23a8002"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_Install_d3dx9_36

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "SamMax201.exe" "$SHORTCUT_NAME1" "" "" # "$SHORTCUT_NAME1.png"
#POL_Shortcut_QuietDebug "$SHORTCUT_NAME1"
POL_Shortcut "SamMax202.exe" "$SHORTCUT_NAME2" "" "" # "$SHORTCUT_NAME2.png"
#POL_Shortcut_QuietDebug "$SHORTCUT_NAME2"
POL_Shortcut "SamMax203.exe" "$SHORTCUT_NAME3" "" "" # "$SHORTCUT_NAME3.png"
#POL_Shortcut_QuietDebug "$SHORTCUT_NAME3"
POL_Shortcut "SamMax204.exe" "$SHORTCUT_NAME4" "" "" # "$SHORTCUT_NAME4.png"
#POL_Shortcut_QuietDebug "$SHORTCUT_NAME4"
POL_Shortcut "SamMax205.exe" "$SHORTCUT_NAME5" "" "" # "$SHORTCUT_NAME5.png"
#POL_Shortcut_QuietDebug "$SHORTCUT_NAME5"

POL_SetupWindow_Close

exit 0
