#!/bin/bash
# Date : (2011-12-28 18-20)
# Last revision : (2012-01-29 17-19)
# Wine version used : 1.3.23
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archive:
# setup_sanitarium.exe 1235894636 "c60d04ddd0614988c7be7c86fa5fe7d8"

#    Lockup with 1.3.36 when reaching to top of the stairs
#    Same with 1.3.35
#    Same with 1.3.34
#    Same with 1.3.30
#    Crash with 1.3.29 when statue "lights up"
#    Heavy flickering with 1.3.27-rawinput2
#    Ok with 1.3.24?
#    Ok with 1.3.23?
#    Ok with 1.2.3?

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="Sanitarium_gog"
WORKING_WINE_VERSION="1.3.23"
INSTALLBIN="setup_sanitarium.exe"

TITLE="$(eval_gettext 'Sanitarium (GoG release)')"
URL="http://www.gog.com/en/gamecard/sanitarium"
SHORTCUT_NAME="Sanitarium"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "DreamForge Intertainment / XS Games" "$URL" "Pierre Etchemaite" "$PREFIX"

POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
[ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "$INSTALLBIN"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


Set_OS win98

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

SHORTCUT_WINDOW="$SHORTCUT_NAME $(eval_gettext '(windowed)')"
POL_Shortcut "sntrm.exe" "$SHORTCUT_NAME"
POL_Shortcut "sntrm.exe" "$SHORTCUT_WINDOW" "" "-w"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Sanitarium/manual.pdf"
POL_Shortcut_Document "$SHORTCUT_WINDOW" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Sanitarium/manual.pdf"

POL_SetupWindow_Close

exit
