#!/bin/bash
# Date : (2011-12-28 18-20)
# Last revision : (2012-05-24 20-02)
# Wine version used : 1.3.23
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

#    Lockup with 1.3.36 when reaching to top of the stairs
#    Same with 1.3.35
#    Same with 1.3.34
#    Same with 1.3.30
#    Crash with 1.3.29 when statue "lights up"
#    Heavy flickering with 1.3.27-rawinput2
#    Ok with 1.3.24?
#    Ok with 1.3.23?
#    Ok with 1.2.3?

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="sanitarium"
PREFIX="Sanitarium_gog"
WORKING_WINE_VERSION="1.3.23"

TITLE="Sanitarium (GoG release)"
SHORTCUT_NAME="Sanitarium"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "DreamForge Intertainment / XS Games" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "c60d04ddd0614988c7be7c86fa5fe7d8"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


Set_OS win98

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

SHORTCUT_WINDOW="$SHORTCUT_NAME $(eval_gettext '(windowed)')"
POL_Shortcut "sntrm.exe" "$SHORTCUT_NAME"
POL_Shortcut "sntrm.exe" "$SHORTCUT_WINDOW" "" "-w"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Sanitarium/manual.pdf"
POL_Shortcut_Document "$SHORTCUT_WINDOW" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Sanitarium/manual.pdf"

POL_SetupWindow_Close

exit
