#!/bin/bash
# Date : (2012-01-15 00-06)
# Last revision : (2012-09-23 19-03)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="septerra_core_legacy_of_the_creator"
PREFIX="SepterraCore_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="Septerra Core: Legacy of the Creator (GoG release)"
SHORTCUT_NAME="Septerra Core"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1041
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Valkyrie Studios / Topware Interactive" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "22839e19bc5c8db1e557810e01be6e42"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# http://www.playonlinux.com/en/issue-1029.html
POL_Wine_Direct3D "DirectDrawRenderer" "gdi"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "septerra.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
# sometimes exits with an exitcode of 1 for what it seems no good reason
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Septerra Core/Manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Septerra Core/README.TXT

POL_SetupWindow_Close

exit
