#!/bin/bash
# Date : (2012-11-18 14-37)
# Last revision : (2012-11-20 01-52)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="sherlock_holmes_secret_of_the_silver_earring"
PREFIX="SherlockHolmesSOTSE_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Sherlock Holmes: Secret of the Silver Earring"
SHORTCUT_NAME="Sherlock Holmes: Secret of the Silver Earring"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1471
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Frogwares" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "6f5936b89922ba7f2a08a149d41579cb"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "game.exe" "$SHORTCUT_NAME" "" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Sherlock Holmes - Secret of the Silver Earring/manual.pdf"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Sherlock Holmes - Secret of the Silver Earring/" || exit 1

TITLE="$TITLE"
POL_Debug_Init
POL_Wine setup.exe
exit 0
_EOF_

exit 0
