#!/bin/bash
# Date : (2013-04-01)
# Last Revision : (2013-11-23 02:44)
# Wine version used : 1.4.1
# Distribution used to test : Debian Wheezy (Testing repositories)
# Author : VisitntX visitntx@gmail.com
#   Updated : petch
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="shogo_mobile_armor_division"
PREFIX="ShogoMobileArmorDivision_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Shogo: Mobile Armor Division"
SHORTCUT_NAME="Shogo: Mobile Armor Division"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1819
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Monolith Productions / Interplay" "http://www.gog.com/en/gamecard/$GOGID" "VisitntX" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "ffb5e64a67fa6522013472e76738289a"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

 # fake sdbinst.exe
POL_Call POL_Install_nop "$WINEPREFIX/drive_c/windows/system32/sdbinst.exe"

POL_Call POL_GoG_install

# Setting Windows Version
Set_OS winxp

# Cleaning Wine by rebooting
POL_Wine_reboot

POL_Shortcut "Shogo.exe" "$SHORTCUT_NAME" "" "" "Game;ActionGame;" # "$SHORTCUT_NAME.png"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/Shogo - Mobile Armor Division/MANUAL.PDF"
# C:\GOG Games\Shogo - Mobile Armor Division\readme.txt
# C:\GOG Games\Shogo - Mobile Armor Division\shogo.hlp
# C:\GOG Games\Shogo - Mobile Armor Division\RefCard.pdf

POL_SetupWindow_Close

exit