#!/bin/bash
# Date : (2012-03-20 20-55)
# Last revision : (2012-03-20 21-56)
# Wine version used : 1.5.0
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_simon_the_sorcerer.exe 91153476 "298f453852f4b057e80e255ad713d32e"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="SimonTheSorcerer_gog"
WORKING_WINE_VERSION="1.5.0"
INSTALLBIN="setup_simon_the_sorcerer.exe"

TITLE="Simon the Sorcerer (GoG release)"
URL="http://www.gog.com/en/gamecard/simon_the_sorcerer"
SHORTCUT_NAME="Simon the Sorcerer"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Adventure Soft" "$URL" "Pierre Etchemaite" "$PREFIX"

POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
[ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "$INSTALLBIN"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_question "$(eval_gettext 'This game uses the ScummVM emulator, that also exists natively for Linux.\nUse native version when present?')" "$TITLE"
NATIVESCUMMVM=''
[ "$APP_ANSWER" = "TRUE" ] && NATIVESCUMMVM=1


POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

if cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Simon the Sorcerer/"; then
    # Create setup file for native ScummVM (translating paths)
    perl -ne 'chomp; 
	      if(/^(.*path)=(.*)/) { 
		my($setting, $path)=($1, $2); 
		my $unix_path=`winepath -u '"'"'$path'"'"'`; 
		chomp $unix_path; 
		print "$setting=$unix_path\n"; 
	      } 
	      else { 
		print "$_\n"; 
	      }' < simon1.ini > simon1-unix.ini
fi

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2" # 640x480x256

Set_Desktop "On" 640 480

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "scummvm.exe" "$SHORTCUT_NAME" "" '-c "C:\'"$PROGRAMFILES"'\GOG.com\Simon the Sorcerer\simon1.ini" simon1'
cp "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Simon the Sorcerer/game.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT_NAME"
if [ -n "$NATIVESCUMMVM" ]; then
    POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "shopt -s execfail"
    POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "exec scummvm -c '../simon1-unix.ini'"
fi
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Simon the Sorcerer/manual.pdf"
# C:\Program Files\GOG.com\Simon the Sorcerer\walkthrough.doc

POL_SetupWindow_Close

exit
