#!/bin/bash
# Date : (2012-05-22 22-47)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.4-scummvm_support
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="simon_the_sorcerer_2"
PREFIX="SimonTheSorcerer2_gog"
WORKING_WINE_VERSION="1.4-scummvm_support"

TITLE="GOG.com - Simon the Sorcerer 2"
SHORTCUT_NAME="Simon the Sorcerer 2"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1225
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Adventure Soft" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "b600e7eeff2f68b8f9d151b92af99a97"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_SetupWindow_VMS "2"

cat <<_EOFCFG_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Simon the Sorcerer 2/simon2.polcfg"
[simon2]
description=Simon the Sorcerer 2
mute=false
subtitles=false
gameid=simon2
language=en
guioptions=launchNoLoad
_EOFCFG_

POL_Shortcut "simon2.polcfg" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;AdventureGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Simon the Sorcerer 2/manual.pdf"

POL_SetupWindow_Close

exit 0
