#!/bin/bash
# Date : (2012-02-05 18-36)
# Last revision : (2012-05-21 20-08)
# Wine version used : 1.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Freeware
# Depend :

# Tested with install archives:
# TSR-SkiChallenge12.exe 71513656 "ca54f9f503159f933ac97ba123647cfb"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="SkiChallenge2012"
WORKING_WINE_VERSION="1.4"

TITLE="Ski Challenge 2012"
URL="http://www.skichallenge.ch/fr/"
SHORTCUT_NAME="Ski Challenge 12 (TSR)"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Greentube" "$URL" "Pierre Etchemaite" "$PREFIX"

if [ -n "$POL_SELECTED_FILE" ]; then
    ARCHIVE="$POL_SELECTED_FILE"
else
    cd "$POL_USER_ROOT/tmp"
    POL_Download "http://download.skichallenge.ch/SC12/installer/TSR-SkiChallenge12.exe" "5434f04497aa6e5376ac781e3c1040dc"
    ARCHIVE="$POL_USER_ROOT/tmp/TSR-SkiChallenge12.exe"
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

POL_Wine --ignore-errors "$ARCHIVE"
case "$?" in
    0|2)
        ;;
    *)
        POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"
        ;;
esac

POL_Wine_WaitExit "$TITLE"


POL_SetupWindow_VMS "128"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "updater.exe" "$SHORTCUT_NAME"
POL_ExtractIcon "$WINEPREFIX/drive_c/Games/Ski Challenge 12 (TSR)/Game.exe" "$POL_USER_ROOT/icones/32/$SHORTCUT_NAME"
POL_ExtractBiggestIcon "$WINEPREFIX/drive_c/Games/Ski Challenge 12 (TSR)/Game.exe" "$POL_USER_ROOT/icones/Full_size/$SHORTCUT_NAME"

POL_SetupWindow_Close

exit
