#!/bin/bash
# Date : (2012-12-07 09:00)
# Last revision : (2013-04-06 08:18)
# Wine version used : 1.5.27 (PlayOnLinux)
# Distribution used to test : Chakra Linux 2013.02 Claire x86-64
# Original Author : GNU_Raziel
# Updated Script Author : Valmar
# Licence : Retail
# Only For : http://www.playonlinux.com

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

TITLE="The Elder Scrolls V : Skyrim"
PREFIX="Skyrim"
EDITOR="Bethesda Softworks"
GAME_URL="http://www.elderscrolls.com/skyrim/"
AUTHOR="Valmar"
[ "$POL_OS" = "Linux" ] && WORKING_WINE_VERSION="1.5.27"
# PlayOnMac playability needs testing for Wine version 1.5.27...
[ "$POL_OS" = "Mac" ] && WORKING_WINE_VERSION="1.5.27"
GAME_VMS="512"
STEAM_ID="72850"

# Starting the script
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/Skyrim/top.jpg" "http://files.playonlinux.com/resources/setups/Skyrim/left.jpg" "$TITLE"
POL_SetupWindow_Init

# Starting debugging API
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"

# Setting prefix path
POL_Wine_SelectPrefix "$PREFIX"

# Downloading wine if necessary and creating prefix
POL_System_SetArch "x86" # For dotnet/mono
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Choose between DVD and Digital Download version
POL_SetupWindow_InstallMethod "DVD,STEAM"

# Fix pulseaudio issue
which pulseaudio && Set_OS "win7"

# Installing mandatory dependencies
POL_Call POL_Install_steam
POL_Call POL_Install_vcrun2008 # Fix game issue
POL_Call POL_Install_d3dx9 # Fix game crash

# Asking about memory size of graphic card
POL_SetupWindow_VMS $GAME_VMS

# Set Graphic Card information keys for wine
POL_Wine_SetVideoDriver

## Fix for this game
POL_Wine_X11Drv "GrabFullscreen" "Y"

# Increase performances
POL_Wine_Direct3D "UseGLSL" "disabled"

# Sound problem fix - pulseaudio related
[ "$POL_OS" = "Linux" ] && Set_SoundDriver "alsa"
[ "$POL_OS" = "Linux" ] && Set_SoundEmulDriver "Y"
## End Fix

# Mandatory pre-install fix for steam
POL_Call POL_Install_steam_flags "$STEAM_ID"

# Shortcut done before install for steam version
POL_Shortcut "steam.exe" "$TITLE" "$TITLE.png" "steam://rungameid/$STEAM_ID"
POL_Shortcut "steam.exe" "Steam ($TITLE)" "" ""

# Allow for steam to update it's files
cd "$WINEPREFIX/drive_c/$PROGRAMFILES/Steam"
POL_Wine start /unix "steam.exe"
POL_SetupWindow_message "$(eval_gettext 'Steam is about to perform an update. After Steam finishes updating and shows you to the login interface, login (or register if you do not have an Steam account) and then when you get to the main Steam interface, close COMPLETELY the Steam interface so that the installation script can continue.')" "$TITLE"

# Just in case this continues when Steam closes, --allow-kill is useful.
POL_Wine_WaitExit "$TITLE installation" --allow-kill

# Begin game installation
if [ "$INSTALL_METHOD" == "DVD" ]; then
	# Asking for CDROM and checking if it's correct one
	POL_SetupWindow_message "$(eval_gettext 'Please insert the game media into your disk drive')" "$TITLE"
	POL_SetupWindow_message "$(eval_gettext 'When $TITLE installation is finished, do NOT click on Play.\n\nClose COMPLETELY the Steam interface, \nso that the installation script can continue')" "$TITLE"
	POL_SetupWindow_cdrom
	POL_SetupWindow_check_cdrom "The Elder Scrolls V- Skyrim_disk1_0.sid"
	ln -s "$CDROM" s:
	cd "$WINEPREFIX/drive_c/$PROGRAMFILES/Steam"
	POL_Wine start /unix "Steam.exe" -install s:
	POL_Wine_WaitExit "$TITLE"
else
	# Steam install
	POL_SetupWindow_message "$(eval_gettext 'When $TITLE download by Steam is finished, do NOT click on Play.\n\nClose COMPLETELY the Steam interface, \nso that the installation script can continue')" "$TITLE"
	cd "$WINEPREFIX/drive_c/$PROGRAMFILES/Steam"
	POL_Wine start /unix "Steam.exe" steam://install/$STEAM_ID
	POL_Wine_WaitExit "$TITLE"
fi

POL_SetupWindow_message "$(eval_gettext 'If the game crashes at startup, open a terminal and type:\necho 0|sudo tee /proc/sys/kernel/yama/ptrace_scope')"
POL_SetupWindow_Close
exit 0