#!/bin/bash
# Date : (2012-06-23 11-41)
# Last revision : (2013-02-08 20-08)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="splinter_cell"
PREFIX="SplinterCell_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Splinter Cell"
SHORTCUT_NAME="Tom Clancy's Splinter Cell"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1272
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ubisoft Montréal / Ubisoft" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "64cd01d285907cb073474d566b2058da"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

cat <<_EOFFUNC_ > "$GOGROOT/Splinter Cell/system/splinter_funcs"

read_sc_settings () {
  [ -z "\$WINEPREFIX" ] && POL_Debug_Fatal 'read_sc_settings: \$WINEPREFIX must be set'
  perl -ne 'print "SCWIDTH=\$1\nSCHEIGHT=\$2\n" if /^Resolution=(\d+)x(\d+)/' "$GOGROOT/Splinter Cell/system/SplinterCellUser.ini"
}

sync_resolutions () {
  eval \$(read_sc_settings)
  # From what I've read game requires virtual desktop, but I can't really test
  Set_Desktop "On" "\$SCWIDTH" "\$SCHEIGHT"
}

_EOFFUNC_

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "SplinterCell.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'source "splinter_funcs"'
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'sync_resolutions'
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/Splinter Cell/Manual.pdf"
# C:\GOG Games\Splinter Cell\Readme.rtf
# C:\GOG Games\Splinter Cell\reference card.pdf

POL_SetupWindow_Close

exit 0
