#!/bin/bash
# Date : (2012-06-23 11-41)
# Last revision : (2012-10-29 02-47)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="splinter_cell"
PREFIX="SplinterCell_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="GOG.com - Splinter Cell"
SHORTCUT_NAME="Tom Clancy's Splinter Cell"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1272
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ubisoft Montréal / Ubisoft" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "378a1797c552a2e4345893eb1b5fbf50"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

cat <<_EOFFUNC_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Splinter Cell/system/splinter_funcs"

read_sc_settings () {
  [ -z "\$WINEPREFIX" ] && POL_Debug_Fatal 'read_sc_settings: \$WINEPREFIX must be set'
  perl -ne 'print "SCWIDTH=\$1\nSCHEIGHT=\$2\n" if /^Resolution=(\d+)x(\d+)/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Splinter Cell/system/SplinterCellUser.ini"
}

sync_resolutions () {
  eval \$(read_sc_settings)
  # From what I've read game requires virtual desktop, but I can't really test
  Set_Desktop "On" "\$SCWIDTH" "\$SCHEIGHT"
}

_EOFFUNC_

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "SplinterCell.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'source "splinter_funcs"'
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'sync_resolutions'
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Splinter Cell/Manual.pdf"
# C:\Program Files\GOG.com\Splinter Cell\Readme.rtf
# C:\Program Files\GOG.com\Splinter Cell\reference card.pdf

POL_SetupWindow_Close

exit
