#!/bin/bash
# Date : (2012-06-24 16-52)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="star_wolves"
PREFIX="StarWolves_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="GOG.com - Star Wolves"
SHORTCUT_NAME="Star Wolves"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1278
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "X-bow Software / 1C Publishing" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "bf212e844f791538696e8518bad5b7c8"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Only d3dx9_36 matters since 1.5.5
POL_Call POL_Install_d3dx9

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "StarWolves.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;StrategyGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Star Wolves/manual.pdf"

POL_SetupWindow_Close

exit 0
