#!/bin/bash
# Date : (2013-01-03 20-04)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.5.15
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Wine 1.4.1, 1.5.7: "Something very funny about your videocard"
# Wine 1.5.9: stopped responding when leaving game
# Wine 1.5.10, 1.5.11, 1.5.15: ok

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="startopia"
PREFIX="Startopia_gog"
WORKING_WINE_VERSION="1.5.15"

TITLE="GOG.com - Startopia"
SHORTCUT_NAME="Startopia"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1527
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Mucky Foot Productions / Square Enix" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "0dac024c52e483d4c6472fca33efd109"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

# Screen can be scrolled by moving the mouse to the borders
POL_Wine_X11Drv "GrabFullScreen" "Y"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "startopia.exe" "$SHORTCUT_NAME" "" "" "Game;StrategyGame;" # "$SHORTCUT_NAME.png"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/StarTopia/Manual.pdf"

POL_SetupWindow_Close

exit 0
