#!/bin/bash
# Date : (2011-12-01 22-38)
# Last revision : (2012-04-15 12-29)
# Wine version used : 1.4-dos_support
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend : dosbox

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="starflight_1_2"
PREFIX="Starflight_1_2_gog"
WORKING_WINE_VERSION="1.4-dos_support"

TITLE="Starflight 1 and 2 (GoG release)"
SHORTCUT1_NAME="Starflight 1"
SHORTCUT1_CODEWHEEL="$SHORTCUT1_NAME - $(eval_gettext 'Code wheel')"
SHORTCUT1_MAP="$SHORTCUT1_NAME - $(eval_gettext 'Stellar map')"
SHORTCUT2_NAME="Starflight 2"
SHORTCUT2_MAP="$SHORTCUT2_NAME - $(eval_gettext 'Stellar map')"

POL_SetupWindow_Init
POL_Debug_Init
POL_SetupWindow_presentation "$TITLE" "Binary Systems / Electronic Arts" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_setup "$GOGID" "4b3e884d1bbe066470338456991dc73e"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

# GoG work!
Set_OS winxp

# Doesn't hurt ;)
POL_Wine_reboot

# Create for Starflight 1 what has been done for Starflight 2: batch file to save/restore games
cp "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/MMAIN.EXE" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/STARFLT/PLAY/"
cp "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/DPUT.EXE" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/STARFLT/PLAY/"
cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/STARFLT/PLAY/sf1.bat"
@ECHO OFF

:MAIN
PAUSE
CLS
MMAIN.EXE
CLS
IF ERRORLEVEL 5 GOTO QUIT
IF ERRORLEVEL 4 GOTO DLETE
IF ERRORLEVEL 3 GOTO SAVE
IF ERRORLEVEL 2 GOTO PLAY
IF ERRORLEVEL 1 GOTO RSUME
IF ERRORLEVEL 0 GOTO PNEW




:DLETE
IF NOT EXISTS GAME.B* GOTO NOTEXIS
DIR GAME.B*
ECHO  Delete which saved game? (1-9)
ECHO  Press space the Enter to cancel

DPUT.EXE

IF ERRORLEVEL 9 GOTO CANCEL

IF NOT ERRORLEVEL 8 GOTO DEIGHT
IF EXISTS GAME.9SV DEL GAME.9SV
IF EXISTS GAME.B9 DEL GAME.B9
ECHO Game number 9 no longer exists...
GOTO MAIN

:DEIGHT
IF NOT ERRORLEVEL 7 GOTO DSEVEN
IF EXISTS GAME.8SV DEL GAME.8SV
IF EXISTS GAME.B8 DEL GAME.B8
ECHO Game number 8 no longer exists...
GOTO MAIN

:DSEVEN
IF NOT ERRORLEVEL 6 GOTO DSIX
IF EXISTS GAME.7SV DEL GAME.7SV
IF EXISTS GAME.B7 DEL GAME.B7
ECHO Game number 7 no longer exists...
GOTO MAIN

:DSIX
IF NOT ERRORLEVEL 5 GOTO DFIVE
IF EXISTS GAME.6SV DEL GAME.6SV
IF EXISTS GAME.B6 DEL GAME.B6
ECHO Game number 6 no longer exists...
GOTO MAIN

:DFIVE
IF NOT ERRORLEVEL 4 GOTO DFOUR
IF EXISTS GAME.5SV DEL GAME.5SV
IF EXISTS GAME.B5 DEL GAME.B5
ECHO Game number 5 no longer exists...
GOTO MAIN

:DFOUR
IF NOT ERRORLEVEL 3 GOTO DTHREE
IF EXISTS GAME.4SV DEL GAME.4SV
IF EXISTS GAME.B4 DEL GAME.B4
ECHO Game number 4 no longer exists...
GOTO MAIN

:DTHREE
IF NOT ERRORLEVEL 2 GOTO DTWO
IF EXISTS GAME.3SV DEL GAME.3SV
IF EXISTS GAME.B3 DEL GAME.B3
ECHO Game number 3 no longer exists...
GOTO MAIN

:DTWO
IF NOT ERRORLEVEL 1 GOTO DONE
IF EXISTS GAME.2SV DEL GAME.2SV
IF EXISTS GAME.B2 DEL GAME.B2
ECHO Game number 2 no longer exists...
GOTO MAIN

:DONE
IF EXISTS GAME.1SV DEL GAME.1SV
IF EXISTS GAME.B1 DEL GAME.B1
ECHO Game number 1 no longer exists...
GOTO MAIN




:RSUME
IF NOT EXIST LASTSAVE.SVA GOTO NOTEXIS
ECHO Copying LASTSAVE to current game
COPY LASTSAVE.SVA STARA.COM
COPY LASTSAVE.SVB STARB.COM
GOTO START




:PLAY
IF NOT EXISTS GAME.B* GOTO NOTEXIS
DIR GAME.B*
ECHO  Play which saved game? (1-9)
ECHO  Press space then Enter to cancel

DPUT.EXE

IF ERRORLEVEL 9 GOTO CANCEL

IF NOT ERRORLEVEL 8 GOTO EEIGHT
IF NOT EXISTS GAME.9SV GOTO NOTEXIS
COPY GAME.9SV STARA.COM
COPY GAME.B9 STARB.COM
ECHO Game 9 is now ready to be played
GOTO START

:EEIGHT
IF NOT ERRORLEVEL 7 GOTO ESEVEN
IF NOT EXISTS GAME.8SV GOTO NOTEXIS
COPY GAME.8SV STARA.COM
COPY GAME.B8 STARB.COM
ECHO Game 8 is now ready to be played
GOTO START

:ESEVEN
IF NOT ERRORLEVEL 6 GOTO ESIX
IF NOT EXISTS GAME.7SV GOTO NOTEXIS
COPY GAME.7SV STARA.COM
COPY GAME.B7 STARB.COM
ECHO Game 7 is now ready to be played
GOTO START

:ESIX
IF NOT ERRORLEVEL 5 GOTO EFIVE
IF NOT EXISTS GAME.6SV GOTO NOTEXIS
COPY GAME.6SV STARA.COM
COPY GAME.B6 STARB.COM
ECHO Game 6 is now ready to be played
GOTO START

:EFIVE
IF NOT ERRORLEVEL 4 GOTO EFOUR
IF NOT EXISTS GAME.5SV GOTO NOTEXIS
COPY GAME.5SV STARA.COM
COPY GAME.B5 STARB.COM
ECHO Game 5 is now ready to be played
GOTO START

:EFOUR
IF NOT ERRORLEVEL 3 GOTO ETHREE
IF NOT EXISTS GAME.4SV GOTO NOTEXIS
COPY GAME.4SV STARA.COM
COPY GAME.B4 STARB.COM
ECHO Game 4 is now ready to be played
GOTO START

:ETHREE
IF NOT ERRORLEVEL 2 GOTO ETWO
IF NOT EXISTS GAME.3SV GOTO NOTEXIS
COPY GAME.3SV STARA.COM
COPY GAME.B3 STARB.COM
ECHO Game 3 is now ready to be played
GOTO START

:ETWO
IF NOT ERRORLEVEL 1 GOTO EONE
IF NOT EXISTS GAME.2SV GOTO NOTEXIS
COPY GAME.2SV STARA.COM
COPY GAME.B2 STARB.COM
ECHO Game 2 is now ready to be played
GOTO START

:EONE
IF NOT EXISTS GAME.1SV GOTO NOTEXIS
COPY GAME.1SV STARA.COM
COPY GAME.B1 STARB.COM
ECHO Game 1 is now ready to be played
GOTO START




:START
ECHO Good luck!
CLS
STARFLT
REM IF SF1CHECK...
COPY STARA.COM LASTSAVE.SVA
COPY STARB.COM LASTSAVE.SVB
GOTO MAIN



:NOTEXIS
ECHO Either there are no saved games to delete/play
ECHO or you have chosen one that does not exist.
ECHO Please try another option.
GOTO MAIN




:SAVE
IF NOT EXIST LASTSAVE.SVA GOTO NOTEXIS


IF EXIST GAME.1* GOTO STWO
COPY LASTSAVE.SVA GAME.1SV
COPY LASTSAVE.SVN GAME.B1
ECHO Game saved as GAME.1SV
GOTO MAIN

:STWO
IF EXISTS GAME.2* GOTO STHREE
COPY LASTSAVE.SVA GAME.2SV
COPY LASTSAVE.SVN GAME.B2
ECHO Game saved as GAME.2SV
GOTO MAIN

:STHREE
IF EXISTS GAME.3* GOTO SFOUR
COPY LASTSAVE.SVA GAME.3SV
COPY LASTSAVE.SVN GAME.B3
ECHO Game saved as GAME.3SV
GOTO MAIN

:SFOUR
IF EXISTS GAME.4* GOTO SFIVE
COPY LASTSAVE.SVA GAME.4SV
COPY LASTSAVE.SVN GAME.B4
ECHO Game saved as GAME.4SV
GOTO MAIN

:SFIVE
IF EXISTS GAME.5* GOTO SSIX
COPY LASTSAVE.SVA GAME.5SV
COPY LASTSAVE.SVN GAME.B5
ECHO Game saved as GAME.5SV
GOTO MAIN

:SSIX
IF EXISTS GAME.6* GOTO SSEVEN
COPY LASTSAVE.SVA GAME.6SV
COPY LASTSAVE.SVN GAME.B6
ECHO Game saved as GAME.6SV
GOTO MAIN

:SSEVEN
IF EXISTS GAME.7* GOTO SEIGHT
COPY LASTSAVE.SVA GAME.7SV
COPY LASTSAVE.SVN GAME.B7
ECHO Game saved as GAME.7SV
GOTO MAIN

:SEIGHT
IF EXISTS GAME.8* GOTO SNINE
COPY LASTSAVE.SVA GAME.8SV
COPY LASTSAVE.SVN GAME.B8
ECHO Game saved as GAME.8SV
GOTO MAIN

:SNINE
IF EXISTS GAME.9* GOTO ALLFULL
COPY LASTSAVE.SVA GAME.9SV
COPY LASTSAVE.SVN GAME.B9
ECHO Game saved as GAME.9SV
GOTO MAIN



:ALLFULL
ECHO You have nine saved games.
ECHO You will have to delete a
ECHO game before you can save.
GOTO MAIN




:PNEW
ECHO Copying original files...
COPY ..\START\STARA.COM STARA.COM
COPY ..\START\STARB.COM STARB.COM
GOTO START




:CANCEL
ECHO Your request has been canceled
GOTO MAIN


:QUIT
ECHO See you again soon!
_EOFBAT_

cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/gfw_high.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT1_NAME"
POL_Shortcut "sf1.bat" "$SHORTCUT1_NAME"
POL_Shortcut_Document "$SHORTCUT1_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/manual.pdf"
# C:\Program Files\GOG.com\Starflight 1 and 2/Starflight 1/map.pdf

POL_Shortcut "Starflight_codes_by_gog.exe" "$SHORTCUT1_CODEWHEEL"

cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/gfw_high.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT2_NAME"
POL_Shortcut "sf2.bat" "$SHORTCUT2_NAME"
POL_Shortcut_Document "$SHORTCUT2_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/manual.pdf"
# C:\Program Files\GOG.com\Starflight 1 and 2\Starflight 2\map.pdf

POL_SetupWindow_Close

exit
