#!/bin/bash
# Date : (2011-12-01 22-38)
# Last revision : (2012-04-11 22-08)
# Wine version used : 1.3.23
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend : dosbox

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="starflight_1_2"
PREFIX="Starflight_1_2_gog"
WORKING_WINE_VERSION="1.3.23"
# GoG tools (graphic mode setup, code wheel work _almost_ ok with 1.3.23
# but are broken (controls don't react to clicks) with 1.3.33

TITLE="Starflight 1 and 2 (GoG release)"
SHORTCUT1_NAME="Starflight 1"
SHORTCUT1_CODEWHEEL="$SHORTCUT1_NAME - $(eval_gettext 'Code wheel')"
SHORTCUT1_MAP="$SHORTCUT1_NAME - $(eval_gettext 'Stellar map')"
SHORTCUT2_NAME="Starflight 2"
SHORTCUT2_MAP="$SHORTCUT2_NAME - $(eval_gettext 'Stellar map')"

POL_SetupWindow_Init
POL_Debug_Init
POL_SetupWindow_presentation "$TITLE" "Binary Systems / Electronic Arts" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_question "$(eval_gettext 'This game uses the DOSBox emulator, that also exists natively for Linux.\nUse native version when present? (Recommended)')" "$TITLE"
NATIVEDOSBOX=''
[ "$APP_ANSWER" = "TRUE" ] && NATIVEDOSBOX=1

# SF1 original interface for game backups involved DOS prompt, restoring this (almost: start in game however)
SF1DROPINCONSOLE=1

POL_Call POL_GoG_setup "$GOGID" "4b3e884d1bbe066470338456991dc73e"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

# GoG work!
Set_OS winxp

# Doesn't hurt ;)
POL_Wine_reboot

# Sadly, it seems GoG installer unpacks both games even if you only ask for 1
# So test below is uneffective and all shortcuts are always created
if [ -d "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1" ]; then
    # Better default settings in my opinion
    sed -i.orig -e 's/^output=.*/output=OpenGL/; s/^cycles=.*/cycles=auto/; s/^fullscreen=.*/fullscreen=false/; s/^scaler=.*/scaler=hq2x/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/dosboxSF1.conf"

    # GoG default
    DOSBOX_PARAMS='-conf dosboxSF1.conf -noconsole -c "exit"'
    if [ -n "$SF1DROPINCONSOLE" ]; then
        DOSBOX_PARAMS='-conf dosboxSF1.conf -noconsole'
        cat <<- _EOFINI_ > $POL_USER_ROOT/tmp/sf1dropinconsole.reg
	[HKEY_LOCAL_MACHINE\Software\GOG.com\GOGSTARFLIGHT1]
	"DOSBOXPARAM"="$DOSBOX_PARAMS"
	"LAUNCHCOMMAND"="\"C:\\Program Files\\GOG.com\\Starflight 1 and 2\\DOSBOX\\dosbox.exe\" $DOSBOX_PARAMS"
	_EOFINI_
        POL_Wine regedit $POL_USER_ROOT/tmp/sf1dropinconsole.reg
        rm $POL_USER_ROOT/tmp/sf1dropinconsole.reg
        sed -i -e 's/^exit.*/type HDNOTESA.TXT/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/dosboxSF1.conf"
    fi

    cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/gfw_high.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT1_NAME"
    POL_SetupWindow_make_shortcut "$PREFIX" "$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/" "C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/DOSBOX/DOSBox.exe" "" "$SHORTCUT1_NAME" "" "$DOSBOX_PARAMS"
    if [ -n "$NATIVEDOSBOX" ]; then
        # Thanks to exec, will only start W32 dosbox if native dosbox fails to start
        POL_Shortcut_InsertBeforeWine "$SHORTCUT1_NAME" "shopt -s execfail"
        POL_Shortcut_InsertBeforeWine "$SHORTCUT1_NAME" "exec dosbox $DOSBOX_PARAMS"
    fi
    POL_Shortcut_Document "$SHORTCUT1_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/manual.pdf"

    POL_Shortcut "Starflight_codes_by_gog.exe" "$SHORTCUT1_CODEWHEEL"

    POL_Shortcut "start.exe" "$SHORTCUT1_MAP" "" "'C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/map.pdf'"
fi

if [ -d "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2" ]; then
    # Better default settings in my opinion
    sed -i.orig -e 's/^output=.*/output=OpenGL/; s/^fullscreen=.*/fullscreen=false/; s/^scaler=.*/scaler=hq2x/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/dosboxSF2.conf"

    cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/gfw_high.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT2_NAME"
    POL_SetupWindow_make_shortcut "$PREFIX" "$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/" "C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/DOSBOX/DOSBox.exe" "" "$SHORTCUT2_NAME" "" "-conf dosboxSF2.conf -noconsole -c \"exit\""
    if [ -n "$NATIVEDOSBOX" ]; then
        # Thanks to exec, will only start W32 dosbox if native dosbox fails to start
        POL_Shortcut_InsertBeforeWine "$SHORTCUT2_NAME" "shopt -s execfail"
        POL_Shortcut_InsertBeforeWine "$SHORTCUT2_NAME" "exec dosbox -conf dosboxSF2.conf"
    fi
    POL_Shortcut_Document "$SHORTCUT2_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/manual.pdf"

    POL_Shortcut "start.exe" "$SHORTCUT2_MAP" "" "'C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/map.pdf'"
fi

POL_SetupWindow_Close

cat <<_EOF_ > $POL_USER_ROOT/configurations/configurators/"$SHORTCUT1_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/" || exit

if [ -n "$NATIVEDOSBOX" ]; then
    # Make sure that if user presses "start game", it will launch the right dosbox
    DOSBOX="`which dosbox`"
    if [ -n "\$DOSBOX" ]; then
	cat <<- _EOFINI_ > $POL_USER_ROOT/tmp/sf1nativedosbox.reg
	REGEDIT4

	[HKEY_LOCAL_MACHINE\Software\GOG.com\GOGSTARFLIGHT1]
	"LAUNCHCOMMAND"="\$DOSBOX -conf dosboxSF1.conf"
	_EOFINI_
        POL_Wine regedit $POL_USER_ROOT/tmp/sf1nativedosbox.reg
        rm $POL_USER_ROOT/tmp/sf1nativedosbox.reg
    fi
fi

POL_Wine "Graphic mode setup.exe" "GOGSTARFLIGHT1"
exit
_EOF_

cat <<_EOF_ > $POL_USER_ROOT/configurations/configurators/"$SHORTCUT2_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/" || exit

if [ -n "$NATIVEDOSBOX" ]; then
    # Make sure that if user presses "start game", it will launch the right dosbox
    DOSBOX="`which dosbox`"
    if [ -n "\$DOSBOX" ]; then
	cat <<- _EOFINI_ > $POL_USER_ROOT/tmp/sf2nativedosbox.reg
	REGEDIT4

	[HKEY_LOCAL_MACHINE\Software\GOG.com\GOGSTARFLIGHT2]
	"LAUNCHCOMMAND"="\$DOSBOX -conf dosboxSF2.conf"
	_EOFINI_
        POL_Wine regedit $POL_USER_ROOT/tmp/sf2nativedosbox.reg
        rm $POL_USER_ROOT/tmp/sf2nativedosbox.reg
    fi
fi

POL_Wine "Graphic mode setup.exe" "GOGSTARFLIGHT2"
exit
_EOF_

exit
