#!/bin/bash
# Date : (2013-05-27 22-00)
# Last revision : (2013-06-29 14-43)
# Wine version used : 1.4.1
# Distribution used to test : Fedora 17, Debian Sid
# Author : TonyFlow
#   updated petch
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="stronghold"
PREFIX="Stronghold_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Stronghold HD"
SHORTCUT_NAME="Stronghold HD"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1721
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "FireFly Studios" "http://www.gog.com/gamecard/$GOGID" "TonyFlow" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" --alternate "setup_$GOGID" "1" "feefadb14ccf00c0a95a39add4da5ae9"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

# Doesnt hurt ;)
POL_Wine_reboot

# Language selection for the manual shortcut
POL_SetupWindow_menu "$(eval_gettext 'What is your preferred language?')" "$(eval_gettext 'Language')" "en: English~fr: French~de: German~it: Italian~es: Spanish" "~"
MAN_LANG=$(echo "${APP_ANSWER}" | cut -d ':' -f 1)

# Configure the shortcut
GOGPATH="$GOGROOT/Stronghold HD"
POL_Shortcut "Stronghold.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;StrategyGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGPATH/manual/manual_$MAN_LANG.pdf"

# Language pack installation
POL_SetupWindow_menu "$(eval_gettext 'Do you have a language pack to install?')" "$(eval_gettext 'Language')" "$(eval_gettext 'Yes')~$(eval_gettext 'No')~$(eval_gettext 'Later')" "~"
if [ "$APP_ANSWER" = "$(eval_gettext 'Yes')" ]; then
	POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run')" "$(eval_gettext 'Language')"
	[ -z "$APP_ANSWER" ] || POL_Wine "$APP_ANSWER"
elif [ "$APP_ANSWER" = "$(eval_gettext 'Later')" ]; then
	POL_SetupWindow_message "$(eval_gettext 'To install a language pack later, open the configuration panel for the game in order to execute the installer into the virtual disk (Misc tab)')" "$(eval_gettext 'Language')"
fi

POL_SetupWindow_Close
exit 0
