#!/bin/bash
# Date : (2013-05-27 22-00)
# Last revision : (2013-12-29 11-28)
# Wine version used : 1.4.1
# Distribution used to test : Fedora 17, Debian Sid
# Author : TonyFlow
#   updated petch
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="stronghold"
PREFIX="Stronghold_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Stronghold HD"
SHORTCUT_NAME="Stronghold HD"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1721
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "FireFly Studios" "http://www.gog.com/gamecard/$GOGID" "TonyFlow" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" --alternate "setup_$GOGID" "2" "a26178ebca7865949d2458818464cd4e"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

# Doesnt hurt ;)
POL_Wine_reboot

# Language selection for the manual shortcut
POL_SetupWindow_menu "$(eval_gettext 'What is your preferred language?')" "$(eval_gettext 'Language')" "en: English~fr: French~de: German~it: Italian~es: Spanish" "~"
MAN_LANG=$(echo "${APP_ANSWER}" | cut -d ':' -f 1)

# Configure the shortcut
GOGPATH="$GOGROOT/Stronghold HD"
POL_Shortcut "Stronghold.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;StrategyGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGPATH/manual/manual_$MAN_LANG.pdf"

POL_SetupWindow_Close
exit 0
