#!/bin/bash
# Date : (2012-05-07 22-36)
# Last revision : (2012-05-08 21-40)
# Wine version used : 1.5.3
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="syberia"
PREFIX="Syberia_gog"
WORKING_WINE_VERSION="1.5.3"

TITLE="Syberia (GoG release)"
SHORTCUT_NAME="Syberia"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Microids / Anuman Interactive" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "6be725a60617364ed4b28f80469cfb4a" "bb213cbae9f2cc4db7823748e9e79784" "53b640d49726551690df9516dafb96e9"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

POL_Call POL_Install_vcrun6

cd "$POL_USER_ROOT/tmp"
POL_Download "http://www.nirsoft.net/utils/nircmd.zip" "3d6d3f094633c5c97f8b15f8fe1023bf"
POL_System_ExtractSingleFile "nircmd.zip" "nircmd.exe" "$WINEPREFIX/drive_c/windows/nircmd.exe"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Syberia.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
# double quotes around "P"OL_Wine prevent args detection to pickup this line, sorry for the hack
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" '(sleep 10; "P"OL_Wine nircmd.exe win hide title Syberia; "P"OL_Wine nircmd.exe win hideshow title Syberia)&'
echo "wait" >> "$POL_USER_ROOT/shortcuts/$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Syberia/Manual.pdf"
# C:\Program Files\GOG.com\Syberia\ReadMe.txt

POL_SetupWindow_Close

exit
