#!/bin/bash
# Date : (2012-05-27 21-44)
# Last revision : (2012-10-29 02-49)
# Wine version used : 1.5.3
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="syberia_2"
PREFIX="Syberia2_gog"
WORKING_WINE_VERSION="1.5.3"

TITLE="GOG.com - Syberia 2"
SHORTCUT_NAME="Syberia 2"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1232
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Microids / Anuman Interactive" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "648155959d414865e123c9e8d1c5f516"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

POL_Call POL_Install_vcrun6

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Syberia2.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Syberia2/Manual.pdf"
# C:\Program Files\GOG.com\Syberia 2\ReadMe.txt
# C:\Program Files\GOG.com\Syberia 2\Walkthrough.pdf

POL_SetupWindow_Close

exit 0
