#!/bin/bash
# Date : (2013-01-30 19-01)
# Last revision : (2013-01-30 20-50)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="tales_of_monkey_island"
PREFIX="TalesOfMonkeyIsland_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - Tales of Monkey Island"
SHORTCUT_NAME1="ToMI S1E1: Launch of the Screaming Narwhal"
SHORTCUT_NAME2="ToMI S1E2: The Siege of Spinner Cay"
SHORTCUT_NAME3="ToMI S1E3: Lair of the Leviathan"
SHORTCUT_NAME4="ToMI S1E4: The Trial and Execution of Guybrush Threepwood"
SHORTCUT_NAME5="ToMI S1E5: Rise of the Pirate God"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
#POL_SetupWindow_SetID ScriptIDNumber
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Telltale Games" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "0ee725e1a4a576d7ed481889ff85b30f"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_Call POL_Install_d3dx9_36

POL_SetupWindow_VMS "64"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "MonkeyIsland101.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME1"

POL_Shortcut "MonkeyIsland102.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME2"

POL_Shortcut "MonkeyIsland103.exe" "$SHORTCUT_NAME3" "$SHORTCUT_NAME3.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME3"

POL_Shortcut "MonkeyIsland104.exe" "$SHORTCUT_NAME4" "$SHORTCUT_NAME4.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME4"

POL_Shortcut "MonkeyIsland105.exe" "$SHORTCUT_NAME5" "$SHORTCUT_NAME5.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME5"

POL_SetupWindow_Close

exit
