#!/bin/bash
# Date : (2012-01-16 20-04)
# Last revision : (2012-09-23 19-21)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Freeware
# Depend :

# Tested with install archives:
# 2011_12_19_Circle_of_Eight_Modpack_7.0.0_Setup.exe 144230937 "f5794aaf9e6be982757f4e4f3ad66afe"
# and
# Circle_of_Eight_Modpack_7.0.0_NC_Setup.exe 295527044 "d8046e6174c4d6eb9a4c5e958b691963"

# Got a crash with 1.3.37, backoff to 1.3.36

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

# Must match templeofelementalevil-gog script values
TITLE_REQUIRED="The Temple of Elemental Evil (GoG release)"
PREFIX="TempleElementalEvil_gog"
WORKING_WINE_VERSION="1.3.36"
INSTALLBIN="Circle_of_Eight_Modpack_7.0.0_NC_Setup.exe"

DOWNLOAD_URL="http://www.moddb.com/mods/circle-of-eight-modpack/news/circle-of-eight-modpacks-700-and-700-nc-released"

TITLE="Temple of Elemental Evil: Circle of Eight Modpack 7"
SHORTCUT_NAME="Temple of Elemental Evil - Circle of Eight Modpack 7"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1064
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Circle of Eight" "http://www.co8.org/" "Pierre Etchemaite" "$PREFIX"

if [ "$(POL_Wine_PrefixExists $PREFIX)" != "True" ]; then
    POL_Debug_Fatal "$(eval_gettext 'Please install $TITLE_REQUIRED first')"
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_AutoSetVersionEnv
POL_LoadVar_PROGRAMFILES

if [ -n "$POL_SELECTED_FILE" ]; then
    ARCHIVE="$POL_SELECTED_FILE"
else
    POL_SetupWindow_question "$(eval_gettext 'You can download the archive file from:')\n$DOWNLOAD_URL\n$(eval_gettext 'Go there now?')" "$TITLE"
    [ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$DOWNLOAD_URL"

    cd $HOME
    POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" ""
    ARCHIVE="$APP_ANSWER"
fi

POL_Call POL_Install_mono28

POL_SetupWindow_message "$(eval_gettext 'Now you must install the modpack in directory:')\nC:\\$PROGRAMFILES\\GOG.com\\Temple of Elemental Evil\\" "$TITLE"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

POL_Wine "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

POL_Shortcut "TFE-X.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""

POL_SetupWindow_Close

exit
