#!/bin/bash
# Date : (2012-01-15 23-29)
# Last revision : (2012-04-19 00-47)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Got a crash with 1.3.37, backoff to 1.3.36; But could be random crashes

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_temple_of_elemental_evil"
PREFIX="TempleElementalEvil_gog"
WORKING_WINE_VERSION="1.3.36"

TITLE="The Temple of Elemental Evil (GoG release)"
SHORTCUT_NAME="Temple of Elemental Evil"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Troika Games / Atari" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "a2f9ee737fd040028585bc24c270e86a"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# According to AppDB it doesn't work without virtual desktop
# I have multiscreen so I can't test without it to confirm it's necessary
Set_Desktop "On" "800" "600"

# Doesn't hurt ;)
POL_Wine_reboot

cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Temple of Elemental Evil/ToEE.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT_NAME"
POL_Shortcut "ToEE.exe" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Temple of Elemental Evil/Manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Temple of Elemental Evil/Readme.txt

# Last words
POL_SetupWindow_message "$(eval_gettext 'It is highly recommended to now install the Circle of Eight Modpack\nto fix many issues with this game, and optionally add new content\n(for "NC" modpacks).\nUse the dedicated PlayOnLinux script in patches section.')" "$TITLE"

POL_SetupWindow_Close

exit
