#!/bin/bash
# Date : (2012-01-15 23-29)
# Last revision : (2012-01-15 23-59)
# Wine version used : 1.3.37
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_temple_of_elemental_evil.exe 1223704982 "a2f9ee737fd040028585bc24c270e86a"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="TempleElementalEvil_gog"
WORKING_WINE_VERSION="1.3.37"

TITLE="$(eval_gettext 'The Temple of Elemental Evil (GoG release)')"
SHORTCUT_NAME="Temple of Elemental Evil"
SHORTCUT_DOC="$SHORTCUT_NAME - $(eval_gettext 'User manual')"
SHORTCUT_README="$SHORTCUT_NAME - $(eval_gettext 'Readme')"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Troika Games / Atari" "http://www.gog.com/en/gamecard/the_temple_of_elemental_evil" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "setup_temple_of_elemental_evil.exe"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

POL_Call POL_Function_SetNativeExtension "pdf"
POL_Call POL_Function_SetNativeExtension "txt"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

# According to AppDB it doesn't work without virtual desktop
# I have multiscreen so I can't test without it to confirm it's necessary
Set_Desktop "On" "800" "600"

# Doesn't hurt ;)
POL_Wine_reboot

cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Temple of Elemental Evil/ToEE.ico" "$REPERTOIRE/icones/32/$SHORTCUT_NAME"
POL_Shortcut "ToEE.exe" "$SHORTCUT_NAME"
POL_Shortcut "start.exe" "$SHORTCUT_DOC" "" "'C:/$PROGRAMFILES/GOG.com/Temple of Elemental Evil/Manual.pdf'"
POL_Shortcut "start.exe" "$SHORTCUT_README" "" "'C:/$PROGRAMFILES/GOG.com/Temple of Elemental Evil/Readme.txt'"

POL_SetupWindow_Close

exit
