#!/bin/bash
# Date : (2012-07-21 11-57)
# Last revision : (2012-10-29 02-51)
# Wine version used : 1.4-dos_support_0.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="tex_murphy_the_pandora_directive"
PREFIX="TexMurphyTPD_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.5"

TITLE="GOG.com - Tex Murphy: The Pandora Directive"
SHORTCUT_NAME="Tex Murphy: The Pandora Directive"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1328
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Access Software / Worldplay LLC" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "bd943dac3ecd79d6911b9dd77d7551a5" "5af0cd2331d7a0c8e33093b7043e0215" "8f4fe1610daed1db85e8a536b90ddd70"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cd "$POL_USER_ROOT/tmp" || POL_Debug_Fatal 'Temporary directory not found!'
POL_Download "http://files.playonlinux.com/empty.iso.gz" "ba835afa9c5b7d0202bc595ed0231275"
zcat empty.iso.gz > "$WINEPREFIX/drive_c/empty.iso"

cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
dosbox_memsize=16
cpu_core=auto
cpu_cycles=max
mixer_rate=22050
mixer_blocksize=2048
mixer_prebuffer=10
sblaster_sbtype=sb16
sblaster_sbbase=220
sblaster_irq=5
sblaster_dma=1
sblaster_hdma=5
sblaster_mixer=true
sblaster_oplmode=auto
sblaster_oplrate=22050
_EOFCFG_
if [ "$POL_OS" = "Linux" ]; then
	# use pmidi -l or aconnect -o list to check your (emulated) midi device
	# 128:0 is just default software emulation port (usually Timidity)
	cat <<-'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
	render_scaler=hq2x
	midi_mididevice=alsa
	midi_midiconfig=128:0
	_EOFCFG_
fi
if [ "$POL_OS" = "Mac" ]; then
	cat <<-'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
	midi_mididevice=coreaudio
	_EOFCFG_
fi

cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
imgmount D "$WINEPREFIX/drive_c/empty.iso" -t iso
set dos4gvm=
_EOFAE_

POL_Shortcut "TEX4.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Pandora Directive/README.TXT"

POL_SetupWindow_Close

exit
