#!/bin/bash
# Date : (2012-05-15 21-41)
# Last revision : (2013-03-24 15-47)
# Wine version used : 1.4-dos_support_0.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="tex_murphy_under_a_killing_moon"
PREFIX="TexMurphyUAKM_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.5"

TITLE="GOG.com - Tex Murphy: Under a Killing Moon"
SHORTCUT_NAME="Tex Murphy: Under a Killing Moon"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1199
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Access Software / Wordplay LLC" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "b1e8f6362681abb0d9bbed1a325a0f7d"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# "SVGA"
POL_SetupWindow_VMS "1"

cat <<_EOFCFG_ > "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
dosbox_memsize=16
cpu_core=auto
cpu_cycles=max

sblaster_sbtype=sb16
sblaster_sbbase=220
sblaster_irq=5
sblaster_dma=1
sblaster_hdma=5
sblaster_mixer=true
sblaster_oplmode=auto
sblaster_oplrate=22050
_EOFCFG_
[ "$POL_OS" = "Linux" ] && echo "render_scaler=hq2x" >> "$WINEPREFIX/playonlinux_dos.cfg"

cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
imgmount F "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Under a Killing Moon/UAKM1.gog" -t iso
imgmount G "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Under a Killing Moon/UAKM2.gog" -t iso
imgmount H "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Under a Killing Moon/UAKM3.gog" -t iso
imgmount I "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Under a Killing Moon/UAKM4.gog" -t iso
_EOFAE_

POL_Shortcut "TEX197.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Under a Killing Moon/manual.pdf"
# C:\Program Files\GOG.com\Under a Killing Moon\README.TXT
# C:\Program Files\GOG.com\Under a Killing Moon\Solution.pdf

POL_SetupWindow_Close

exit 0
