#!/usr/bin/env playonlinux-bash
# Date : (2012-07-11 21-56)
# Last revision : (2014-05-11 10-13)
# Wine version used : 1.4.1, 1.6.2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_whispered_world"
PREFIX="WhisperedWorld_gog"
WORKING_WINE_VERSION="1.6.2"

TITLE="GOG.com - The Whispered World"
SHORTCUT_NAME="The Whispered World"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1309
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Daedalic Entertainment" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "0e4ca91315d3c6c354f93bc02237987b" "97b85af764360970cd9bee1571ac4ad6" "b3b1d06a73c62510e9b687ff8f4a8885"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "TWW.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;AdventureGame;"
# See: http://wiki.winehq.org/Sound ("SDL applications").
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'unset SDL_AUDIODIVER'
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/The Whispered World/documents/Manual.pdf"
# TWWOptions.exe only allows fullscreen/windowed setting, not worth using as configurator

POL_SetupWindow_Close

exit 0
