#!/bin/bash
# Date : (2012-11-25 17:56)
# Last revision : (2013-11-10 22-07)
# Wine version used : 1.4.1, 1.5.5
# Distribution used to test : OpenSuSE 12.2 64-bit
# Author : hmdai (Based on Deponia DC script by Kweepeer)
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_book_of_unwritten_tales"
PREFIX="TheBookofUnwrittenTales_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="GOG.com - The Book of Unwritten Tales"
SHORTCUT_NAME="The Book of Unwritten Tales"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/bout_64x64.png" "http://files.playonlinux.com/resources/setups/$PREFIX/bout_left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1488
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "King Art/Nordic Games" "http://www.gog.com/gamecard/$GOGID" "hmdai" "$PREFIX"
POL_Call POL_GoG_setup "$GOGID" "ae8210bf659d372ed4b26e447d78aab3" "4ea0eccb7ca2f77c301e79412ff1e214" "95e52d38b6c1548ac311284c539a4c52" "badc51c03e52268d8e94fbe6aadbbbac"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "128"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "bout.exe" "$SHORTCUT_NAME" "" "" "Game;AdventureGame;"

POL_SetupWindow_Close
exit0