#!/bin/bash
# Date : (2012-11-24 21:30)
# Last revision : (2013-12-20 23-29)
# Wine version used : 1.5.5, 1.6.1, 1.7.8
# Distribution used to test : OpenSuSE 12.2 64-bit
# Author : hmdai (Based on Deponia DC script by Kweepeer)
#   Update: petch
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_dark_eye_chains_of_satinav"
PREFIX="TheDarkEyeChainofSatinav_gog"
WORKING_WINE_VERSION="1.7.8"

TITLE="GOG.com - The Dark Eye: Chain of Satinav"
SHORTCUT_NAME="The Dark Eye: Chain of Satinav"

POL_GetSetupImages "" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1478
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Daedalic Entertainment" "http://www.gog.com/gamecard/$GOGID" "hmdai" "$PREFIX"
POL_Call POL_GoG_setup "$GOGID" "d1c375ba007b7ed6574a16cca823258a" "0c9ea69bdb3e2c66d13f2d27812279b6" "d87f0693751554c1d382f770202e8c45" "ef662b59635829ed4505f6d7272e4bb7" "555d8af3bb598ed4c481e3e3d63b0221"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install "/nogui"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "128"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "satinav.exe" "$SHORTCUT_NAME" "" "" "Game;AdventureGame;"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'unset SDL_AUDIODRIVER'

# Create a tmp directory for the game to create thumbnail image for save game
mkdir "$WINEPREFIX/drive_c/tmp"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

cd "$GOGROOT/The Dark Eye - Chains of Satinav/" || exit 1

POL_Wine "VisionaireConfigurationTool.exe"
exit 0
_EOF_

exit 0