#!/bin/bash
# Date : (2012-01-06 21-20)
# Last revision : (2012-05-28 11-19)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_feeble_files"
PREFIX="FeebleFiles_gog"
WORKING_WINE_VERSION="1.3.36"

TITLE="The Feeble Files (GoG release)"
SHORTCUT_NAME="The Feeble Files"

POL_SetupWindow_Init
# 4.0.15 needed for complex POL_Shortcut_InsertBeforeWine
POL_RequiredVersion "4.0.15" || POL_Debug_Fatal "$APPLICATION_TITLE 4.0.15 is required to install $TITLE"

POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Adventure Soft" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "16f0ec3760c68d646abc6671f657361a" "df8a0031ac21f2efe93da1440d0fb024" "27197e9622d4ee349a8f4766f949426b"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# GoG work!
Set_OS winxp

# "SVGA videocard" (?)
POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "scummvm.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" '-c "C:\'"$PROGRAMFILES"'\GOG.com\The Feeble Files\feeble.ini"'
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Feeble Files/manual.pdf"

POL_SetupWindow_Close

exit
