#!/bin/bash
# Date : (2012-01-06 21-20)
# Last revision : (2013-11-17 22-04)
# Wine version used : 1.4-scummvm_support
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_feeble_files"
PREFIX="FeebleFiles_gog"
WORKING_WINE_VERSION="1.4-scummvm_support"

TITLE="GOG.com - The Feeble Files"
SHORTCUT_NAME="The Feeble Files"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1034
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Adventure Soft" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "5d687266db960a09886c76ff34388288" "2cfdbdbaf61663967d6748530d648337" "b622b451b73e4a8ed899253d575668dc"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


cat <<_EOFCFG_ > "$GOGROOT/The Feeble Files/feeble.polcfg"
[feeble]
description=The Feeble Files
platform=windows
gameid=feeble
language=en
_EOFCFG_

POL_Shortcut "feeble.polcfg" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;AdventureGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$GOGROOT/The Feeble Files/manual.pdf"

POL_SetupWindow_Close

exit 0
