#!/bin/bash
# Date : (2012-05-13 10-53)
# Last revision : (2012-05-24 19-59)
# Wine version used : 1.4-dos_support_0.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_incredible_machine_mega_pack"
PREFIX="TheIncredibleMachine_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.4"

TITLE="The Incredible Machine Mega Pack (GoG release)"
SHORTCUT_NAME1="TIM - Even More Incredible Machine"
SHORTCUT_NAME2="TIM - The Incredible Machine 3"
SHORTCUT_NAME3="TIM - Return of the Incredible Machine Contraptions"
SHORTCUT_NAME4="TIM - Even More Contraptions"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Dynamix / Playdom" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "021e9371ce23f438315eb26c079c1c95"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cat <<_EOFCFG_ > "$WINEPREFIX/playonlinux_dos.cfg"
dosbox_memsize=16
cpu_core=auto
cpu_cycles=8000
_EOFCFG_

cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Incredible Machine Series/The Even More Incredible Machine/EVEN.BAT"
@ECHO OFF
cls
Echo -------------------------------------------
Echo   Please select ANY 3 icons when prompted.
Echo -------------------------------------------
pause
TIM.EXE
EXIT
_EOFBAT_

# GoG work!
Set_OS winxp

# "800x600 16-bit color"
POL_SetupWindow_VMS "1"

# Otherwise both "Even More Contraptions" and "Return of Incredible Machine Contraptions" crashes
POL_Wine_Direct3D "DirectDrawRenderer" "gdi"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "EVEN.BAT" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut "TIMWIN.EXE" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""
POL_Shortcut "Contraptions.exe" "$SHORTCUT_NAME3" "$SHORTCUT_NAME3.png" ""
POL_Shortcut "EvenMore.exe" "$SHORTCUT_NAME4" "$SHORTCUT_NAME4.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME4"
POL_Shortcut_Document "$SHORTCUT_NAME4" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Incredible Machine Series/The Incredible Machine - Even More Contraptions/readme.txt"

POL_SetupWindow_Close

exit
