#!/bin/bash
# Date : (2013-01-21 19-45)
# Last revision : (2013-01-23 21-41)
# Wine version used : 1.5.8
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Wine 1.4.1, 1.5.7: Unimplemented function msvcp90.dll.??0?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@H@Z (after introduction)
# Wine 1.5.8: starts ok

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="interstate76"
PREFIX="Interstate76_gog"
WORKING_WINE_VERSION="1.5.8"

TITLE="GOG.com - The Interstate '76 Arsenal"
SHORTCUT_NAME1="Interstate '76"
SHORTCUT_NAME2="Interstate '76 Nitro Pack"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
#POL_SetupWindow_SetID ScriptIDNumber
# For POL_Wine_UpdateRegistryWinePair
POL_RequiredVersion "4.0.16" || POL_Debug_Fatal "$APPLICATION_TITLE 4.0.16 is required to install $TITLE"
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Activision" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "9df956a4eb54278cc5e54a9bb2974248"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


Set_OS winxp
POL_Wine_UpdateRegistryWinePair 'AppDefaults\i76.exe' "Version" "win98"
POL_Wine_UpdateRegistryWinePair 'AppDefaults\nitro.exe' "Version" "win98"

POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "i76.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" "-glide"
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Interstate 76 Arsenal/Manual.pdf"

POL_Shortcut "nitro.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" "-glide"

POL_SetupWindow_Close

exit
