#!/bin/bash
# Date : (2012-01-04 23-55)
# Last revision : (2012-04-14 17-17)
# Wine version used : 1.4-dos_support
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="last_express_the"
PREFIX="LastExpress_gog"
WORKING_WINE_VERSION="1.4-dos_support"

TITLE="The Last Express (GoG release)"
SHORTCUT_NAME="The Last Express"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Smoking Car Productions / Phoenix Licensing" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_setup "$GOGID" "fa23dcee7dc701d8d33f12d3037433e8"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2"

cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
mount D "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Last Express/data" -t cdrom
_EOFAE_

# Doesn't hurt ;)
POL_Wine_reboot

cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Last Express/gfw_high.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT_NAME"
POL_Shortcut "EXPRESS.EXE" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Last Express/Manual.pdf"
# C:/$PROGRAMFILES/GOG.com/The Last Express/Readme.txt

POL_SetupWindow_Close

exit
