#!/bin/bash
# Date : (2012-01-04 23-55)
# Last revision : (2012-09-23 19-12)
# Wine version used : 1.4-dos_support_0.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="last_express_the"
PREFIX="LastExpress_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.5"

TITLE="The Last Express (GoG release)"
SHORTCUT_NAME="The Last Express"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1125
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Smoking Car Productions / Phoenix Licensing" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "fa23dcee7dc701d8d33f12d3037433e8"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cat <<'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
cpu_cycles='max 95% limit 33000'
manual_mount=true
_EOFCFG_
[ "$POL_OS" = "Linux" ] && echo "render_scaler=hq2x" >> "$WINEPREFIX/playonlinux_dos.cfg"

# Use drives from W downward
cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
mount W "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Last Express/data" -t cdrom
_EOFAE_

POL_Shortcut "EXPRESS.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Last Express/Manual.pdf"
# C:/$PROGRAMFILES/GOG.com/The Last Express/Readme.txt

POL_SetupWindow_Close

exit
