#!/bin/bash
# Date : (2012-05-03 22-02)
# Last revision : (2012-06-06 21-04)
# Wine version used : 1.4-dos_support_0.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="theme_hospital"
PREFIX="ThemeHospital_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.5"

TITLE="Theme Hospital (GoG release)"
SHORTCUT_NAME="Theme Hospital"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Bullfrog Productions / Electronic Arts" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "d79126b277bc155b5acee2822f4203b5"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# "640x480 256 colors"
POL_SetupWindow_VMS "2"

cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
cpu_core=auto
cpu_cputype=auto
cpu_cycles=auto
mixer_rate=44100
mixer_prebuffer=50
sblaster_oplmode=auto
sblaster_oplemu=default
#sblaster_oplrate=44100
ipx_enable=1
ipx_connection=1
ipx_ipx=true

speaker_pcspeaker=false
speaker_tandy=off
speaker_disney=false
joystick_joysticktype=none
midi_mpu401=none
gus_gus=false
_EOFCFG_

# Set real install path
cat <<'_EOFCFG_' | perl -pe 's/\n/\r\n/' > "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Theme Hospital/HOSPITAL.CFG"
INSTALL_PATH=c:\PROGRA~1\GOG.COM\THEMEH~1\
INSTALL_TYPE=MAX
LANGUAGE=ENG
_EOFCFG_

POL_Shortcut "HOSPITAL.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Theme Hospital/manual.pdf"

POL_SetupWindow_Close

exit
