#!/bin/bash
# Date : (2012-02-19 00-28)
# Last revision : (2012-11-29 23-48)
# Wine version used : 1.5.18
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_witcher"
PREFIX="TheWitcher_gog"
WORKING_WINE_VERSION="1.5.18"

TITLE="GOG.com - The Witcher Enhanced Edition Directors Cut"
SHORTCUT_NAME="The Witcher Enhanced Edition DC"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1065
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "CD Projekt RED" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "94e42a8fb9d5c44e37a0d98eed6babc9" "77f181c95623b3d304bbf1f1ca374a43" "fd00e3930cd203523a2fcd11b3db6d70" "2ea8bdfe6a2904ab8b36e1c7280a6f10" "7257321819069f62b4b2aea7c6185bcb" "29fef08cd064226d202524c01ab2c00d" "13d1655e95bb6831d07a8a0ef6599cc2"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Default interface leaks winprocs and crashes under Wine
POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_Call POL_install_d3dx9_36
POL_Call POL_install_d3dx9_43

POL_SetupWindow_VMS "128"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "launcher.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/The Witcher Enhanced Edition Directors Cut/manual.pdf"
# C:\GOG Games\The Witcher Enhanced Edition Directors Cut\readme.rtf

POL_SetupWindow_Close

exit 0
