#!/bin/bash
# Date : (2012-02-19 00-28)
# Last revision : (2013-11-30 20-48)
# Wine version used : 1.5.18, 1.6.1, 1.7.6
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# 1.6.x better performance
# 1.7.x health gauge
# 1.7.0-1.7.5 no music

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_witcher"
PREFIX="TheWitcher_gog"
WORKING_WINE_VERSION="1.7.6"

TITLE="GOG.com - The Witcher Enhanced Edition Directors Cut"
SHORTCUT_NAME="The Witcher Enhanced Edition DC"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1065
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "CD Projekt RED" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "517bee649628c9ac7e6df95866ddf962" "776f4f60b03c182bbd99a7e6a250b40a" "90d8d89af1f51ba772aefa8c688d56ec" "6dda80674754ec37d2fb85f253d22731" "9bec98fbd429d085b05bfe73aad966a9" "d5bf259be43de9e7358cc3d5e3fcc2ef" "6df62216833975f1b73590705a6bcd5c"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Default interface leaks winprocs and crashes under Wine
POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

# Fix black screen
POL_Call POL_install_d3dx9_36
# Fix large dark polygons, (in rain and more)
POL_Call POL_install_d3dx9_43

POL_SetupWindow_VMS "128"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "launcher.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/The Witcher Enhanced Edition Director's Cut/manual.pdf"
# C:\GOG Games\The Witcher Enhanced Edition Director's Cut\readme.rtf

POL_SetupWindow_Close

exit 0
