#!/bin/bash
# Date : (2012-09-08 10-59)
# Last revision : (2012-09-23 19-15)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="total_annihilation_kingdoms"
PREFIX="TotalAnnihilationKingdoms_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="Total Annihilation - Kingdoms (GoG release)"
SHORTCUT_NAME="Total Annihilation: Kingdoms"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1391
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Cavedog Entertainment / Atari" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "3045c36f91696ea3a5c2f9c7ad0d93de"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

Set_Desktop "On" "640" "480"
POL_Wine_X11Drv "GrabFullScreen" "Y"

# GoG work!
Set_OS winxp

# "SVGA"?
POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Kingdoms.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Total Annihilation Kingdoms/Manual.pdf"
# C:\Program Files\GOG.com\Total Annihilation Kingdoms\ReadMe.txt
# C:\Program Files\GOG.com\Total Annihilation Kingdoms\atlas\index.html
# C:\Program Files\GOG.com\Total Annihilation Kingdoms\readme.htm
# C:\Program Files\GOG.com\Total Annihilation Kingdoms\Cartographer.exe

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Total Annihilation Kingdoms/" || exit 1
TITLE="$TITLE"
POL_Debug_Init
POL_Wine ChooseRenderer.exe
exit
_EOF_

exit
