#!/bin/bash
# Date : (2011-12-09 20-31)
# Last revision : (2012-03-25 17-12)
# Wine version used : 1.3.36
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_two_worlds.exe 2314533 f59283baad1d482806a4302c6a105c66
# setup_two_worlds-1.bin 2097685248 d0eab18be86037476a7cd4e47f1afc0a
# setup_two_worlds-2.bin 1716047202 eb19df7336379a5b1355354ed69f124e

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="2Worlds_gog"
WORKING_WINE_VERSION="1.3.36"
INSTALLBIN="setup_two_worlds.exe"

TITLE="Two Worlds: Epic Edition (GoG release)"
URL="http://www.gog.com/en/gamecard/two_worlds"
SHORTCUT_NAME="Two worlds"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Reality Pump Studios / Topware Interactive" "$URL" "Pierre Etchemaite" "$PREFIX"

if [ -z "$POL_SELECTED_FILE" ]; then
    POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
    [ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

if [ -n "$POL_SELECTED_FILE" ]; then
    ARCHIVE="$POL_SELECTED_FILE"
else
    cd $HOME
    POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "$INSTALLBIN"
    ARCHIVE="$APP_ANSWER"
fi

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


#POL_Call POL_Install_dsound
POL_Call POL_Install_devenum
POL_Call POL_Install_quartz
POL_Call POL_Install_xact
POL_Call POL_Install_d3dx9
POL_Call POL_Install_wmp10

# WMV9AP VC-1 Codec
cd "$POL_USER_ROOT/tmp/" || POL_Debug_Fatal "$(eval_gettext 'temp directory missing')"
POL_Download 'http://www-pc.uni-regensburg.de/systemsw/WinMedia/wvc1dmo.exe' "cbbfea5937bebcc8ebf2ff6abfc050bd"
POL_Wine wvc1dmo.exe /C /Q '/T:C:\windows\temp'
cp "$WINEPREFIX/drive_c/windows/temp/wvc1dmod.dll" "$WINEPREFIX/drive_c/windows/system32"
POL_Wine regsvr32 wvc1dmod.dll

# Untested
#POL_Call POL_Install_directplay

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "128"

#POL_Wine_X11Drv "DXGrab" "Y"
POL_Wine_X11Drv "GrabFullScreen" "Y"

POL_Wine_DirectSound "DefaultSampleRate" "48000"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "TwoWorlds.exe" "$SHORTCUT_NAME"
POL_Shortcut "TwoWorlds_RADEON.exe" "$SHORTCUT_NAME (Radeon)"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Two Worlds/Manual.pdf"
POL_Shortcut_Document "$SHORTCUT_NAME (Radeon)" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Two Worlds/Manual.pdf"

POL_SetupWindow_question "$(eval_gettext 'Two Worlds Control Panel is a tool from InsideTwoWorlds community,\nthat allows you to tweak parameters and manage mods\nfor this game. See\nhttp://www.insidetwoworlds.com/local_links.php?linkid=21&catid=13 for details.\nInstall it?')" "$TITLE"
if [ "$APP_ANSWER" = "TRUE" ]; then
  cd "$POL_USER_ROOT/tmp/" 
  POL_Download 'http://www.insidetwoworlds.com/local_links.php?s=d92f024673ebf64a34a7b47675963c70&action=jump&catid=13&id=21' "d41d8cd98f00b204e9800998ecf8427e"
  mv local_links.php TwoWorldsCP107.zip
  unzip TwoWorldsCP107.zip TwoWorldsCP.exe
  POL_Wine_InstallFonts
  POL_Call POL_Install_dotnet20
  POL_Wine TwoWorldsCP.exe
  if [ $? -eq 0 ]; then
    # CP needs that weird path ending to find TW correctly!
    cat <<'_EOFINI_' > "$POL_USER_ROOT/tmp/fixtw1path.reg"
REGEDIT4

[HKEY_LOCAL_MACHINE\Software\Reality Pump\TwoWorlds\FileSystem]
"DataPath"="C:\\Program Files\\GOG.com\\Two Worlds/>"
"OutputDir"="C:\\Program Files\\GOG.com\\Two Worlds"
_EOFINI_
    POL_Wine regedit "$POL_USER_ROOT/tmp/fixtw1path.reg"
    rm "$POL_USER_ROOT/tmp/fixtw1path.reg"

    # On my computer, subpixel aa makes CP fonts look like crap @96dpi,
    # and "ok" @100dpi...
    cat <<'_EOFINI_' > "$POL_USER_ROOT/tmp/100dpi.reg"
REGEDIT4

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Hardware Profiles\Current\Software\Fonts]
"LogPixels"=dword:00000064
_EOFINI_
    POL_Wine regedit "$POL_USER_ROOT/tmp/100dpi.reg"
    rm "$POL_USER_ROOT/tmp/100dpi.reg"

    # Create a shortcut, since the CP behaves more like a launcher than a
    # configurator
    POL_Shortcut "TwoWorldsCP.exe" "$SHORTCUT_NAME - $(eval_gettext 'Control Panel')"
  fi
fi

POL_SetupWindow_Close

exit
