#!/bin/bash
# Date : (2013-05-08 21-02)
# Last revision : (2013-05-18 21-21)
# Wine version used : 1.4-dos_support_0.6
# Distribution used to test : Xubuntu 12.10
# Author : Pascal Reinhard dev@ovocean.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="ultima_8_gold_edition"
PREFIX="Ultima8_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.6"

TITLE="GOG.com - Ultima 8"
SHORTCUT_NAME="Ultima 8: Pagan"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1684
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Origin Systems / Electronic Arts" "http://www.gog.com/gamecard/$GOGID" "Pascal Reinhard" "$PREFIX"

# Language choice
POL_SetupWindow_menu "Choose the game's language" "Language" "English-German-French" "-"
U8LANGUAGE=$APP_ANSWER

# Country code
U8LANG="en"
[ "$U8LANGUAGE" = "German" ] && U8LANG="de"
[ "$U8LANGUAGE" = "French" ] && U8LANG="fr"

POL_Call POL_GoG_setup "$GOGID" "379e4ad340f878d2288080191231e9c9"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Message about hand-picking the language
if [ "$U8LANG" != "en" ]
then
    POL_SetupWindow_message "$(eval_gettext 'IMPORTANT: 
    \n\nOn the installation window coming next, do NOT click the Options button, it would mess up the language selection.')" "$(eval_gettext 'Language selection')"
fi

POL_Call POL_GoG_install

# Dosbox config
cat <<_EOFCFG_ >> "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
sdl_output=overlay
render_aspect=true
render_scaler=normal2x
cpu_cycleup=1000
cpu_cycledown=1000
mixer_prebuffer=50
sblaster_sbtype=sbpro1
sblaster_sbbase=220
sblaster_irq=5
sblaster_dma=1
speaker_pcspeaker=false
speaker_tandy=off
speaker_disney=false
gus_gus=false
dos_keyboardlayout=$U8LANG
_EOFCFG_
if [ "$POL_OS" = "Linux" ]; then
	# use pmidi -l or aconnect -o list to check your (emulated) midi device
	# 128:0 is just the default software emulation port (usually Timidity)
	cat <<-'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
	midi_mididevice=alsa
	midi_midiconfig=128:0
	_EOFCFG_
fi
if [ "$POL_OS" = "Mac" ]; then
	cat <<-'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
	midi_mididevice=coreaudio
	_EOFCFG_
fi

cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
mount D "$WINEPREFIX/drive_c/GOG Games/Ultima VIII - Pagan/$U8LANGUAGE"
_EOFAE_

cat <<_EOFBAT_ > "$WINEPREFIX/drive_c/Ultima8.bat"
@ECHO OFF
D:
U8.EXE
EXIT
_EOFBAT_

POL_Shortcut "Ultima8.bat" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/Ultima VIII - Pagan/$U8LANGUAGE/manual.pdf"

# Warning about MIDI music
if [ "$POL_OS" = "Linux" ]
then
    POL_SetupWindow_message "$(eval_gettext '$SHORTCUT_NAME is successfully installed.\n\nNote that the game may lack music. If so, it may be that you need to install a MIDI synthesizer, as your Linux distribution doesn'"'"'t have one installed by default. Seek for help online if you don'"'"'t know how to do this. In general you will want to install TiMidity++.')" "$(eval_gettext 'Final notes')"
fi

POL_SetupWindow_Close

exit 0