#!/bin/bash
# Date : (2012-08-25 18-58)
# Last revision : (2012-08-25 21-18)
# Wine version used : 1.5.11
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="unreal_2_the_awakening_se"
PREFIX="Unreal2_gog"
WORKING_WINE_VERSION="1.5.11"

TITLE="Unreal 2 - The Awakening SE (GoG release)"
SHORTCUT_NAME="Unreal 2: The Awakening"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
# 4.0.15 needed for complex POL_Shortcut_InsertBeforeWine
POL_RequiredVersion "4.0.15" || POL_Debug_Fatal "$APPLICATION_TITLE 4.0.15 is required to install $TITLE"
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Epic Games" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "c3533fb12a6ddbbd213c2a5ca2a13f65"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

POL_Wine_DirectInput "MouseWarpOverride" "force"

# Workaround
cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Unreal 2 – The Awakening SE/Music" || POL_Debug_Fatal "Couldn't find music directory"
mkdir -p disabled
mv *.con disabled

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Unreal2.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'taskset -pc 0 $$'
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Unreal 2 – The Awakening SE/Help/Manual.pdf"
# C:\Program Files\GOG.com\Unreal 2 – The Awakening SE\Help/Readme.txt

POL_SetupWindow_Close

exit
