#!/bin/bash
# Date : (2012-07-29 16-18)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="unreal_gold"
PREFIX="UnrealGold_gog"
WORKING_WINE_VERSION="1.5.5"
PATCH_ARCHIVE="OMP-UGOLD-V0.2.zip"

TITLE="GOG.com - Unreal Gold"
SHORTCUT_NAME="Unreal Gold"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1335
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Epic Games" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "7a270229d28a44089030150bd9f3a1e1"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cd "$POL_USER_ROOT/tmp" || POL_Debug_Fatal "Can't find temp directory!"

# Update and enable OpenGL driver
# Taken from http://www.oldunreal.com/specialpatches.html
POL_Download "http://files.playonlinux.com/$PATCH_ARCHIVE" "455dc59d939cff53cf3c28b9d7dbc87d"

POL_System_ExtractSingleFile "$PATCH_ARCHIVE" "OpenGLDrv.dll" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Unreal Gold/System/OpenGlDrv.dll"
POL_System_ExtractSingleFile "$PATCH_ARCHIVE" "OpenGlDrv.int" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Unreal Gold/System/OpenGlDrv.int"
POL_System_ExtractSingleFile "$PATCH_ARCHIVE" "Unreal.exe" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Unreal Gold/System/Unreal.exe"
POL_System_ExtractSingleFile "$PATCH_ARCHIVE" "UCC.exe" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Unreal Gold/System/UCC.exe"
POL_System_ExtractSingleFile "$PATCH_ARCHIVE" "Setup.exe" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Unreal Gold/System/Setup.exe"
#perl -i.bak -pe 's/^GameRenderDevice=[0-9A-Za-z.]*/GameRenderDevice=OpenGLDrv.OpenGLRenderDevice/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Unreal Gold/System/Unreal.ini"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Unreal.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Unreal Gold/Manual/Manual.pdf"
# C:\Program Files\GOG.com\Unreal Gold\Help\ReadMe.txt

POL_SetupWindow_message "$(eval_gettext 'On first run the game will autodetect available renderers.\nIt is likely that you will get better performance out of the OpenGL renderer.')" "$TITLE"

POL_SetupWindow_Close

exit 0
