#!/bin/bash
# Date : (2012-09-22 22-30)
# Last revision : (2012-09-23 10-09)
# Wine version used : 1.5.13
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="wallace_gromits_grand_adventures"
PREFIX="WallaceAndGromitGA_gog"
WORKING_WINE_VERSION="1.5.13"

TITLE="Wallace and Gromit's Grand Adventures (GoG release)"
SHORTCUT_NAME1="Wallace and Gromit EP101: Fright of the Bumblebees"
SHORTCUT_NAME2="Wallace and Gromit EP102: The Last Resort"
SHORTCUT_NAME3="Wallace and Gromit EP103: Muzzled"
SHORTCUT_NAME4="Wallace and Gromit EP104: The Bogey Man"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Telltale Games" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "b840f0cbca364999a65c384ce76ef8a1"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

POL_Call POL_Install_d3dx9_36

# Doesn't hurt ;)
POL_Wine_reboot

qwertyze () {
    # backup keyboard layout, switch to qwerty, then restore after game
    local SHORTCUT="$1"
    POL_Shortcut_InsertBeforeWine "$SHORTCUT" 'KLB="$POL_USER_ROOT/tmp/keyboard_layout-$$.backup"'
    POL_Shortcut_InsertBeforeWine "$SHORTCUT" 'setxkbmap -print > "$KLB"'
    POL_Shortcut_InsertBeforeWine "$SHORTCUT" 'setxkbmap us'
    echo 'xkbcomp - $DISPLAY < "$KLB"' >> "$POL_USER_ROOT/shortcuts/$SHORTCUT"
}

POL_Shortcut "WallaceGromit101.exe" "$SHORTCUT_NAME1" "" "" # $SHORTCUT_NAME1.png
qwertyze "$SHORTCUT_NAME1"
POL_Shortcut "WallaceGromit102.exe" "$SHORTCUT_NAME2" "" "" # $SHORTCUT_NAME2.png
qwertyze "$SHORTCUT_NAME2"
POL_Shortcut "WallaceGromit103.exe" "$SHORTCUT_NAME3" "" "" # $SHORTCUT_NAME3.png
qwertyze "$SHORTCUT_NAME3"
POL_Shortcut "WallaceGromit104.exe" "$SHORTCUT_NAME4" "" "" # $SHORTCUT_NAME4.png
qwertyze "$SHORTCUT_NAME4"

POL_SetupWindow_Close

for SHORTCUT in "$SHORTCUT_NAME1" "$SHORTCUT_NAME2" "$SHORTCUT_NAME3" "$SHORTCUT_NAME4"; do
    cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Wallace and Gromits Grand Adventures/" || exit 1

TITLE="$TITLE"
POL_Debug_Init
POL_Wine Language.exe
exit
_EOF_
done

exit
