#!/bin/bash
# Date : (2012-09-29 03-54)
# Last revision : (2012-09-29 12-51)
# Wine version used : 1.4.1
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="zeus_poseidon"
PREFIX="ZeusAndPoseidon_gog"
WORKING_WINE_VERSION="1.4.1"

TITLE="Zeus + Poseidon (GoG release)"
SHORTCUT_NAME="Zeus + Poseidon"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
#POL_SetupWindow_SetID XXXX
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Impressions Games / Activision" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "b0b7d8f0a65f64be5a93af49a538fd7a"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Zeus.exe" "$SHORTCUT_NAME" "" "" # "$SHORTCUT_NAME.png"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Zeus and Poseidon/Zeus - Manual.pdf"
# C:\Program Files\GOG.com\Zeus and Poseidon\Zeus - Quick Reference Card.pdf
# C:\Program Files\GOG.com\Zeus and Poseidon\Zeus - Poseidon - Manual.pdf
# C:\Program Files\GOG.com\Zeus and Poseidon\Zeus - Adventure_Editor - Manual.pdf
# C:\Program Files\GOG.com\Zeus and Poseidon\Zeus - Poseidon - Adventure_Editor - Manual.pdf
# C:\Program Files\GOG.com\Zeus and Poseidon\Readme.txt
# C:\Program Files\GOG.com\Zeus and Poseidon\Zeus_editor.txt

POL_SetupWindow_Close

exit
