#!/bin/bash
# Date : (2012-02-03 22-01)
# Last revision : (2012-02-03 22-49)
# Wine version used : 1.4-rc2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archives:
# setup_broken_sword_4.exe 2322487 "04286672cfe5a99ec65e04d35d9e0b8c"
# setup_broken_sword_4-1.bin 2097677056 "54f55cedc88e3ca94f81b99c102f6cf6"
# setup_broken_sword_4-2.bin 1004600524 "259e76b3604e0ef871647093f8a0fb64"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="BrokenSword4_gog"
WORKING_WINE_VERSION="1.4-rc2"
INSTALLBIN="setup_broken_sword_4.exe"

TITLE="$(eval_gettext 'Broken Sword IV: The Angel of Death (GoG release)')"
URL="http://www.gog.com/en/gamecard/broken_sword_4"
SHORTCUT_NAME="Broken Sword 4: The Angel of Death (Secrets of the Ark)"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Revolution Software" "$URL" "Pierre Etchemaite" "$PREFIX"

POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
[ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "$INSTALLBIN"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"


# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "bs4pc.exe" "$SHORTCUT_NAME"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'schedtool -a 0x1 $$'

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Broken Sword - The Angel of Death/manual.pdf"

POL_SetupWindow_Close

exit
