#!/bin/bash
# Date : (2012-02-03 22-01)
# Last revision : (2012-06-03 23-28)
# Wine version used : 1.5.3
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="broken_sword_4"
PREFIX="BrokenSword4_gog"
WORKING_WINE_VERSION="1.5.3"

TITLE="Broken Sword IV: The Angel of Death (GoG release)"
SHORTCUT_NAME="Broken Sword 4: The Angel of Death (Secrets of the Ark)"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Revolution Software" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "04286672cfe5a99ec65e04d35d9e0b8c" "54f55cedc88e3ca94f81b99c102f6cf6" "259e76b3604e0ef871647093f8a0fb64"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"


# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "bs4pc.exe" "$SHORTCUT_NAME"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'taskset -c 0 -p $$'

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Broken Sword - The Angel of Death/manual.pdf"

POL_SetupWindow_Close

exit
