#!/bin/bash
# Date : (2011-12-14 02-03)
# Last revision : (2012-01-29 01-07)
# Wine version used : 1.3.34
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archive:
# setup_empire_earth_gold.exe 564162686 "1d5c5587ab26488b3a38f1ba288ce89a"

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="EmpireEarth_gog"
WORKING_WINE_VERSION="1.3.34"

TITLE="$(eval_gettext 'Empire Earth: Gold Edition (GoG release)')"
SHORTCUT_NAME1="Empire Earth"
SHORTCUT_NAME2="Empire Earth: The Art of Conquest"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Stainless Steel Studios / Rebellion" "http://www.gog.com/en/gamecard/empire_earth_gold_edition" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "setup_empire_earth_gold.exe"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

POL_Call POL_install_d3dx9
POL_Call POL_install_directmusic
POL_Call POL_install_vcrun6

cat <<_EOFINI_ > "$POL_USER_ROOT/tmp/disable_directmusic.reg"
REGEDIT4

[HKEY_CURRENT_USER\Software\SSSI\Empire Earth]
"Music Enabled"=dword:00000000
_EOFINI_
POL_Wine regedit "$POL_USER_ROOT/tmp/disable_directmusic.reg"
rm "$POL_USER_ROOT/tmp/disable_directmusic.reg"

# GoG work!?
Set_OS win2k

POL_SetupWindow_VMS "4"

POL_Wine_X11Drv "DXGrab" "Y"
POL_Wine_X11Drv "GrabFullScreen" "Y"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Empire Earth.exe" "$SHORTCUT_NAME1"
#POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME1" "POL_Wine_AutoSetVersionEnv"
#POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME1" "wineserver -k"
#POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME1" "nice -19 wineserver"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME1" "xset m 1 1"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME1" "trap 'xset m default' EXIT"

POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth/Manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth/technology_tree.pdf
# C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth/scenario_editor_manual.pdf

POL_Shortcut "EE-AOC.exe" "$SHORTCUT_NAME2"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME2" "POL_Wine_AutoSetVersionEnv"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME2" "wineserver -k"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME2" "nice -19 wineserver"

POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth - The Art of Conquest/manual_aoc.pdf"
# C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth - The Art of Conquest/readme.txt
# C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth - The Art of Conquest/technology_tree_aoc.pdf

POL_SetupWindow_Close
exit
