#!/bin/bash
# Date : (2012-07-23 19-46)
# Last revision : (2013-07-10 13-29)
# Wine version used : 1.5.8
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="the_witcher_2"
PREFIX="TheWitcher2_gog"
WORKING_WINE_VERSION="1.5.8"

TITLE="GOG.com - The Witcher 2 Enhanced Edition"
SHORTCUT_NAME="The Witcher 2: Assassins of Kings EE"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "CD Projekt RED" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

# This is getting really ugly
if [ "$POL_SELECTED_FILE" ]; then
    POL_GoG_location="$POL_SELECTED_FILE"
elif [ -e "$(POL_Config_Read GOG_REPO)/setup_the_witcher_2_ee_3.0.1.17.bin" ]; then
    # Already downloaded and renamed
    POL_GoG_location="$(POL_Config_Read GOG_REPO)/setup_the_witcher_2_ee_3.0.1.17.exe"
else
    POL_Call POL_GoG_setup "$GOGID" "b8c84b47644b53c5d3c9e1a2c9bb3a2e" "bc207a9ee725ccce2fad933861ffa299" "740dc01dfa936ea4755049d0fd8a3fe4" "b96ba44d1f33f4e73941f490f2828982" "b56b54012f218d887863ce778ef77e5a" "5d06e0b2bd1aa47697578cacbc8c1ed4" "8698adebaafab3ff9aa0303934bac1e3" "7efb39400446f2609ad11eeb7a7e2a14" "01a8b34c6a115cc16da61a8510072351" "ce4a8cb2360a358c35dc72d959652725"
    
    if [ "$POL_GoG_downloaded" = "True" ]; then
        cd "$(POL_Config_Read GOG_REPO)"
        # silly rename, or InnoSetup won't find all its pieces
        mv setup_the_witcher_2.exe setup_the_witcher_2_ee_3.0.1.17.exe
        mv setup_the_witcher_2-1.bin setup_the_witcher_2_ee_3.0.1.17.bin
        for i in 2 3 4 5 6 7 8 9; do
            mv setup_the_witcher_2-$i.bin setup_the_witcher_2_ee_3.0.1.17-$((i-1)).bin
        done
	POL_GoG_location="$PWD/setup_the_witcher_2_ee_3.0.1.17.exe"
    fi
fi

# POL_System_SetArch "auto"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Call POL_Install_d3dcompiler_43
# POL_Call POL_Install_xact
# POL_Call POL_Install_dotnet40

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "512"

POL_Wine_Direct3D "UseGLSL" "disabled"
POL_Wine_SetVideoDriver

# Doesn't hurt ;)
POL_Wine_reboot

MANUAL="manual_en.pdf"
[ "$POL_LANG" = "es" ] && MANUAL="manual_es.pdf"
[ "$POL_LANG" = "it" ] && MANUAL="manual_it.pdf"
[ "$POL_LANG" = "de" ] && MANUAL="manual_de.pdf"
[ "$POL_LANG" = "fr" ] && MANUAL="manual_fr.pdf"
[ "$POL_LANG" = "pl" ] && MANUAL="manual_pl.pdf"
[ "$POL_LANG" = "cz" ] && MANUAL="manual_cz.pdf"
[ "$POL_LANG" = "hu" ] && MANUAL="manual_hu.pdf"
[ "$POL_LANG" = "jp" ] && MANUAL="manual_jp.pdf"

POL_Shortcut "witcher2.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/The Witcher 2 Enhanced Edition/$MANUAL"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES
cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/The Witcher 2 Enhanced Edition/bin/" || exit 1
TITLE="$TITLE"
POL_Wine Configurator.exe
exit 0
_EOF_

# Run the configurator? Ok!
bash "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"

exit 0
