#!/bin/bash
# Date : (2012-07-15 21-36)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="wing_commander_4_the_price_of_freedom"
PREFIX="WingCommander4_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="GOG.com - Wing Commander 4 - The Price of Freedom"
SHORTCUT_NAME="Wing Commander 4: The Price of Freedom"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Origin Systems / Electronic Arts" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "23b66d7ecec15f105cf675343af8d60c" "cf61c4cda510062a7ddcb3224dd99ed3" "855de57d2fc43b3388cf33199d9799b6" "f0fadbb85e9b498520315561b55848a1" "47e2c9c22f31853a947a5150552bc5fa"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# GoG work!
Set_OS winxp

# POL_Call POL_Install_devenum
# POL_Call POL_Install_quartz
# POL_Call POL_Install_wmp9

# Who knows
POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "wc4dvd.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Wing Commander IV/Manual.pdf"
# C:\Program Files\GOG.com\Wing Commander IV\Playguide.pdf

POL_SetupWindow_Close

exit 0
