#!/bin/bash
# Date : (2012-07-15 21-36)
# Last revision : (2013-05-09 12-42)
# Wine version used : 1.5.29
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="wing_commander_4_the_price_of_freedom"
PREFIX="WingCommander4_gog"
WORKING_WINE_VERSION="1.5.29"

TITLE="GOG.com - Wing Commander 4 - The Price of Freedom"
SHORTCUT_NAME="Wing Commander 4: The Price of Freedom"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Origin Systems / Electronic Arts" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "4d9bda3717e83bb855b89f62fdec0b22" "364873a4948bbd4fe26b81aeee433638" "c9832f38dba0d70f5ab082cf5b760e09" "8482f1534f7f0fc5a4c8a49a5bce9545" "41841c307852308c23196e26291e06e0" "4f8a86c457c01c23262e8246471731c0"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

# POL_Call POL_Install_devenum
# POL_Call POL_Install_quartz
# POL_Call POL_Install_wmp9

# POL_Call POL_Install_amstream
# POL_Call POL_Install_ffdshow

# Who knows
POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "wc4dvd.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Wing Commander IV/Manual.pdf"
# C:\Program Files\GOG.com\Wing Commander IV\Playguide.pdf

POL_SetupWindow_Close

exit 0
