#!/usr/bin/env playonlinux-bash
# Date : (2012-02-12 16-11)
# Last revision : (2013-03-26 00-09)
# Wine version used : 1.3.37
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="WarInThePacific_AdmiralsEdition"
WORKING_WINE_VERSION="1.3.37"
INSTALLBIN=""

TITLE="War In The Pacific: Admiral's Edition"
URL="http://www.matrixgames.com/products/351/details/War.in.the.Pacific.-.Admiral%27s.Edition"
SHORTCUT_NAME="War In The Pacific: Admiral's Edition"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Henderson Field Designs / Matrix Games" "$URL" "Fredrik Vollan (Pierre Etchemaite)" "$PREFIX"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" ""
ARCHIVE="$APP_ANSWER"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

Set_OS winxp

POL_SetupWindow_VMS "128"

POL_Call POL_Install_vcrun2008
POL_Call POL_Install_quartz
POL_Call POL_Install_ffdshow
POL_Call POL_Install_devenum
POL_Call POL_Install_msasn1
POL_Call POL_Install_dsound # didn't try the built in one
POL_Call POL_Install_directmusic # didn't try the built in one
POL_Call POL_Install_msxml4
POL_Call POL_Install_mfc42
POL_Call POL_Install_wmp9
POL_Call POL_Install_wmp9codecs

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "War in the Pacific Admiral Edition.exe" "$SHORTCUT_NAME" "" '${WIDTH:+-px $WIDTH} ${HEIGHT:+-py $HEIGHT}' "Game;StrategyGame;"
# Should work correctly in 4.0.15?
Pol_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'WIDTH=`xrandr -q | grep current | awk "{ print \$8 }"`'
Pol_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'HEIGHT=`xrandr -q | grep current | awk "{ print \$10 }" | tr -d ,`'

POL_SetupWindow_Close

exit 0
