#!/bin/bash
# Date : (2012-05-27 12-14)
# Last revision : (2012-05-27 13-04)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="sid_meiers_alpha_centauri"
PREFIX="AlphaCentauri_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="Sid Meier's Alpha Centauri (GoG release)"
SHORTCUT_NAME="Sid Meier's Alpha Centauri"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

which sox || POL_Debug_Fatal "This script needs 'sox' to improve game sounds"

POL_SetupWindow_presentation "$TITLE" "Firaxis Games / Electronic Arts" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "d9bd6f055c1d08ee4aacf480ad4d62a0"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "2"

POL_SetupWindow_pulsebar "$(eval_gettext 'Resampling game sounds')" "$TITLE"
cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOGcom/Sid Meiers Alpha Centauri/fx" || POL_Debug_Fatal "game not in standard path?"
mkdir orig || POL_Debug_Fatal "Failed to create directory"
mv *.wav orig
cd orig
PULSE=0
for i in *.wav; do 
    let PULSE=$((PULSE+100))
    POL_SetupWindow_set_text "$i"
    POL_SetupWindow_pulse "$((PULSE / 291))"
    case "$i" in
#        cpu*|CPU*)
            # Seem hardcoded to play at 22.05kHz
#            cp "$i" "../$i"
#            ;;
        *)
            sox "$i" "../$i" rate -q 48000 # 44100
            ;;
    esac
done

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "terran.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_QuietDebug "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOGcom/Sid Meiers Alpha Centauri/Manual.pdf"
# C:\Program Files\GOGcom\Sid Meiers Alpha Centauri\readme.txt

POL_SetupWindow_Close

exit
