#!/usr/bin/env playonlinux-bash
# Date : (2012-05-17 16-12)
# Last revision : (2013-04-23 22-06)
# Wine version used : 1.5.13
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="another_world_20th_anniversary_edition"
PREFIX="AnotherWorld20_gog"
WORKING_WINE_VERSION="1.5.13"

TITLE="GOG.com - Another World: 20th Anniversary Edition"
SHORTCUT_NAME="Another World (20th Anniversary)"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1230
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Eric Chahi / Digital Lounge" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "45c5922d183b89669ee2d2471a147049"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

POL_Wine_DirectInput "MouseWarpOverride" "disable"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "anowor.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"

# Disable autorepeat to avoid flooding the game with keyboard events
#POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'xset r off'
#echo "xset r on" >> "$POL_USER_ROOT/shortcuts/$SHORTCUT_NAME"

POL_SetupWindow_Close

exit 0
