#!/bin/bash
# Date : (2011-12-14 23-58)
# Last revision : (2012-06-03 23-35)
# Wine version used : 1.5.0
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested up to 1.3.35 without native DirectSound, and still looping sounds
# Same thing with 1.3.36
# Same thing with 1.5.0 (less often I feel)

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="beyond_good_and_evil"
PREFIX="BeyondGaE_gog"
WORKING_WINE_VERSION="1.5.0"

TITLE="Beyond Good and Evil (GoG release)"
SHORTCUT_NAME="Beyond Good and Evil"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ubisoft" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "75ccff61fc37b3b04245f094850dce88"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

# Can only get lots of looping sounds (2s loops) without native DirectSound
# (and emulated sound outputs?)
# Not so bad as it used to in 1.5.0?
# POL_Call POL_install_dsound

# GoG work!
Set_OS winxp

# Has problems when unconstrained
Set_Desktop "On" "1024" "768"

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

convert "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Beyond Good and Evil/game.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT_NAME"
POL_Shortcut "BGE.exe" "$SHORTCUT_NAME"
# Fixes a problem with CPU management on modern computers (specially laptops):
# BGE doesn't handle variable frequency, so make sure they stay at top frequency
# with a background busy loop (other means are less portable and/or require root privileges)
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'taskset -pc 0 $$'
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'nice -19 bash -c "while true; do let i=1; done" &'
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'BUSYLOOP_PID=$!'
echo 'kill $BUSYLOOP_PID' >> "$POL_USER_ROOT/shortcuts/$SHORTCUT_NAME"

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Beyond Good and Evil/manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Beyond Good and Evil/readme.txt

POL_SetupWindow_message "$(eval_gettext 'Remember to run the configurator once before playing.')" "$TITLE"

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Beyond Good and Evil/" || exit 1

TITLE="$TITLE"

POL_Wine "SettingsApplication.exe"

exit
_EOF_

exit
