#!/bin/bash
# Date : (2011-12-14 23-58)
# Last revision : (2012-01-29 17-07)
# Wine version used : 1.3.23
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Tested with install archive:
# setup_beyond_good_and_evil.exe 1544566386 "75ccff61fc37b3b04245f094850dce88"

# Tested up to 1.3.35 without native DirectSound, and still looping sounds
# Same thing with 1.3.36

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="BeyondGaE_gog"
WORKING_WINE_VERSION="1.3.23"
INSTALLBIN="setup_beyond_good_and_evil.exe"

TITLE="$(eval_gettext 'Beyond Good and Evil (GoG release)')"
URL="http://www.gog.com/en/gamecard/beyond_good_and_evil"
SHORTCUT_NAME="Beyond Good and Evil"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ubisoft" "$URL" "Pierre Etchemaite" "$PREFIX"

POL_SetupWindow_question "$(eval_gettext 'Do you want to download $TITLE from GOG.com?')" "$TITLE"
[ "$APP_ANSWER" = "TRUE" ] && POL_Browser "$URL"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "$INSTALLBIN"
ARCHIVE="$APP_ANSWER"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

# Can only get lots of looping sounds (2s loops) without native DirectSound
# (and emulated sound outputs?)
POL_Call POL_install_dsound

# GoG work!
Set_OS winxp

# Has problems when unconstrained
Set_Desktop "On" "1024" "768"

POL_SetupWindow_VMS "32"

# Doesn't hurt ;)
POL_Wine_reboot

convert "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Beyond Good and Evil/game.ico" "$POL_USER_ROOT/icones/32/$SHORTCUT_NAME"
POL_Shortcut "BGE.exe" "$SHORTCUT_NAME"
# Fixes a problem with CPU management on modern computers (specially laptops):
# BGE doesn't handle variable frequency, so make sure they stay at top frequency
# with a background busy loop (other means are less portable and/or require root privileges)
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'schedtool -a 0x1 $$'
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'nice -19 bash -c "while true; do let i=1; done" &'
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'BUSYLOOP_PID=$!'
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" 'trap "kill $BUSYLOOP_PID" EXIT'

POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Beyond Good and Evil/manual.pdf"
# C:/$PROGRAMFILES/GOG.com/Beyond Good and Evil/readme.txt

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Beyond Good and Evil/" || exit 1

TITLE="$TITLE"

POL_Wine "SettingsApplication.exe"

exit
_EOF_

exit
