#!/bin/bash
# Date : (2012-03-12 23-44)
# Last revision : (2012-04-19 00-39)
# Wine version used : 1.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="bloodrayne"
PREFIX="BloodRayne1_gog"
WORKING_WINE_VERSION="1.4"

TITLE="BloodRayne (GoG release)"
SHORTCUT_NAME="BloodRayne"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Terminal Reality / Majesco" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "b9925ca60f016cf67cdfafceeb5623e7"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "64"

POL_Wine_X11Drv "GrabFullScreen" "Y"

# Some issues playing this
mv "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/BloodRayne 1/video/Cutscene.exe" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/BloodRayne 1/video/Cutscene.exe.disabled"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "rayne.exe" "$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/BloodRayne 1/manual.pdf"
# C:\Program Files\GOG.com\BloodRayne 1\readme.txt

POL_SetupWindow_Close

exit
