#!/bin/bash
# Date : (2012-05-15 19-03)
# Last revision : (2012-05-24 19-55)
# Wine version used : 1.5.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# Only installs Creatures 3
# The Docking Station wants 16-bits display, and doesn't work even with Xephyr
# You can get native Docking Station from http://www.creaturesdockingstation.com/
# But I have no idea if one can make it to work with this installation of Creatures 3

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="creatures_exodus"
PREFIX="CreaturesExodus_gog"
WORKING_WINE_VERSION="1.5.4"

TITLE="Creatures Exodus (GoG release)"
SHORTCUT_NAME1="Creatures 3"
SHORTCUT_NAME2="Creatures: Docking Station"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Creatures Labs / Kalypso Media Digital" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" ""

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

# "SVGA hicolor?"
POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "engine.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" "--autokill Creatures 3"
POL_Shortcut_QuietDebug "$SHORTCUT_NAME1"
POL_Shortcut_Document "$SHORTCUT_NAME1" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Creatures Exodus/Creature 3/Walkthrough.pdf"
# C:\Program Files\GOG.com\Creatures Exodus\Creatures 3\ShortcutCard.pdf

#POL_Shortcut "InstallBlast.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""
#POL_Shortcut_Document "$SHORTCUT_NAME2" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Creatures Exodus/Docking Station/Manual.pdf"
# C:\Program Files\GOG.com\Creatures Exodus\Docking Station\QuickStartSmall.pdf


POL_SetupWindow_Close

exit
