#!/bin/bash
# Date : (2012-05-26 18-21)
# Last revision : (2014-08-23 21-46)
# Wine version used : 1.7.25
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="desperados_wanted_dead_or_alive"
PREFIX="DesperadosWDOA_gog"
WORKING_WINE_VERSION="1.7.25"

TITLE="GOG.com - Desperados - Wanted Dead or Alive"
SHORTCUT_NAME="Desperados: Wanted Dead or Alive"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Spellbound Entertainment AG / Atari" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "8e2f4e2ade9e641fdd35a9dd36d55d00"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

cd "$POL_USER_ROOT/tmp"
POL_Download "http://files.playonlinux.com/msadp32.acm.zip" "78d7dc0fd8babafa108f36c8f649d907"
POL_System_ExtractSingleFile "msadp32.acm.zip" "msadp32.acm" "$WINEPREFIX/drive_c/windows/system32/msadp32.acm"
POL_Wine regsvr32 msadp32.acm
POL_Call POL_Function_OverrideDLL "native" "msadp32.acm"

# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "game.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;StrategyGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Desperados Wanted Dead or Alive/Manual.pdf"
# C:\Program Files\GOG.com\Desperados Wanted Dead or Alive\readme.txt

POL_SetupWindow_Close

exit 0
