#!/bin/bash
# Date : (2013-01-06 16-20)
# Last revision : (2014-08-23 17-52)
# Wine version used : 1.7.25
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="divinity_2_developers_cut"
PREFIX="Divinity2_gog"
WORKING_WINE_VERSION="1.7.25"

TITLE="GOG.com - Divinity 2 Developer's Cut"
SHORTCUT_NAME="Divinity 2"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
#POL_SetupWindow_SetID ScriptIDNumber
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Larian Studios" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" --alternate "setup_$GOGID" 5 "cfd274cac455b7e144c8fd4bee4f2127" "6029e6977ef019fadf1bcf1082d09a92" "bdf7a76142c05dd833d366db5dfc332d" "e100ceec4ff1ae56f7ab61080fc1fd35" "9752465446f857fed6df75e4d7f5cfe0"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_Install_d3dx9_36
POL_Call POL_Install_devenum
POL_Call POL_Install_quartz
POL_Call POL_Install_wmp9
POL_Call POL_Install_wmpcodecs

POL_Call POL_GoG_install "/nogui"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "256"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Divinity2.exe" "$SHORTCUT_NAME Developer's Cut" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
POL_Shortcut_Document "$SHORTCUT_NAME Developer's Cut" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Divinity 2 Developers Cut/manual.pdf"
# C:\Program Files\GOG.com\Divinity 2 Developers Cut\readme.txt

POL_Shortcut "Divinity2-debug.exe" "$SHORTCUT_NAME [Developer Mode]" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"

POL_SetupWindow_Close

exit 0
