#!/bin/bash
# Date : (2012-07-01 19-55)
# Last revision : (2013-02-16 09-37)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="geneforge_15"
PREFIX="Geneforge_1_5_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="GOG.com - Geneforge 1-5"
SHORTCUT_NAME1="Geneforge"
SHORTCUT_NAME2="Geneforge 2"
SHORTCUT_NAME3="Geneforge 3"
SHORTCUT_NAME4="Geneforge 4"
SHORTCUT_NAME5="Geneforge 5"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Spiderweb Software" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "28be4951fc0018de4d3c996f797ed003"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "16"

POL_Wine_DirectInput "MouseWarpOverride" "force"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Geneforge.exe" "$SHORTCUT_NAME1" "$SHORTCUT_NAME1.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME1" "$GOGROOT/Geneforge/Geneforge/Geneforge Manual.pdf"
POL_Shortcut "Geneforge 2.exe" "$SHORTCUT_NAME2" "$SHORTCUT_NAME2.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME2" "$GOGROOT/Geneforge/Geneforge 2/Geneforge 2 Manual.pdf"
POL_Shortcut "Geneforge 3.exe" "$SHORTCUT_NAME3" "$SHORTCUT_NAME3.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME3" "$GOGROOT/Geneforge/Geneforge 3/Geneforge 3 Manual.pdf"
POL_Shortcut "Geneforge 4.exe" "$SHORTCUT_NAME4" "$SHORTCUT_NAME4.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME4" "$GOGROOT/Geneforge/Geneforge 4/Geneforge 4 Manual.pdf"
POL_Shortcut "Geneforge 5.exe" "$SHORTCUT_NAME5" "$SHORTCUT_NAME5.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME5" "$GOGROOT/Geneforge/Geneforge 5/Geneforge 5 Manual.pdf"

POL_SetupWindow_Close

exit 0
