#!/bin/bash
# Date : (2012-05-15 15-33)
# Last revision : (2012-05-24 19-54)
# Wine version used : 1.5.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="lionheart_legacy_of_the_crusader"
PREFIX="Lionheart_gog"
WORKING_WINE_VERSION="1.5.4"

TITLE="Lionheart - Legacy of the Crusader (GoG release)"
SHORTCUT_NAME="Lionheart: Legacy of the Crusader"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Reflexive Entertainment / Interplay" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "08bc4d0075e2f3b8829281f085f43406"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "8"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Lionheart.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Lionheart/MANUAL.PDF"
# C:\Program Files\GOG.com\Lionheart\readme.txt

POL_SetupWindow_Close

exit
