#!/bin/bash
# Date : (2012-07-22 15-32)
# Last revision : (2013-03-24 15-47)
# Wine version used : 1.5.5
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="pro_pinball_big_race_usa"
PREFIX="ProPinballBRU_gog"
WORKING_WINE_VERSION="1.5.5"

TITLE="GOG.com - Pro Pinball Big Race USA"
SHORTCUT_NAME="Pro Pinball Big Race USA"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Cunning Developments / Strategy First" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "23b754c41d52e379434f13dc4a4ff6d2"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine_WaitBefore "$TITLE"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "BigRaceUSA.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Pro Pinball - Big Race USA/Manual.pdf"
# Game has issues with uncapped FPS (menus too fast...) => enable vblank
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "export __GL_SYNC_TO_VBLANK=1" # nvidia?
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME" "export vblank_mode=1"         # others?

POL_SetupWindow_Close

exit 0
