#!/bin/bash
# Date : (2012-05-01 00-01)
# Last revision : (2012-05-01 00-34)
# Wine version used : 1.5.2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="runaway_a_road_adventure"
PREFIX="Runaway_gog"
WORKING_WINE_VERSION="1.5.2"

TITLE="Runaway: A Road Adventure (GoG release)"
SHORTCUT_NAME="Runaway: A Road Adventure"

#POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Pendulo Studio / Focus Home Interactive" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "174444af2422d4375d8ea4f2f8d54cbd"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

# GoG work!
Set_OS winxp

# "1024x768 16bits color"
POL_SetupWindow_VMS "2"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Runaway.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
convert ico:"$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Runaway - A Road Adventure/game.ico" png:"$POL_USER_ROOT/icones/32/$SHORTCUT_NAME"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Runaway - A Road Adventure/manual.pdf"
# C:\Program Files\GOG.com\Runaway - A Road Adventure\README.TXT

POL_SetupWindow_Close

exit
