#!/bin/bash
# Date : (2012-05-04 23-09)
# Last revision : (2012-05-05 00-22)
# Wine version used : 1.4-dos_support_0.4
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="screamer"
PREFIX="Screamer_gog"
WORKING_WINE_VERSION="1.4-dos_support_0.4"

TITLE="Screamer (GoG release)"
SHORTCUT_NAME="Screamer"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Graffiti / Interplay" "http://www.gog.com/en/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "b1eb71f08bf477484a6e77777787dcc5"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Prevent GoG installer from installing Acrobat Reader or Foxit in each prefix
POL_Call POL_Function_SetNativeExtension "pdf"

POL_Wine "$POL_GoG_location" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

# Game expects itself at the root of C:
mv "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Screamer/"* "$WINEPREFIX/drive_c/"

# Game is a bit crash-prone http://www.dosbox.com/comp_list.php?showID=723
cat <<'_EOFCFG_' >> "$WINEPREFIX/playonlinux_dos.cfg"
manual_mount=true
cpu_core=dynamic
cpu_cycles=150000
mixer_prebuffer=10
ipx_enable=1
ipx_connection=1
ipx_ipx=true
_EOFCFG_

cat <<_EOFAE_ > "$WINEPREFIX/drive_c/autoexec.bat"
IPXNET STARTSERVER
imgmount d "$WINEPREFIX/drive_c/SCREAMER.inst" -t iso -fs iso
_EOFAE_

# "VGA 256 colors"
POL_SetupWindow_VMS "2"

POL_Shortcut "STARTH.EXE" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" ""
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/manual.pdf"
# C:\Program Files\GOG.com\Screamer\README.TXT

POL_SetupWindow_Close

cat <<_EOF_ > "$POL_USER_ROOT/configurations/configurators/$SHORTCUT_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="\$POL_USER_ROOT/wineprefix/$PREFIX"
export WINEDEBUG="-all"

POL_LoadVar_PROGRAMFILES

cd "\$WINEPREFIX/drive_c/" || exit 1

TITLE="$TITLE"

POL_Debug_Init

POL_Wine SETUP.EXE

exit
_EOF_

exit
