#!/bin/bash
# Date : (2012-10-23 12-18)
# Last revision : (2013-04-13 02-34)
# Wine version used : 1.5.10
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="thief_gold"
PREFIX="Thief_gog"
WORKING_WINE_VERSION="1.5.10"

TITLE="GOG.com - Thief Gold"
SHORTCUT_NAME="Thief: The Dark Project + Gold"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1445
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Looking Glass Studios / Square Enix" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "affb0b391cacf02a117aa1b9f22b9d6a"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_Install_devenum
POL_Call POL_Install_quartz

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "4"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "THIEF.EXE" "$SHORTCUT_NAME" "" "" "Game;ActionGame;" # "$SHORTCUT_NAME.png"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Thief Gold/manual.pdf"
# C:\Program Files\GOG.com\Thief Gold\THIEF_no_ddfix.EXE
# C:\Program Files\GOG.com\Thief Gold\DROMED.EXE
# C:\Program Files\GOG.com\Thief Gold\reference card.pdf

POL_SetupWindow_Close

exit 0
