#!/bin/bash
# Date : (2012-03-17 23-07)
# Last revision : (2013-03-25 23-45)
# Wine version used : 1.5.18
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite pe-pol@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

# 1.5.18 fixes lots of issues with fog and smoke, that could otherwise only be improved by disabling GLSL

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

GOGID="xiii"
PREFIX="XIII_gog"
WORKING_WINE_VERSION="1.5.18"
[ "$POL_OS" = "Mac" ] && WORKING_WINE_VERSION="1.2.3"

TITLE="GOG.com - XIII"
SHORTCUT_NAME="XIII"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_SetupWindow_SetID 1112
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Ubisoft Paris Studios / Ubisoft" "http://www.gog.com/gamecard/$GOGID" "Pierre Etchemaite" "$PREFIX"

POL_Call POL_GoG_setup "$GOGID" "eaa0497b762d36f88da5391acece2197" "55ce207ab42df8278b501be2f836b414" "b1900a394f69d4aba27c1dd585cd164f"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_Call POL_GoG_install


# GoG work!
Set_OS winxp

POL_SetupWindow_VMS "32"

POL_Wine_X11Drv "GrabFullScreen" "Y"
POL_Wine_DirectInput "MouseWarpOverride" "force"

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "xiii.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;ActionGame;"
POL_Shortcut_Document "$SHORTCUT_NAME" "$WINEPREFIX/drive_c/GOG Games/XIII/Manual.pdf"
# C:\GOG Games\XIII\Support\English\Readme.doc

POL_SetupWindow_Close

exit 0
